// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="kernel_trmm_kernel_trmm,hls_ip_2023_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.247500,HLS_SYN_LAT=22801,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=766,HLS_SYN_LUT=900,HLS_VERSION=2023_1_1}" *)

module kernel_trmm (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        alpha,
        A_address0,
        A_ce0,
        A_q0,
        B_address0,
        B_ce0,
        B_we0,
        B_d0,
        B_q0,
        B_address1,
        B_ce1,
        B_q1
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] alpha;
output  [8:0] A_address0;
output   A_ce0;
input  [31:0] A_q0;
output  [9:0] B_address0;
output   B_ce0;
output   B_we0;
output  [31:0] B_d0;
input  [31:0] B_q0;
output  [9:0] B_address1;
output   B_ce1;
input  [31:0] B_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] B_address0;
reg B_ce0;
reg B_we0;
reg[31:0] B_d0;
reg B_ce1;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire  signed [47:0] sext_ln19_fu_117_p1;
reg  signed [47:0] sext_ln19_reg_313;
wire   [0:0] icmp_ln20_fu_168_p2;
reg   [0:0] icmp_ln20_reg_321;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln21_fu_144_p2;
wire   [4:0] select_ln19_fu_174_p3;
reg   [4:0] select_ln19_reg_326;
wire   [4:0] select_ln19_2_fu_182_p3;
reg   [4:0] select_ln19_2_reg_332;
wire   [4:0] select_ln19_1_fu_220_p3;
reg   [4:0] select_ln19_1_reg_339;
wire    ap_CS_fsm_state3;
wire   [9:0] add_ln22_1_fu_255_p2;
reg   [9:0] add_ln22_1_reg_344;
reg   [9:0] B_addr_reg_350;
wire    ap_CS_fsm_state5;
reg  signed [31:0] B_load_reg_355;
wire    ap_CS_fsm_state6;
wire  signed [47:0] sext_ln23_fu_271_p1;
wire    ap_CS_fsm_state7;
reg   [31:0] trunc_ln1_reg_365;
wire    ap_CS_fsm_state8;
wire    grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_start;
wire    grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_done;
wire    grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_idle;
wire    grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_ready;
wire   [9:0] grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_address0;
wire    grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_ce0;
wire    grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_we0;
wire   [31:0] grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_d0;
wire   [9:0] grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_address1;
wire    grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_ce1;
wire   [8:0] grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_A_address0;
wire    grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_A_ce0;
wire  signed [31:0] grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_grp_fu_113_p_din0;
wire  signed [31:0] grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_grp_fu_113_p_din1;
wire    grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_grp_fu_113_p_ce;
reg    grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_start_reg;
wire    ap_CS_fsm_state4;
wire   [63:0] zext_ln22_3_fu_267_p1;
reg   [4:0] j_fu_66;
wire   [4:0] add_ln20_fu_190_p2;
reg   [4:0] indvars_iv_fu_70;
reg   [4:0] i_fu_74;
reg   [9:0] indvar_flatten_fu_78;
wire   [9:0] add_ln21_fu_150_p2;
wire    ap_CS_fsm_state9;
reg  signed [31:0] grp_fu_113_p0;
reg  signed [31:0] grp_fu_113_p1;
wire   [4:0] indvars_iv_next116_fu_162_p2;
wire   [4:0] add_ln19_fu_214_p2;
wire   [5:0] tmp_1_fu_235_p3;
wire   [9:0] tmp_fu_228_p3;
wire   [9:0] zext_ln22_fu_242_p1;
wire   [9:0] sub_ln22_fu_246_p2;
wire   [9:0] zext_ln22_2_fu_252_p1;
wire   [47:0] grp_fu_113_p2;
reg    grp_fu_113_ce;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_start_reg = 1'b0;
end

kernel_trmm_kernel_trmm_Pipeline_VITIS_LOOP_21_3 grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_start),
    .ap_done(grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_done),
    .ap_idle(grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_idle),
    .ap_ready(grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_ready),
    .zext_ln19(select_ln19_1_reg_339),
    .B_address0(grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_address0),
    .B_ce0(grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_ce0),
    .B_we0(grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_we0),
    .B_d0(grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_d0),
    .B_q0(B_q0),
    .B_address1(grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_address1),
    .B_ce1(grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_ce1),
    .B_q1(B_q1),
    .add_ln22_1(add_ln22_1_reg_344),
    .zext_ln19_1(select_ln19_2_reg_332),
    .A_address0(grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_A_address0),
    .A_ce0(grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_A_ce0),
    .A_q0(A_q0),
    .zext_ln20(select_ln19_reg_326),
    .grp_fu_113_p_din0(grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_grp_fu_113_p_din0),
    .grp_fu_113_p_din1(grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_grp_fu_113_p_din1),
    .grp_fu_113_p_dout0(grp_fu_113_p2),
    .grp_fu_113_p_ce(grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_grp_fu_113_p_ce)
);

kernel_trmm_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_113_p0),
    .din1(grp_fu_113_p1),
    .ce(grp_fu_113_ce),
    .dout(grp_fu_113_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_start_reg <= 1'b1;
        end else if ((grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_ready == 1'b1)) begin
            grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_74 <= 5'd0;
    end else if (((icmp_ln21_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_74 <= select_ln19_2_fu_182_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_fu_78 <= 10'd0;
    end else if (((icmp_ln21_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_fu_78 <= add_ln21_fu_150_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvars_iv_fu_70 <= 5'd1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        indvars_iv_fu_70 <= select_ln19_1_fu_220_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j_fu_66 <= 5'd0;
    end else if (((icmp_ln21_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_fu_66 <= add_ln20_fu_190_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        B_addr_reg_350 <= zext_ln22_3_fu_267_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_load_reg_355 <= B_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln22_1_reg_344 <= add_ln22_1_fu_255_p2;
        select_ln19_1_reg_339 <= select_ln19_1_fu_220_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_ln20_reg_321 <= icmp_ln20_fu_168_p2;
        select_ln19_2_reg_332 <= select_ln19_2_fu_182_p3;
        select_ln19_reg_326 <= select_ln19_fu_174_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sext_ln19_reg_313 <= sext_ln19_fu_117_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        trunc_ln1_reg_365 <= {{grp_fu_113_p2[47:16]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        B_address0 = B_addr_reg_350;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        B_address0 = zext_ln22_3_fu_267_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        B_address0 = grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_address0;
    end else begin
        B_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state9))) begin
        B_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        B_ce0 = grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_ce0;
    end else begin
        B_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        B_ce1 = grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_ce1;
    end else begin
        B_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        B_d0 = trunc_ln1_reg_365;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        B_d0 = grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_d0;
    end else begin
        B_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        B_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        B_we0 = grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_we0;
    end else begin
        B_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln21_fu_144_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_144_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_113_ce = grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_grp_fu_113_p_ce;
    end else begin
        grp_fu_113_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_113_p0 = grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_grp_fu_113_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_113_p0 = sext_ln23_fu_271_p1;
    end else begin
        grp_fu_113_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_113_p1 = grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_grp_fu_113_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_113_p1 = sext_ln19_reg_313;
    end else begin
        grp_fu_113_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln21_fu_144_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_A_address0;

assign A_ce0 = grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_A_ce0;

assign B_address1 = grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_B_address1;

assign add_ln19_fu_214_p2 = (indvars_iv_fu_70 + 5'd1);

assign add_ln20_fu_190_p2 = (select_ln19_fu_174_p3 + 5'd1);

assign add_ln21_fu_150_p2 = (indvar_flatten_fu_78 + 10'd1);

assign add_ln22_1_fu_255_p2 = (sub_ln22_fu_246_p2 + zext_ln22_2_fu_252_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_start = grp_kernel_trmm_Pipeline_VITIS_LOOP_21_3_fu_101_ap_start_reg;

assign icmp_ln20_fu_168_p2 = ((j_fu_66 == 5'd30) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_144_p2 = ((indvar_flatten_fu_78 == 10'd600) ? 1'b1 : 1'b0);

assign indvars_iv_next116_fu_162_p2 = (i_fu_74 + 5'd1);

assign select_ln19_1_fu_220_p3 = ((icmp_ln20_reg_321[0:0] == 1'b1) ? add_ln19_fu_214_p2 : indvars_iv_fu_70);

assign select_ln19_2_fu_182_p3 = ((icmp_ln20_fu_168_p2[0:0] == 1'b1) ? indvars_iv_next116_fu_162_p2 : i_fu_74);

assign select_ln19_fu_174_p3 = ((icmp_ln20_fu_168_p2[0:0] == 1'b1) ? 5'd0 : j_fu_66);

assign sext_ln19_fu_117_p1 = $signed(alpha);

assign sext_ln23_fu_271_p1 = B_load_reg_355;

assign sub_ln22_fu_246_p2 = (tmp_fu_228_p3 - zext_ln22_fu_242_p1);

assign tmp_1_fu_235_p3 = {{select_ln19_2_reg_332}, {1'd0}};

assign tmp_fu_228_p3 = {{select_ln19_2_reg_332}, {5'd0}};

assign zext_ln22_2_fu_252_p1 = select_ln19_reg_326;

assign zext_ln22_3_fu_267_p1 = add_ln22_1_reg_344;

assign zext_ln22_fu_242_p1 = tmp_1_fu_235_p3;

endmodule //kernel_trmm
