[project]
name = "llm-rewrite-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llm>=0.27.1",
    "llm-openrouter>=0.5",
    "pyslang>=9.1.0",
    "python-dotenv>=1.1.1",
]
