// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module kernel_doitgen_kernel_doitgen_Pipeline_VITIS_LOOP_23_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        C4_address0,
        C4_ce0,
        C4_q0,
        C4_address1,
        C4_ce1,
        C4_q1,
        sum_address0,
        sum_ce0,
        sum_we0,
        sum_d0,
        sext_ln26,
        sext_ln26_1,
        sext_ln26_2,
        sext_ln26_3,
        sext_ln26_4,
        sext_ln26_5,
        sext_ln26_6,
        sext_ln26_7,
        sext_ln26_8,
        sext_ln26_9,
        sext_ln26_10,
        sext_ln23
);

parameter    ap_ST_fsm_pp0_stage0 = 6'd1;
parameter    ap_ST_fsm_pp0_stage1 = 6'd2;
parameter    ap_ST_fsm_pp0_stage2 = 6'd4;
parameter    ap_ST_fsm_pp0_stage3 = 6'd8;
parameter    ap_ST_fsm_pp0_stage4 = 6'd16;
parameter    ap_ST_fsm_pp0_stage5 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] C4_address0;
output   C4_ce0;
input  [31:0] C4_q0;
output  [7:0] C4_address1;
output   C4_ce1;
input  [31:0] C4_q1;
output  [3:0] sum_address0;
output   sum_ce0;
output   sum_we0;
output  [31:0] sum_d0;
input  [31:0] sext_ln26;
input  [31:0] sext_ln26_1;
input  [31:0] sext_ln26_2;
input  [31:0] sext_ln26_3;
input  [31:0] sext_ln26_4;
input  [31:0] sext_ln26_5;
input  [31:0] sext_ln26_6;
input  [31:0] sext_ln26_7;
input  [31:0] sext_ln26_8;
input  [31:0] sext_ln26_9;
input  [31:0] sext_ln26_10;
input  [31:0] sext_ln23;

reg ap_idle;
reg[7:0] C4_address0;
reg C4_ce0;
reg[7:0] C4_address1;
reg C4_ce1;
reg sum_ce0;
reg sum_we0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_pp0_stage5_subdone;
reg   [0:0] icmp_ln23_reg_943;
reg    ap_condition_exit_pp0_iter0_stage5;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] reg_300;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state8_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state9_pp0_stage2_iter1;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state10_pp0_stage3_iter1;
wire    ap_block_pp0_stage3_11001;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state11_pp0_stage4_iter1;
wire    ap_block_pp0_stage4_11001;
wire    ap_block_pp0_stage5_11001;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state7_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] reg_304;
wire   [47:0] grp_fu_296_p2;
reg   [47:0] reg_308;
wire   [47:0] grp_fu_292_p2;
reg   [47:0] reg_312;
wire  signed [47:0] sext_ln23_cast_fu_316_p1;
reg  signed [47:0] sext_ln23_cast_reg_873;
wire  signed [47:0] sext_ln26_10_cast_fu_320_p1;
reg  signed [47:0] sext_ln26_10_cast_reg_878;
wire  signed [47:0] sext_ln26_9_cast_fu_324_p1;
reg  signed [47:0] sext_ln26_9_cast_reg_883;
wire  signed [47:0] sext_ln26_8_cast_fu_328_p1;
reg  signed [47:0] sext_ln26_8_cast_reg_888;
wire  signed [47:0] sext_ln26_7_cast_fu_332_p1;
reg  signed [47:0] sext_ln26_7_cast_reg_893;
wire  signed [47:0] sext_ln26_6_cast_fu_336_p1;
reg  signed [47:0] sext_ln26_6_cast_reg_898;
wire  signed [47:0] sext_ln26_5_cast_fu_340_p1;
reg  signed [47:0] sext_ln26_5_cast_reg_903;
wire  signed [47:0] sext_ln26_4_cast_fu_344_p1;
reg  signed [47:0] sext_ln26_4_cast_reg_908;
wire  signed [47:0] sext_ln26_3_cast_fu_348_p1;
reg  signed [47:0] sext_ln26_3_cast_reg_913;
wire  signed [47:0] sext_ln26_2_cast_fu_352_p1;
reg  signed [47:0] sext_ln26_2_cast_reg_918;
wire  signed [47:0] sext_ln26_1_cast_fu_356_p1;
reg  signed [47:0] sext_ln26_1_cast_reg_923;
wire  signed [47:0] sext_ln26_cast_fu_360_p1;
reg  signed [47:0] sext_ln26_cast_reg_928;
reg   [3:0] p_2_reg_933;
wire   [0:0] icmp_ln23_fu_372_p2;
wire   [63:0] p_cast_fu_378_p1;
reg   [63:0] p_cast_reg_947;
reg   [63:0] p_cast_reg_947_pp0_iter1_reg;
wire   [5:0] zext_ln26_2_fu_398_p1;
reg   [5:0] zext_ln26_2_reg_962;
wire   [6:0] zext_ln26_1_fu_423_p1;
reg   [6:0] zext_ln26_1_reg_977;
wire  signed [47:0] sext_ln26_11_fu_453_p1;
wire  signed [47:0] sext_ln26_12_fu_458_p1;
reg   [31:0] tmp_5_reg_1013;
wire  signed [47:0] sext_ln26_13_fu_493_p1;
wire  signed [47:0] sext_ln26_14_fu_498_p1;
reg   [31:0] tmp_6_reg_1038;
wire  signed [47:0] sext_ln26_15_fu_556_p1;
wire  signed [47:0] sext_ln26_16_fu_561_p1;
reg   [31:0] tmp_8_reg_1063;
wire  signed [47:0] sext_ln26_17_fu_643_p1;
wire  signed [47:0] sext_ln26_18_fu_648_p1;
reg   [31:0] tmp_s_reg_1078;
wire  signed [47:0] sext_ln26_19_fu_705_p1;
wire  signed [47:0] sext_ln26_20_fu_710_p1;
reg   [31:0] tmp_2_reg_1093;
wire  signed [47:0] sext_ln26_21_fu_762_p1;
wire  signed [47:0] sext_ln26_22_fu_767_p1;
reg   [31:0] tmp_11_reg_1108;
reg   [31:0] trunc_ln26_s_reg_1113;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln26_4_fu_393_p1;
wire   [63:0] zext_ln26_5_fu_407_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln26_6_fu_418_p1;
wire   [63:0] zext_ln26_7_fu_437_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln26_8_fu_448_p1;
wire   [63:0] zext_ln26_9_fu_468_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln26_10_fu_478_p1;
wire   [63:0] zext_ln26_11_fu_514_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln26_12_fu_528_p1;
wire   [63:0] zext_ln26_13_fu_580_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln26_14_fu_591_p1;
reg   [3:0] p_fu_98;
wire   [3:0] add_ln23_fu_566_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_p_2;
reg  signed [31:0] grp_fu_292_p0;
reg  signed [31:0] grp_fu_292_p1;
reg  signed [31:0] grp_fu_296_p0;
reg  signed [31:0] grp_fu_296_p1;
wire   [4:0] zext_ln26_3_fu_383_p1;
wire   [4:0] add_ln26_11_fu_387_p2;
wire   [5:0] add_ln26_12_fu_401_p2;
wire   [5:0] add_ln26_13_fu_412_p2;
wire   [4:0] tmp_3_fu_426_p3;
wire  signed [5:0] sext_ln26_23_fu_433_p1;
wire   [6:0] add_ln26_14_fu_442_p2;
wire   [6:0] add_ln26_15_fu_463_p2;
wire   [6:0] add_ln26_16_fu_473_p2;
wire   [5:0] tmp_4_fu_503_p3;
wire  signed [6:0] sext_ln26_24_fu_510_p1;
wire   [5:0] add_ln26_17_fu_519_p2;
wire  signed [6:0] sext_ln26_25_fu_524_p1;
wire   [47:0] shl_ln_fu_533_p3;
wire   [47:0] add_ln26_fu_540_p2;
wire   [7:0] zext_ln26_fu_571_p1;
wire   [7:0] add_ln26_18_fu_574_p2;
wire   [7:0] add_ln26_19_fu_585_p2;
wire   [47:0] shl_ln26_1_fu_596_p3;
wire   [47:0] add_ln26_1_fu_603_p2;
wire   [31:0] tmp_7_fu_609_p4;
wire   [47:0] shl_ln26_2_fu_619_p3;
wire   [47:0] add_ln26_2_fu_627_p2;
wire   [47:0] shl_ln26_3_fu_658_p3;
wire   [47:0] add_ln26_3_fu_665_p2;
wire   [31:0] tmp_9_fu_671_p4;
wire   [47:0] shl_ln26_4_fu_681_p3;
wire   [47:0] add_ln26_4_fu_689_p2;
wire   [47:0] shl_ln26_5_fu_715_p3;
wire   [47:0] add_ln26_5_fu_722_p2;
wire   [31:0] tmp_1_fu_728_p4;
wire   [47:0] shl_ln26_6_fu_738_p3;
wire   [47:0] add_ln26_6_fu_746_p2;
wire   [47:0] shl_ln26_7_fu_772_p3;
wire   [47:0] add_ln26_7_fu_779_p2;
wire   [31:0] tmp_10_fu_785_p4;
wire   [47:0] shl_ln26_8_fu_795_p3;
wire   [47:0] add_ln26_8_fu_803_p2;
wire   [47:0] shl_ln26_9_fu_819_p3;
wire   [47:0] add_ln26_9_fu_826_p2;
wire   [31:0] tmp_12_fu_832_p4;
wire   [47:0] shl_ln26_s_fu_842_p3;
wire   [47:0] add_ln26_10_fu_850_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [5:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

kernel_doitgen_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_292_p0),
    .din1(grp_fu_292_p1),
    .ce(1'b1),
    .dout(grp_fu_292_p2)
);

kernel_doitgen_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_296_p0),
    .din1(grp_fu_296_p1),
    .ce(1'b1),
    .dout(grp_fu_296_p2)
);

kernel_doitgen_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage5),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_exit_pp0_iter0_stage5) | ((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_fu_98 <= 4'd0;
    end else if (((icmp_ln23_reg_943 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        p_fu_98 <= add_ln23_fu_566_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln23_reg_943 <= icmp_ln23_fu_372_p2;
        p_2_reg_933 <= ap_sig_allocacmp_p_2;
        p_cast_reg_947_pp0_iter1_reg[3 : 0] <= p_cast_reg_947[3 : 0];
        sext_ln23_cast_reg_873 <= sext_ln23_cast_fu_316_p1;
        sext_ln26_10_cast_reg_878 <= sext_ln26_10_cast_fu_320_p1;
        sext_ln26_1_cast_reg_923 <= sext_ln26_1_cast_fu_356_p1;
        sext_ln26_2_cast_reg_918 <= sext_ln26_2_cast_fu_352_p1;
        sext_ln26_3_cast_reg_913 <= sext_ln26_3_cast_fu_348_p1;
        sext_ln26_4_cast_reg_908 <= sext_ln26_4_cast_fu_344_p1;
        sext_ln26_5_cast_reg_903 <= sext_ln26_5_cast_fu_340_p1;
        sext_ln26_6_cast_reg_898 <= sext_ln26_6_cast_fu_336_p1;
        sext_ln26_7_cast_reg_893 <= sext_ln26_7_cast_fu_332_p1;
        sext_ln26_8_cast_reg_888 <= sext_ln26_8_cast_fu_328_p1;
        sext_ln26_9_cast_reg_883 <= sext_ln26_9_cast_fu_324_p1;
        sext_ln26_cast_reg_928 <= sext_ln26_cast_fu_360_p1;
        tmp_s_reg_1078 <= {{add_ln26_4_fu_689_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln23_fu_372_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_cast_reg_947[3 : 0] <= p_cast_fu_378_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln23_reg_943 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((icmp_ln23_reg_943 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((icmp_ln23_reg_943 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((icmp_ln23_reg_943 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln23_reg_943 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_300 <= C4_q1;
        reg_304 <= C4_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln23_reg_943 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((icmp_ln23_reg_943 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((icmp_ln23_reg_943 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_308 <= grp_fu_296_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln23_reg_943 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((icmp_ln23_reg_943 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_312 <= grp_fu_292_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_11_reg_1108 <= {{add_ln26_8_fu_803_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_2_reg_1093 <= {{add_ln26_6_fu_746_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln23_reg_943 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        tmp_5_reg_1013 <= {{grp_fu_292_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln23_reg_943 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        tmp_6_reg_1038 <= {{add_ln26_fu_540_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln23_reg_943 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        tmp_8_reg_1063 <= {{add_ln26_2_fu_627_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        trunc_ln26_s_reg_1113 <= {{add_ln26_10_fu_850_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln23_reg_943 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        zext_ln26_1_reg_977[3 : 0] <= zext_ln26_1_fu_423_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln23_reg_943 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        zext_ln26_2_reg_962[3 : 0] <= zext_ln26_2_fu_398_p1[3 : 0];
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            C4_address0 = zext_ln26_14_fu_591_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            C4_address0 = zext_ln26_12_fu_528_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            C4_address0 = zext_ln26_10_fu_478_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            C4_address0 = zext_ln26_8_fu_448_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            C4_address0 = zext_ln26_6_fu_418_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            C4_address0 = zext_ln26_4_fu_393_p1;
        end else begin
            C4_address0 = 'bx;
        end
    end else begin
        C4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            C4_address1 = zext_ln26_13_fu_580_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            C4_address1 = zext_ln26_11_fu_514_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            C4_address1 = zext_ln26_9_fu_468_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            C4_address1 = zext_ln26_7_fu_437_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            C4_address1 = zext_ln26_5_fu_407_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            C4_address1 = p_cast_fu_378_p1;
        end else begin
            C4_address1 = 'bx;
        end
    end else begin
        C4_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        C4_ce0 = 1'b1;
    end else begin
        C4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        C4_ce1 = 1'b1;
    end else begin
        C4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln23_reg_943 == 1'd1) & (1'b0 == ap_block_pp0_stage5_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_condition_exit_pp0_iter0_stage5 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_p_2 = 4'd0;
    end else begin
        ap_sig_allocacmp_p_2 = p_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_292_p0 = sext_ln26_21_fu_762_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_292_p0 = sext_ln26_19_fu_705_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_292_p0 = sext_ln26_17_fu_643_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_292_p0 = sext_ln26_15_fu_556_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_292_p0 = sext_ln26_13_fu_493_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_292_p0 = sext_ln26_11_fu_453_p1;
    end else begin
        grp_fu_292_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_292_p1 = sext_ln26_10_cast_reg_878;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_292_p1 = sext_ln26_8_cast_reg_888;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_292_p1 = sext_ln26_6_cast_reg_898;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_292_p1 = sext_ln26_4_cast_reg_908;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_292_p1 = sext_ln26_2_cast_reg_918;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_292_p1 = sext_ln26_cast_reg_928;
    end else begin
        grp_fu_292_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_296_p0 = sext_ln26_22_fu_767_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_296_p0 = sext_ln26_20_fu_710_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_296_p0 = sext_ln26_18_fu_648_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_296_p0 = sext_ln26_16_fu_561_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_296_p0 = sext_ln26_14_fu_498_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_296_p0 = sext_ln26_12_fu_458_p1;
    end else begin
        grp_fu_296_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_296_p1 = sext_ln23_cast_reg_873;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_296_p1 = sext_ln26_9_cast_reg_883;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_296_p1 = sext_ln26_7_cast_reg_893;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_296_p1 = sext_ln26_5_cast_reg_903;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_296_p1 = sext_ln26_3_cast_reg_913;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_296_p1 = sext_ln26_1_cast_reg_923;
    end else begin
        grp_fu_296_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        sum_ce0 = 1'b1;
    end else begin
        sum_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        sum_we0 = 1'b1;
    end else begin
        sum_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln23_fu_566_p2 = (p_2_reg_933 + 4'd1);

assign add_ln26_10_fu_850_p2 = (shl_ln26_s_fu_842_p3 + reg_308);

assign add_ln26_11_fu_387_p2 = (zext_ln26_3_fu_383_p1 + 5'd12);

assign add_ln26_12_fu_401_p2 = (zext_ln26_2_fu_398_p1 + 6'd24);

assign add_ln26_13_fu_412_p2 = ($signed(zext_ln26_2_fu_398_p1) + $signed(6'd36));

assign add_ln26_14_fu_442_p2 = (zext_ln26_1_fu_423_p1 + 7'd60);

assign add_ln26_15_fu_463_p2 = ($signed(zext_ln26_1_reg_977) + $signed(7'd72));

assign add_ln26_16_fu_473_p2 = ($signed(zext_ln26_1_reg_977) + $signed(7'd84));

assign add_ln26_17_fu_519_p2 = ($signed(zext_ln26_2_reg_962) + $signed(6'd44));

assign add_ln26_18_fu_574_p2 = (zext_ln26_fu_571_p1 + 8'd120);

assign add_ln26_19_fu_585_p2 = ($signed(zext_ln26_fu_571_p1) + $signed(8'd132));

assign add_ln26_1_fu_603_p2 = (shl_ln26_1_fu_596_p3 + reg_312);

assign add_ln26_2_fu_627_p2 = (shl_ln26_2_fu_619_p3 + reg_308);

assign add_ln26_3_fu_665_p2 = (shl_ln26_3_fu_658_p3 + reg_312);

assign add_ln26_4_fu_689_p2 = (shl_ln26_4_fu_681_p3 + reg_308);

assign add_ln26_5_fu_722_p2 = (shl_ln26_5_fu_715_p3 + reg_312);

assign add_ln26_6_fu_746_p2 = (shl_ln26_6_fu_738_p3 + reg_308);

assign add_ln26_7_fu_779_p2 = (shl_ln26_7_fu_772_p3 + reg_312);

assign add_ln26_8_fu_803_p2 = (shl_ln26_8_fu_795_p3 + reg_308);

assign add_ln26_9_fu_826_p2 = (shl_ln26_9_fu_819_p3 + reg_312);

assign add_ln26_fu_540_p2 = (shl_ln_fu_533_p3 + reg_308);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage5;

assign icmp_ln23_fu_372_p2 = ((ap_sig_allocacmp_p_2 == 4'd12) ? 1'b1 : 1'b0);

assign p_cast_fu_378_p1 = ap_sig_allocacmp_p_2;

assign sext_ln23_cast_fu_316_p1 = $signed(sext_ln23);

assign sext_ln26_10_cast_fu_320_p1 = $signed(sext_ln26_10);

assign sext_ln26_11_fu_453_p1 = $signed(reg_300);

assign sext_ln26_12_fu_458_p1 = $signed(reg_304);

assign sext_ln26_13_fu_493_p1 = $signed(reg_300);

assign sext_ln26_14_fu_498_p1 = $signed(reg_304);

assign sext_ln26_15_fu_556_p1 = $signed(reg_300);

assign sext_ln26_16_fu_561_p1 = $signed(reg_304);

assign sext_ln26_17_fu_643_p1 = $signed(reg_300);

assign sext_ln26_18_fu_648_p1 = $signed(reg_304);

assign sext_ln26_19_fu_705_p1 = $signed(reg_300);

assign sext_ln26_1_cast_fu_356_p1 = $signed(sext_ln26_1);

assign sext_ln26_20_fu_710_p1 = $signed(reg_304);

assign sext_ln26_21_fu_762_p1 = $signed(reg_300);

assign sext_ln26_22_fu_767_p1 = $signed(reg_304);

assign sext_ln26_23_fu_433_p1 = $signed(tmp_3_fu_426_p3);

assign sext_ln26_24_fu_510_p1 = $signed(tmp_4_fu_503_p3);

assign sext_ln26_25_fu_524_p1 = $signed(add_ln26_17_fu_519_p2);

assign sext_ln26_2_cast_fu_352_p1 = $signed(sext_ln26_2);

assign sext_ln26_3_cast_fu_348_p1 = $signed(sext_ln26_3);

assign sext_ln26_4_cast_fu_344_p1 = $signed(sext_ln26_4);

assign sext_ln26_5_cast_fu_340_p1 = $signed(sext_ln26_5);

assign sext_ln26_6_cast_fu_336_p1 = $signed(sext_ln26_6);

assign sext_ln26_7_cast_fu_332_p1 = $signed(sext_ln26_7);

assign sext_ln26_8_cast_fu_328_p1 = $signed(sext_ln26_8);

assign sext_ln26_9_cast_fu_324_p1 = $signed(sext_ln26_9);

assign sext_ln26_cast_fu_360_p1 = $signed(sext_ln26);

assign shl_ln26_1_fu_596_p3 = {{tmp_6_reg_1038}, {16'd0}};

assign shl_ln26_2_fu_619_p3 = {{tmp_7_fu_609_p4}, {16'd0}};

assign shl_ln26_3_fu_658_p3 = {{tmp_8_reg_1063}, {16'd0}};

assign shl_ln26_4_fu_681_p3 = {{tmp_9_fu_671_p4}, {16'd0}};

assign shl_ln26_5_fu_715_p3 = {{tmp_s_reg_1078}, {16'd0}};

assign shl_ln26_6_fu_738_p3 = {{tmp_1_fu_728_p4}, {16'd0}};

assign shl_ln26_7_fu_772_p3 = {{tmp_2_reg_1093}, {16'd0}};

assign shl_ln26_8_fu_795_p3 = {{tmp_10_fu_785_p4}, {16'd0}};

assign shl_ln26_9_fu_819_p3 = {{tmp_11_reg_1108}, {16'd0}};

assign shl_ln26_s_fu_842_p3 = {{tmp_12_fu_832_p4}, {16'd0}};

assign shl_ln_fu_533_p3 = {{tmp_5_reg_1013}, {16'd0}};

assign sum_address0 = p_cast_reg_947_pp0_iter1_reg;

assign sum_d0 = trunc_ln26_s_reg_1113;

assign tmp_10_fu_785_p4 = {{add_ln26_7_fu_779_p2[47:16]}};

assign tmp_12_fu_832_p4 = {{add_ln26_9_fu_826_p2[47:16]}};

assign tmp_1_fu_728_p4 = {{add_ln26_5_fu_722_p2[47:16]}};

assign tmp_3_fu_426_p3 = {{1'd1}, {p_2_reg_933}};

assign tmp_4_fu_503_p3 = {{2'd2}, {p_2_reg_933}};

assign tmp_7_fu_609_p4 = {{add_ln26_1_fu_603_p2[47:16]}};

assign tmp_9_fu_671_p4 = {{add_ln26_3_fu_665_p2[47:16]}};

assign zext_ln26_10_fu_478_p1 = add_ln26_16_fu_473_p2;

assign zext_ln26_11_fu_514_p1 = $unsigned(sext_ln26_24_fu_510_p1);

assign zext_ln26_12_fu_528_p1 = $unsigned(sext_ln26_25_fu_524_p1);

assign zext_ln26_13_fu_580_p1 = add_ln26_18_fu_574_p2;

assign zext_ln26_14_fu_591_p1 = add_ln26_19_fu_585_p2;

assign zext_ln26_1_fu_423_p1 = p_2_reg_933;

assign zext_ln26_2_fu_398_p1 = p_2_reg_933;

assign zext_ln26_3_fu_383_p1 = ap_sig_allocacmp_p_2;

assign zext_ln26_4_fu_393_p1 = add_ln26_11_fu_387_p2;

assign zext_ln26_5_fu_407_p1 = add_ln26_12_fu_401_p2;

assign zext_ln26_6_fu_418_p1 = add_ln26_13_fu_412_p2;

assign zext_ln26_7_fu_437_p1 = $unsigned(sext_ln26_23_fu_433_p1);

assign zext_ln26_8_fu_448_p1 = add_ln26_14_fu_442_p2;

assign zext_ln26_9_fu_468_p1 = add_ln26_15_fu_463_p2;

assign zext_ln26_fu_571_p1 = p_2_reg_933;

always @ (posedge ap_clk) begin
    p_cast_reg_947[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_947_pp0_iter1_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_962[5:4] <= 2'b00;
    zext_ln26_1_reg_977[6:4] <= 3'b000;
end

endmodule //kernel_doitgen_kernel_doitgen_Pipeline_VITIS_LOOP_23_3
