// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module kernel_mvt_kernel_mvt_Pipeline_VITIS_LOOP_21_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        A_address1,
        A_ce1,
        A_q1,
        x1_address0,
        x1_ce0,
        x1_we0,
        x1_d0,
        x1_q0,
        sext_ln23,
        sext_ln23_1,
        sext_ln23_2,
        sext_ln23_3,
        sext_ln23_4,
        sext_ln23_5,
        sext_ln23_6,
        sext_ln23_7,
        sext_ln23_8,
        sext_ln23_9,
        sext_ln23_10,
        sext_ln23_11,
        sext_ln23_12,
        sext_ln23_13,
        sext_ln23_14,
        sext_ln23_15,
        sext_ln23_16,
        sext_ln23_17,
        sext_ln23_18,
        sext_ln23_19,
        sext_ln23_20,
        sext_ln23_21,
        sext_ln23_22,
        sext_ln23_23,
        sext_ln23_24,
        sext_ln23_25,
        sext_ln23_26,
        sext_ln23_27,
        sext_ln23_28,
        sext_ln23_29,
        sext_ln23_30,
        sext_ln23_31,
        sext_ln23_32,
        sext_ln23_33,
        sext_ln23_34,
        sext_ln23_35,
        sext_ln23_36,
        sext_ln23_37,
        sext_ln23_38,
        sext_ln21,
        grp_fu_1748_p_din0,
        grp_fu_1748_p_din1,
        grp_fu_1748_p_dout0,
        grp_fu_1748_p_ce,
        grp_fu_1752_p_din0,
        grp_fu_1752_p_din1,
        grp_fu_1752_p_dout0,
        grp_fu_1752_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 20'd1;
parameter    ap_ST_fsm_pp0_stage1 = 20'd2;
parameter    ap_ST_fsm_pp0_stage2 = 20'd4;
parameter    ap_ST_fsm_pp0_stage3 = 20'd8;
parameter    ap_ST_fsm_pp0_stage4 = 20'd16;
parameter    ap_ST_fsm_pp0_stage5 = 20'd32;
parameter    ap_ST_fsm_pp0_stage6 = 20'd64;
parameter    ap_ST_fsm_pp0_stage7 = 20'd128;
parameter    ap_ST_fsm_pp0_stage8 = 20'd256;
parameter    ap_ST_fsm_pp0_stage9 = 20'd512;
parameter    ap_ST_fsm_pp0_stage10 = 20'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 20'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 20'd4096;
parameter    ap_ST_fsm_pp0_stage13 = 20'd8192;
parameter    ap_ST_fsm_pp0_stage14 = 20'd16384;
parameter    ap_ST_fsm_pp0_stage15 = 20'd32768;
parameter    ap_ST_fsm_pp0_stage16 = 20'd65536;
parameter    ap_ST_fsm_pp0_stage17 = 20'd131072;
parameter    ap_ST_fsm_pp0_stage18 = 20'd262144;
parameter    ap_ST_fsm_pp0_stage19 = 20'd524288;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] A_address0;
output   A_ce0;
input  [31:0] A_q0;
output  [10:0] A_address1;
output   A_ce1;
input  [31:0] A_q1;
output  [5:0] x1_address0;
output   x1_ce0;
output   x1_we0;
output  [31:0] x1_d0;
input  [31:0] x1_q0;
input  [31:0] sext_ln23;
input  [31:0] sext_ln23_1;
input  [31:0] sext_ln23_2;
input  [31:0] sext_ln23_3;
input  [31:0] sext_ln23_4;
input  [31:0] sext_ln23_5;
input  [31:0] sext_ln23_6;
input  [31:0] sext_ln23_7;
input  [31:0] sext_ln23_8;
input  [31:0] sext_ln23_9;
input  [31:0] sext_ln23_10;
input  [31:0] sext_ln23_11;
input  [31:0] sext_ln23_12;
input  [31:0] sext_ln23_13;
input  [31:0] sext_ln23_14;
input  [31:0] sext_ln23_15;
input  [31:0] sext_ln23_16;
input  [31:0] sext_ln23_17;
input  [31:0] sext_ln23_18;
input  [31:0] sext_ln23_19;
input  [31:0] sext_ln23_20;
input  [31:0] sext_ln23_21;
input  [31:0] sext_ln23_22;
input  [31:0] sext_ln23_23;
input  [31:0] sext_ln23_24;
input  [31:0] sext_ln23_25;
input  [31:0] sext_ln23_26;
input  [31:0] sext_ln23_27;
input  [31:0] sext_ln23_28;
input  [31:0] sext_ln23_29;
input  [31:0] sext_ln23_30;
input  [31:0] sext_ln23_31;
input  [31:0] sext_ln23_32;
input  [31:0] sext_ln23_33;
input  [31:0] sext_ln23_34;
input  [31:0] sext_ln23_35;
input  [31:0] sext_ln23_36;
input  [31:0] sext_ln23_37;
input  [31:0] sext_ln23_38;
input  [31:0] sext_ln21;
output  [31:0] grp_fu_1748_p_din0;
output  [31:0] grp_fu_1748_p_din1;
input  [47:0] grp_fu_1748_p_dout0;
output   grp_fu_1748_p_ce;
output  [31:0] grp_fu_1752_p_din0;
output  [31:0] grp_fu_1752_p_din1;
input  [47:0] grp_fu_1752_p_dout0;
output   grp_fu_1752_p_ce;

reg ap_idle;
reg[10:0] A_address0;
reg A_ce0;
reg[10:0] A_address1;
reg A_ce1;
reg[5:0] x1_address0;
reg x1_ce0;
reg x1_we0;

(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state25_pp0_stage4_iter1;
wire    ap_block_pp0_stage4_subdone;
reg   [0:0] icmp_ln21_reg_2783;
reg    ap_condition_exit_pp0_iter0_stage4;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage19;
wire    ap_block_state20_pp0_stage19_iter0;
wire    ap_block_pp0_stage19_subdone;
reg   [31:0] reg_808;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state22_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state23_pp0_stage2_iter1;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state24_pp0_stage3_iter1;
wire    ap_block_pp0_stage3_11001;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_pp0_stage5_11001;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state7_pp0_stage6_iter0;
wire    ap_block_pp0_stage6_11001;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state8_pp0_stage7_iter0;
wire    ap_block_pp0_stage7_11001;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_state9_pp0_stage8_iter0;
wire    ap_block_pp0_stage8_11001;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_state10_pp0_stage9_iter0;
wire    ap_block_pp0_stage9_11001;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_state11_pp0_stage10_iter0;
wire    ap_block_pp0_stage10_11001;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_state12_pp0_stage11_iter0;
wire    ap_block_pp0_stage11_11001;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_state13_pp0_stage12_iter0;
wire    ap_block_pp0_stage12_11001;
wire    ap_CS_fsm_pp0_stage13;
wire    ap_block_state14_pp0_stage13_iter0;
wire    ap_block_pp0_stage13_11001;
wire    ap_CS_fsm_pp0_stage14;
wire    ap_block_state15_pp0_stage14_iter0;
wire    ap_block_pp0_stage14_11001;
wire    ap_CS_fsm_pp0_stage15;
wire    ap_block_state16_pp0_stage15_iter0;
wire    ap_block_pp0_stage15_11001;
wire    ap_CS_fsm_pp0_stage16;
wire    ap_block_state17_pp0_stage16_iter0;
wire    ap_block_pp0_stage16_11001;
wire    ap_CS_fsm_pp0_stage17;
wire    ap_block_state18_pp0_stage17_iter0;
wire    ap_block_pp0_stage17_11001;
wire    ap_CS_fsm_pp0_stage18;
wire    ap_block_state19_pp0_stage18_iter0;
wire    ap_block_pp0_stage18_11001;
wire    ap_block_pp0_stage19_11001;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state21_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] reg_812;
reg   [47:0] reg_816;
reg   [47:0] reg_820;
wire  signed [47:0] sext_ln21_cast_fu_824_p1;
reg  signed [47:0] sext_ln21_cast_reg_2583;
wire  signed [47:0] sext_ln23_38_cast_fu_828_p1;
reg  signed [47:0] sext_ln23_38_cast_reg_2588;
wire  signed [47:0] sext_ln23_37_cast_fu_832_p1;
reg  signed [47:0] sext_ln23_37_cast_reg_2593;
wire  signed [47:0] sext_ln23_36_cast_fu_836_p1;
reg  signed [47:0] sext_ln23_36_cast_reg_2598;
wire  signed [47:0] sext_ln23_35_cast_fu_840_p1;
reg  signed [47:0] sext_ln23_35_cast_reg_2603;
wire  signed [47:0] sext_ln23_34_cast_fu_844_p1;
reg  signed [47:0] sext_ln23_34_cast_reg_2608;
wire  signed [47:0] sext_ln23_33_cast_fu_848_p1;
reg  signed [47:0] sext_ln23_33_cast_reg_2613;
wire  signed [47:0] sext_ln23_32_cast_fu_852_p1;
reg  signed [47:0] sext_ln23_32_cast_reg_2618;
wire  signed [47:0] sext_ln23_31_cast_fu_856_p1;
reg  signed [47:0] sext_ln23_31_cast_reg_2623;
wire  signed [47:0] sext_ln23_30_cast_fu_860_p1;
reg  signed [47:0] sext_ln23_30_cast_reg_2628;
wire  signed [47:0] sext_ln23_29_cast_fu_864_p1;
reg  signed [47:0] sext_ln23_29_cast_reg_2633;
wire  signed [47:0] sext_ln23_28_cast_fu_868_p1;
reg  signed [47:0] sext_ln23_28_cast_reg_2638;
wire  signed [47:0] sext_ln23_27_cast_fu_872_p1;
reg  signed [47:0] sext_ln23_27_cast_reg_2643;
wire  signed [47:0] sext_ln23_26_cast_fu_876_p1;
reg  signed [47:0] sext_ln23_26_cast_reg_2648;
wire  signed [47:0] sext_ln23_25_cast_fu_880_p1;
reg  signed [47:0] sext_ln23_25_cast_reg_2653;
wire  signed [47:0] sext_ln23_24_cast_fu_884_p1;
reg  signed [47:0] sext_ln23_24_cast_reg_2658;
wire  signed [47:0] sext_ln23_23_cast_fu_888_p1;
reg  signed [47:0] sext_ln23_23_cast_reg_2663;
wire  signed [47:0] sext_ln23_22_cast_fu_892_p1;
reg  signed [47:0] sext_ln23_22_cast_reg_2668;
wire  signed [47:0] sext_ln23_21_cast_fu_896_p1;
reg  signed [47:0] sext_ln23_21_cast_reg_2673;
wire  signed [47:0] sext_ln23_20_cast_fu_900_p1;
reg  signed [47:0] sext_ln23_20_cast_reg_2678;
wire  signed [47:0] sext_ln23_19_cast_fu_904_p1;
reg  signed [47:0] sext_ln23_19_cast_reg_2683;
wire  signed [47:0] sext_ln23_18_cast_fu_908_p1;
reg  signed [47:0] sext_ln23_18_cast_reg_2688;
wire  signed [47:0] sext_ln23_17_cast_fu_912_p1;
reg  signed [47:0] sext_ln23_17_cast_reg_2693;
wire  signed [47:0] sext_ln23_16_cast_fu_916_p1;
reg  signed [47:0] sext_ln23_16_cast_reg_2698;
wire  signed [47:0] sext_ln23_15_cast_fu_920_p1;
reg  signed [47:0] sext_ln23_15_cast_reg_2703;
wire  signed [47:0] sext_ln23_14_cast_fu_924_p1;
reg  signed [47:0] sext_ln23_14_cast_reg_2708;
wire  signed [47:0] sext_ln23_13_cast_fu_928_p1;
reg  signed [47:0] sext_ln23_13_cast_reg_2713;
wire  signed [47:0] sext_ln23_12_cast_fu_932_p1;
reg  signed [47:0] sext_ln23_12_cast_reg_2718;
wire  signed [47:0] sext_ln23_11_cast_fu_936_p1;
reg  signed [47:0] sext_ln23_11_cast_reg_2723;
wire  signed [47:0] sext_ln23_10_cast_fu_940_p1;
reg  signed [47:0] sext_ln23_10_cast_reg_2728;
wire  signed [47:0] sext_ln23_9_cast_fu_944_p1;
reg  signed [47:0] sext_ln23_9_cast_reg_2733;
wire  signed [47:0] sext_ln23_8_cast_fu_948_p1;
reg  signed [47:0] sext_ln23_8_cast_reg_2738;
wire  signed [47:0] sext_ln23_7_cast_fu_952_p1;
reg  signed [47:0] sext_ln23_7_cast_reg_2743;
wire  signed [47:0] sext_ln23_6_cast_fu_956_p1;
reg  signed [47:0] sext_ln23_6_cast_reg_2748;
wire  signed [47:0] sext_ln23_5_cast_fu_960_p1;
reg  signed [47:0] sext_ln23_5_cast_reg_2753;
wire  signed [47:0] sext_ln23_4_cast_fu_964_p1;
reg  signed [47:0] sext_ln23_4_cast_reg_2758;
wire  signed [47:0] sext_ln23_3_cast_fu_968_p1;
reg  signed [47:0] sext_ln23_3_cast_reg_2763;
wire  signed [47:0] sext_ln23_2_cast_fu_972_p1;
reg  signed [47:0] sext_ln23_2_cast_reg_2768;
wire  signed [47:0] sext_ln23_1_cast_fu_976_p1;
reg  signed [47:0] sext_ln23_1_cast_reg_2773;
wire  signed [47:0] sext_ln23_cast_fu_980_p1;
reg  signed [47:0] sext_ln23_cast_reg_2778;
wire   [0:0] icmp_ln21_fu_992_p2;
wire   [10:0] add_ln23_40_fu_1029_p2;
reg   [10:0] add_ln23_40_reg_2787;
reg   [5:0] x1_addr_reg_2839;
reg   [5:0] x1_addr_reg_2839_pp0_iter1_reg;
reg   [31:0] x1_load_reg_2854;
wire  signed [47:0] sext_ln23_39_fu_1096_p1;
wire  signed [47:0] sext_ln23_40_fu_1101_p1;
wire  signed [47:0] sext_ln23_41_fu_1126_p1;
wire  signed [47:0] sext_ln23_42_fu_1131_p1;
reg   [31:0] tmp_3_reg_2909;
wire  signed [47:0] sext_ln23_43_fu_1203_p1;
wire  signed [47:0] sext_ln23_44_fu_1208_p1;
reg   [31:0] tmp_5_reg_2934;
wire  signed [47:0] sext_ln23_45_fu_1280_p1;
wire  signed [47:0] sext_ln23_46_fu_1285_p1;
reg   [31:0] tmp_7_reg_2959;
wire  signed [47:0] sext_ln23_47_fu_1357_p1;
wire  signed [47:0] sext_ln23_48_fu_1362_p1;
reg   [31:0] tmp_9_reg_2984;
wire  signed [47:0] sext_ln23_49_fu_1434_p1;
wire  signed [47:0] sext_ln23_50_fu_1439_p1;
reg   [31:0] tmp_11_reg_3009;
wire  signed [47:0] sext_ln23_51_fu_1511_p1;
wire  signed [47:0] sext_ln23_52_fu_1516_p1;
reg   [31:0] tmp_13_reg_3034;
wire  signed [47:0] sext_ln23_53_fu_1588_p1;
wire  signed [47:0] sext_ln23_54_fu_1593_p1;
reg   [31:0] tmp_15_reg_3059;
wire  signed [47:0] sext_ln23_55_fu_1665_p1;
wire  signed [47:0] sext_ln23_56_fu_1670_p1;
reg   [31:0] tmp_17_reg_3084;
wire  signed [47:0] sext_ln23_57_fu_1742_p1;
wire  signed [47:0] sext_ln23_58_fu_1747_p1;
reg   [31:0] tmp_19_reg_3109;
wire  signed [47:0] sext_ln23_59_fu_1819_p1;
wire  signed [47:0] sext_ln23_60_fu_1824_p1;
reg   [31:0] tmp_21_reg_3134;
wire  signed [47:0] sext_ln23_61_fu_1896_p1;
wire  signed [47:0] sext_ln23_62_fu_1901_p1;
reg   [31:0] tmp_23_reg_3159;
wire  signed [47:0] sext_ln23_63_fu_1973_p1;
wire  signed [47:0] sext_ln23_64_fu_1978_p1;
reg   [31:0] tmp_25_reg_3184;
wire  signed [47:0] sext_ln23_65_fu_2050_p1;
wire  signed [47:0] sext_ln23_66_fu_2055_p1;
reg   [31:0] tmp_27_reg_3209;
wire  signed [47:0] sext_ln23_67_fu_2127_p1;
wire  signed [47:0] sext_ln23_68_fu_2132_p1;
reg   [31:0] tmp_29_reg_3234;
wire  signed [47:0] sext_ln23_69_fu_2204_p1;
wire  signed [47:0] sext_ln23_70_fu_2209_p1;
reg   [31:0] tmp_31_reg_3259;
wire  signed [47:0] sext_ln23_71_fu_2281_p1;
wire  signed [47:0] sext_ln23_72_fu_2286_p1;
reg   [31:0] tmp_33_reg_3284;
wire  signed [47:0] sext_ln23_73_fu_2358_p1;
wire  signed [47:0] sext_ln23_74_fu_2363_p1;
reg   [31:0] tmp_35_reg_3299;
wire  signed [47:0] sext_ln23_75_fu_2415_p1;
wire  signed [47:0] sext_ln23_76_fu_2420_p1;
reg   [31:0] tmp_37_reg_3314;
wire  signed [47:0] sext_ln23_77_fu_2472_p1;
wire  signed [47:0] sext_ln23_78_fu_2477_p1;
reg   [31:0] tmp_39_reg_3329;
reg   [31:0] trunc_ln23_s_reg_3334;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln23_1_fu_1035_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln23_2_fu_1046_p1;
wire   [63:0] i_cast_fu_1004_p1;
wire   [63:0] zext_ln23_3_fu_1061_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln23_4_fu_1071_p1;
wire   [63:0] zext_ln23_5_fu_1081_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln23_6_fu_1091_p1;
wire   [63:0] zext_ln23_7_fu_1111_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln23_8_fu_1121_p1;
wire   [63:0] zext_ln23_9_fu_1141_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln23_10_fu_1151_p1;
wire   [63:0] zext_ln23_11_fu_1218_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln23_12_fu_1228_p1;
wire   [63:0] zext_ln23_13_fu_1295_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln23_14_fu_1305_p1;
wire   [63:0] zext_ln23_15_fu_1372_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln23_16_fu_1382_p1;
wire   [63:0] zext_ln23_17_fu_1449_p1;
wire    ap_block_pp0_stage8;
wire   [63:0] zext_ln23_18_fu_1459_p1;
wire   [63:0] zext_ln23_19_fu_1526_p1;
wire    ap_block_pp0_stage9;
wire   [63:0] zext_ln23_20_fu_1536_p1;
wire   [63:0] zext_ln23_21_fu_1603_p1;
wire    ap_block_pp0_stage10;
wire   [63:0] zext_ln23_22_fu_1613_p1;
wire   [63:0] zext_ln23_23_fu_1680_p1;
wire    ap_block_pp0_stage11;
wire   [63:0] zext_ln23_24_fu_1690_p1;
wire   [63:0] zext_ln23_25_fu_1757_p1;
wire    ap_block_pp0_stage12;
wire   [63:0] zext_ln23_26_fu_1767_p1;
wire   [63:0] zext_ln23_27_fu_1834_p1;
wire    ap_block_pp0_stage13;
wire   [63:0] zext_ln23_28_fu_1844_p1;
wire   [63:0] zext_ln23_29_fu_1911_p1;
wire    ap_block_pp0_stage14;
wire   [63:0] zext_ln23_30_fu_1921_p1;
wire   [63:0] zext_ln23_31_fu_1988_p1;
wire    ap_block_pp0_stage15;
wire   [63:0] zext_ln23_32_fu_1998_p1;
wire   [63:0] zext_ln23_33_fu_2065_p1;
wire    ap_block_pp0_stage16;
wire   [63:0] zext_ln23_34_fu_2075_p1;
wire   [63:0] zext_ln23_35_fu_2142_p1;
wire    ap_block_pp0_stage17;
wire   [63:0] zext_ln23_36_fu_2152_p1;
wire   [63:0] zext_ln23_37_fu_2219_p1;
wire    ap_block_pp0_stage18;
wire   [63:0] zext_ln23_38_fu_2229_p1;
wire   [63:0] zext_ln23_39_fu_2296_p1;
wire    ap_block_pp0_stage19;
wire   [63:0] zext_ln23_40_fu_2306_p1;
reg   [5:0] i_fu_214;
wire   [5:0] add_ln21_fu_998_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i_2;
reg  signed [31:0] grp_fu_800_p0;
reg  signed [31:0] grp_fu_800_p1;
reg  signed [31:0] grp_fu_804_p0;
reg  signed [31:0] grp_fu_804_p1;
wire   [8:0] tmp_1_fu_1017_p3;
wire   [10:0] tmp_fu_1009_p3;
wire   [10:0] zext_ln23_fu_1025_p1;
wire   [10:0] or_ln23_fu_1040_p2;
wire   [10:0] or_ln23_1_fu_1056_p2;
wire   [10:0] or_ln23_2_fu_1066_p2;
wire   [10:0] or_ln23_3_fu_1076_p2;
wire   [10:0] or_ln23_4_fu_1086_p2;
wire   [10:0] or_ln23_5_fu_1106_p2;
wire   [10:0] or_ln23_6_fu_1116_p2;
wire   [10:0] add_ln23_41_fu_1136_p2;
wire   [10:0] add_ln23_42_fu_1146_p2;
wire   [47:0] shl_ln_fu_1156_p3;
wire   [47:0] add_ln23_fu_1163_p2;
wire   [31:0] tmp_2_fu_1169_p4;
wire   [47:0] shl_ln23_1_fu_1179_p3;
wire   [47:0] add_ln23_1_fu_1187_p2;
wire   [10:0] add_ln23_43_fu_1213_p2;
wire   [10:0] add_ln23_44_fu_1223_p2;
wire   [47:0] shl_ln23_2_fu_1233_p3;
wire   [47:0] add_ln23_2_fu_1240_p2;
wire   [31:0] tmp_4_fu_1246_p4;
wire   [47:0] shl_ln23_3_fu_1256_p3;
wire   [47:0] add_ln23_3_fu_1264_p2;
wire   [10:0] add_ln23_45_fu_1290_p2;
wire   [10:0] add_ln23_46_fu_1300_p2;
wire   [47:0] shl_ln23_4_fu_1310_p3;
wire   [47:0] add_ln23_4_fu_1317_p2;
wire   [31:0] tmp_6_fu_1323_p4;
wire   [47:0] shl_ln23_5_fu_1333_p3;
wire   [47:0] add_ln23_5_fu_1341_p2;
wire   [10:0] add_ln23_47_fu_1367_p2;
wire   [10:0] add_ln23_48_fu_1377_p2;
wire   [47:0] shl_ln23_6_fu_1387_p3;
wire   [47:0] add_ln23_6_fu_1394_p2;
wire   [31:0] tmp_8_fu_1400_p4;
wire   [47:0] shl_ln23_7_fu_1410_p3;
wire   [47:0] add_ln23_7_fu_1418_p2;
wire   [10:0] add_ln23_49_fu_1444_p2;
wire   [10:0] add_ln23_50_fu_1454_p2;
wire   [47:0] shl_ln23_8_fu_1464_p3;
wire   [47:0] add_ln23_8_fu_1471_p2;
wire   [31:0] tmp_10_fu_1477_p4;
wire   [47:0] shl_ln23_9_fu_1487_p3;
wire   [47:0] add_ln23_9_fu_1495_p2;
wire   [10:0] add_ln23_51_fu_1521_p2;
wire   [10:0] add_ln23_52_fu_1531_p2;
wire   [47:0] shl_ln23_s_fu_1541_p3;
wire   [47:0] add_ln23_10_fu_1548_p2;
wire   [31:0] tmp_12_fu_1554_p4;
wire   [47:0] shl_ln23_10_fu_1564_p3;
wire   [47:0] add_ln23_11_fu_1572_p2;
wire   [10:0] add_ln23_53_fu_1598_p2;
wire   [10:0] add_ln23_54_fu_1608_p2;
wire   [47:0] shl_ln23_11_fu_1618_p3;
wire   [47:0] add_ln23_12_fu_1625_p2;
wire   [31:0] tmp_14_fu_1631_p4;
wire   [47:0] shl_ln23_12_fu_1641_p3;
wire   [47:0] add_ln23_13_fu_1649_p2;
wire   [10:0] add_ln23_55_fu_1675_p2;
wire   [10:0] add_ln23_56_fu_1685_p2;
wire   [47:0] shl_ln23_13_fu_1695_p3;
wire   [47:0] add_ln23_14_fu_1702_p2;
wire   [31:0] tmp_16_fu_1708_p4;
wire   [47:0] shl_ln23_14_fu_1718_p3;
wire   [47:0] add_ln23_15_fu_1726_p2;
wire   [10:0] add_ln23_57_fu_1752_p2;
wire   [10:0] add_ln23_58_fu_1762_p2;
wire   [47:0] shl_ln23_15_fu_1772_p3;
wire   [47:0] add_ln23_16_fu_1779_p2;
wire   [31:0] tmp_18_fu_1785_p4;
wire   [47:0] shl_ln23_16_fu_1795_p3;
wire   [47:0] add_ln23_17_fu_1803_p2;
wire   [10:0] add_ln23_59_fu_1829_p2;
wire   [10:0] add_ln23_60_fu_1839_p2;
wire   [47:0] shl_ln23_17_fu_1849_p3;
wire   [47:0] add_ln23_18_fu_1856_p2;
wire   [31:0] tmp_20_fu_1862_p4;
wire   [47:0] shl_ln23_18_fu_1872_p3;
wire   [47:0] add_ln23_19_fu_1880_p2;
wire   [10:0] add_ln23_61_fu_1906_p2;
wire   [10:0] add_ln23_62_fu_1916_p2;
wire   [47:0] shl_ln23_19_fu_1926_p3;
wire   [47:0] add_ln23_20_fu_1933_p2;
wire   [31:0] tmp_22_fu_1939_p4;
wire   [47:0] shl_ln23_20_fu_1949_p3;
wire   [47:0] add_ln23_21_fu_1957_p2;
wire   [10:0] add_ln23_63_fu_1983_p2;
wire   [10:0] add_ln23_64_fu_1993_p2;
wire   [47:0] shl_ln23_21_fu_2003_p3;
wire   [47:0] add_ln23_22_fu_2010_p2;
wire   [31:0] tmp_24_fu_2016_p4;
wire   [47:0] shl_ln23_22_fu_2026_p3;
wire   [47:0] add_ln23_23_fu_2034_p2;
wire   [10:0] add_ln23_65_fu_2060_p2;
wire   [10:0] add_ln23_66_fu_2070_p2;
wire   [47:0] shl_ln23_23_fu_2080_p3;
wire   [47:0] add_ln23_24_fu_2087_p2;
wire   [31:0] tmp_26_fu_2093_p4;
wire   [47:0] shl_ln23_24_fu_2103_p3;
wire   [47:0] add_ln23_25_fu_2111_p2;
wire   [10:0] add_ln23_67_fu_2137_p2;
wire   [10:0] add_ln23_68_fu_2147_p2;
wire   [47:0] shl_ln23_25_fu_2157_p3;
wire   [47:0] add_ln23_26_fu_2164_p2;
wire   [31:0] tmp_28_fu_2170_p4;
wire   [47:0] shl_ln23_26_fu_2180_p3;
wire   [47:0] add_ln23_27_fu_2188_p2;
wire   [10:0] add_ln23_69_fu_2214_p2;
wire   [10:0] add_ln23_70_fu_2224_p2;
wire   [47:0] shl_ln23_27_fu_2234_p3;
wire   [47:0] add_ln23_28_fu_2241_p2;
wire   [31:0] tmp_30_fu_2247_p4;
wire   [47:0] shl_ln23_28_fu_2257_p3;
wire   [47:0] add_ln23_29_fu_2265_p2;
wire   [10:0] add_ln23_71_fu_2291_p2;
wire   [10:0] add_ln23_72_fu_2301_p2;
wire   [47:0] shl_ln23_29_fu_2311_p3;
wire   [47:0] add_ln23_30_fu_2318_p2;
wire   [31:0] tmp_32_fu_2324_p4;
wire   [47:0] shl_ln23_30_fu_2334_p3;
wire   [47:0] add_ln23_31_fu_2342_p2;
wire   [47:0] shl_ln23_31_fu_2368_p3;
wire   [47:0] add_ln23_32_fu_2375_p2;
wire   [31:0] tmp_34_fu_2381_p4;
wire   [47:0] shl_ln23_32_fu_2391_p3;
wire   [47:0] add_ln23_33_fu_2399_p2;
wire   [47:0] shl_ln23_33_fu_2425_p3;
wire   [47:0] add_ln23_34_fu_2432_p2;
wire   [31:0] tmp_36_fu_2438_p4;
wire   [47:0] shl_ln23_34_fu_2448_p3;
wire   [47:0] add_ln23_35_fu_2456_p2;
wire   [47:0] shl_ln23_35_fu_2482_p3;
wire   [47:0] add_ln23_36_fu_2489_p2;
wire   [31:0] tmp_38_fu_2495_p4;
wire   [47:0] shl_ln23_36_fu_2505_p3;
wire   [47:0] add_ln23_37_fu_2513_p2;
wire   [47:0] shl_ln23_37_fu_2529_p3;
wire   [47:0] add_ln23_38_fu_2536_p2;
wire   [31:0] tmp_s_fu_2542_p4;
wire   [47:0] shl_ln23_38_fu_2552_p3;
wire   [47:0] add_ln23_39_fu_2560_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [19:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage9_subdone;
wire    ap_block_pp0_stage10_subdone;
wire    ap_block_pp0_stage11_subdone;
wire    ap_block_pp0_stage12_subdone;
wire    ap_block_pp0_stage13_subdone;
wire    ap_block_pp0_stage14_subdone;
wire    ap_block_pp0_stage15_subdone;
wire    ap_block_pp0_stage16_subdone;
wire    ap_block_pp0_stage17_subdone;
wire    ap_block_pp0_stage18_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 20'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

kernel_mvt_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage4),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage4)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage19_subdone) & (1'b1 == ap_CS_fsm_pp0_stage19))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln21_fu_992_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_214 <= add_ln21_fu_998_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_214 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln21_fu_992_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln23_40_reg_2787[10 : 3] <= add_ln23_40_fu_1029_p2[10 : 3];
        x1_addr_reg_2839 <= i_cast_fu_1004_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln21_reg_2783 <= icmp_ln21_fu_992_p2;
        sext_ln21_cast_reg_2583 <= sext_ln21_cast_fu_824_p1;
        sext_ln23_10_cast_reg_2728 <= sext_ln23_10_cast_fu_940_p1;
        sext_ln23_11_cast_reg_2723 <= sext_ln23_11_cast_fu_936_p1;
        sext_ln23_12_cast_reg_2718 <= sext_ln23_12_cast_fu_932_p1;
        sext_ln23_13_cast_reg_2713 <= sext_ln23_13_cast_fu_928_p1;
        sext_ln23_14_cast_reg_2708 <= sext_ln23_14_cast_fu_924_p1;
        sext_ln23_15_cast_reg_2703 <= sext_ln23_15_cast_fu_920_p1;
        sext_ln23_16_cast_reg_2698 <= sext_ln23_16_cast_fu_916_p1;
        sext_ln23_17_cast_reg_2693 <= sext_ln23_17_cast_fu_912_p1;
        sext_ln23_18_cast_reg_2688 <= sext_ln23_18_cast_fu_908_p1;
        sext_ln23_19_cast_reg_2683 <= sext_ln23_19_cast_fu_904_p1;
        sext_ln23_1_cast_reg_2773 <= sext_ln23_1_cast_fu_976_p1;
        sext_ln23_20_cast_reg_2678 <= sext_ln23_20_cast_fu_900_p1;
        sext_ln23_21_cast_reg_2673 <= sext_ln23_21_cast_fu_896_p1;
        sext_ln23_22_cast_reg_2668 <= sext_ln23_22_cast_fu_892_p1;
        sext_ln23_23_cast_reg_2663 <= sext_ln23_23_cast_fu_888_p1;
        sext_ln23_24_cast_reg_2658 <= sext_ln23_24_cast_fu_884_p1;
        sext_ln23_25_cast_reg_2653 <= sext_ln23_25_cast_fu_880_p1;
        sext_ln23_26_cast_reg_2648 <= sext_ln23_26_cast_fu_876_p1;
        sext_ln23_27_cast_reg_2643 <= sext_ln23_27_cast_fu_872_p1;
        sext_ln23_28_cast_reg_2638 <= sext_ln23_28_cast_fu_868_p1;
        sext_ln23_29_cast_reg_2633 <= sext_ln23_29_cast_fu_864_p1;
        sext_ln23_2_cast_reg_2768 <= sext_ln23_2_cast_fu_972_p1;
        sext_ln23_30_cast_reg_2628 <= sext_ln23_30_cast_fu_860_p1;
        sext_ln23_31_cast_reg_2623 <= sext_ln23_31_cast_fu_856_p1;
        sext_ln23_32_cast_reg_2618 <= sext_ln23_32_cast_fu_852_p1;
        sext_ln23_33_cast_reg_2613 <= sext_ln23_33_cast_fu_848_p1;
        sext_ln23_34_cast_reg_2608 <= sext_ln23_34_cast_fu_844_p1;
        sext_ln23_35_cast_reg_2603 <= sext_ln23_35_cast_fu_840_p1;
        sext_ln23_36_cast_reg_2598 <= sext_ln23_36_cast_fu_836_p1;
        sext_ln23_37_cast_reg_2593 <= sext_ln23_37_cast_fu_832_p1;
        sext_ln23_38_cast_reg_2588 <= sext_ln23_38_cast_fu_828_p1;
        sext_ln23_3_cast_reg_2763 <= sext_ln23_3_cast_fu_968_p1;
        sext_ln23_4_cast_reg_2758 <= sext_ln23_4_cast_fu_964_p1;
        sext_ln23_5_cast_reg_2753 <= sext_ln23_5_cast_fu_960_p1;
        sext_ln23_6_cast_reg_2748 <= sext_ln23_6_cast_fu_956_p1;
        sext_ln23_7_cast_reg_2743 <= sext_ln23_7_cast_fu_952_p1;
        sext_ln23_8_cast_reg_2738 <= sext_ln23_8_cast_fu_948_p1;
        sext_ln23_9_cast_reg_2733 <= sext_ln23_9_cast_fu_944_p1;
        sext_ln23_cast_reg_2778 <= sext_ln23_cast_fu_980_p1;
        tmp_35_reg_3299 <= {{add_ln23_33_fu_2399_p2[47:16]}};
        x1_addr_reg_2839_pp0_iter1_reg <= x1_addr_reg_2839;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage19_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage19)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage18_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage18)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage17_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage17)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage16_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage13_11001) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & 
    (1'b1 == ap_CS_fsm_pp0_stage6)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_808 <= A_q1;
        reg_812 <= A_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage19_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage19)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage18_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage18)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage17_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage17)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage16_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter0 
    == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) 
    | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_816 <= grp_fu_1748_p_dout0;
        reg_820 <= grp_fu_1752_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        tmp_11_reg_3009 <= {{add_ln23_9_fu_1495_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        tmp_13_reg_3034 <= {{add_ln23_11_fu_1572_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        tmp_15_reg_3059 <= {{add_ln23_13_fu_1649_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage11_11001) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        tmp_17_reg_3084 <= {{add_ln23_15_fu_1726_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage12_11001) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        tmp_19_reg_3109 <= {{add_ln23_17_fu_1803_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage13_11001) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        tmp_21_reg_3134 <= {{add_ln23_19_fu_1880_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage14_11001) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        tmp_23_reg_3159 <= {{add_ln23_21_fu_1957_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage15_11001) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        tmp_25_reg_3184 <= {{add_ln23_23_fu_2034_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage16_11001) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        tmp_27_reg_3209 <= {{add_ln23_25_fu_2111_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage17_11001) & (1'b1 == ap_CS_fsm_pp0_stage17))) begin
        tmp_29_reg_3234 <= {{add_ln23_27_fu_2188_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage18_11001) & (1'b1 == ap_CS_fsm_pp0_stage18))) begin
        tmp_31_reg_3259 <= {{add_ln23_29_fu_2265_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage19_11001) & (1'b1 == ap_CS_fsm_pp0_stage19))) begin
        tmp_33_reg_3284 <= {{add_ln23_31_fu_2342_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_37_reg_3314 <= {{add_ln23_35_fu_2456_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_39_reg_3329 <= {{add_ln23_37_fu_2513_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        tmp_3_reg_2909 <= {{add_ln23_1_fu_1187_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        tmp_5_reg_2934 <= {{add_ln23_3_fu_1264_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        tmp_7_reg_2959 <= {{add_ln23_5_fu_1341_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        tmp_9_reg_2984 <= {{add_ln23_7_fu_1418_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        trunc_ln23_s_reg_3334 <= {{add_ln23_39_fu_2560_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_2783 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        x1_load_reg_2854 <= x1_q0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage19) & (1'b1 == ap_CS_fsm_pp0_stage19))) begin
            A_address0 = zext_ln23_40_fu_2306_p1;
        end else if (((1'b0 == ap_block_pp0_stage18) & (1'b1 == ap_CS_fsm_pp0_stage18))) begin
            A_address0 = zext_ln23_38_fu_2229_p1;
        end else if (((1'b0 == ap_block_pp0_stage17) & (1'b1 == ap_CS_fsm_pp0_stage17))) begin
            A_address0 = zext_ln23_36_fu_2152_p1;
        end else if (((1'b0 == ap_block_pp0_stage16) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
            A_address0 = zext_ln23_34_fu_2075_p1;
        end else if (((1'b0 == ap_block_pp0_stage15) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
            A_address0 = zext_ln23_32_fu_1998_p1;
        end else if (((1'b0 == ap_block_pp0_stage14) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
            A_address0 = zext_ln23_30_fu_1921_p1;
        end else if (((1'b0 == ap_block_pp0_stage13) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
            A_address0 = zext_ln23_28_fu_1844_p1;
        end else if (((1'b0 == ap_block_pp0_stage12) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
            A_address0 = zext_ln23_26_fu_1767_p1;
        end else if (((1'b0 == ap_block_pp0_stage11) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
            A_address0 = zext_ln23_24_fu_1690_p1;
        end else if (((1'b0 == ap_block_pp0_stage10) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
            A_address0 = zext_ln23_22_fu_1613_p1;
        end else if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            A_address0 = zext_ln23_20_fu_1536_p1;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            A_address0 = zext_ln23_18_fu_1459_p1;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            A_address0 = zext_ln23_16_fu_1382_p1;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            A_address0 = zext_ln23_14_fu_1305_p1;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            A_address0 = zext_ln23_12_fu_1228_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            A_address0 = zext_ln23_10_fu_1151_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            A_address0 = zext_ln23_8_fu_1121_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            A_address0 = zext_ln23_6_fu_1091_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            A_address0 = zext_ln23_4_fu_1071_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            A_address0 = zext_ln23_2_fu_1046_p1;
        end else begin
            A_address0 = 'bx;
        end
    end else begin
        A_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage19) & (1'b1 == ap_CS_fsm_pp0_stage19))) begin
            A_address1 = zext_ln23_39_fu_2296_p1;
        end else if (((1'b0 == ap_block_pp0_stage18) & (1'b1 == ap_CS_fsm_pp0_stage18))) begin
            A_address1 = zext_ln23_37_fu_2219_p1;
        end else if (((1'b0 == ap_block_pp0_stage17) & (1'b1 == ap_CS_fsm_pp0_stage17))) begin
            A_address1 = zext_ln23_35_fu_2142_p1;
        end else if (((1'b0 == ap_block_pp0_stage16) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
            A_address1 = zext_ln23_33_fu_2065_p1;
        end else if (((1'b0 == ap_block_pp0_stage15) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
            A_address1 = zext_ln23_31_fu_1988_p1;
        end else if (((1'b0 == ap_block_pp0_stage14) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
            A_address1 = zext_ln23_29_fu_1911_p1;
        end else if (((1'b0 == ap_block_pp0_stage13) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
            A_address1 = zext_ln23_27_fu_1834_p1;
        end else if (((1'b0 == ap_block_pp0_stage12) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
            A_address1 = zext_ln23_25_fu_1757_p1;
        end else if (((1'b0 == ap_block_pp0_stage11) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
            A_address1 = zext_ln23_23_fu_1680_p1;
        end else if (((1'b0 == ap_block_pp0_stage10) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
            A_address1 = zext_ln23_21_fu_1603_p1;
        end else if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            A_address1 = zext_ln23_19_fu_1526_p1;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            A_address1 = zext_ln23_17_fu_1449_p1;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            A_address1 = zext_ln23_15_fu_1372_p1;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            A_address1 = zext_ln23_13_fu_1295_p1;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            A_address1 = zext_ln23_11_fu_1218_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            A_address1 = zext_ln23_9_fu_1141_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            A_address1 = zext_ln23_7_fu_1111_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            A_address1 = zext_ln23_5_fu_1081_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            A_address1 = zext_ln23_3_fu_1061_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            A_address1 = zext_ln23_1_fu_1035_p1;
        end else begin
            A_address1 = 'bx;
        end
    end else begin
        A_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage19_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage19)) | ((1'b0 == ap_block_pp0_stage18_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage18)) | ((1'b0 == ap_block_pp0_stage17_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage17)) | ((1'b0 == ap_block_pp0_stage16_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage11_11001) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 
    == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        A_ce0 = 1'b1;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage19_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage19)) | ((1'b0 == ap_block_pp0_stage18_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage18)) | ((1'b0 == ap_block_pp0_stage17_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage17)) | ((1'b0 == ap_block_pp0_stage16_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage11_11001) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 
    == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        A_ce1 = 1'b1;
    end else begin
        A_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_reg_2783 == 1'd1) & (1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage19_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage19))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_214;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_800_p0 = sext_ln23_38_cast_reg_2588;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_800_p0 = sext_ln23_36_cast_reg_2598;
    end else if (((1'b0 == ap_block_pp0_stage19) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage19))) begin
        grp_fu_800_p0 = sext_ln23_34_cast_reg_2608;
    end else if (((1'b0 == ap_block_pp0_stage18) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage18))) begin
        grp_fu_800_p0 = sext_ln23_32_cast_reg_2618;
    end else if (((1'b0 == ap_block_pp0_stage17) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage17))) begin
        grp_fu_800_p0 = sext_ln23_30_cast_reg_2628;
    end else if (((1'b0 == ap_block_pp0_stage16) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        grp_fu_800_p0 = sext_ln23_28_cast_reg_2638;
    end else if (((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        grp_fu_800_p0 = sext_ln23_26_cast_reg_2648;
    end else if (((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        grp_fu_800_p0 = sext_ln23_24_cast_reg_2658;
    end else if (((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        grp_fu_800_p0 = sext_ln23_22_cast_reg_2668;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        grp_fu_800_p0 = sext_ln23_20_cast_reg_2678;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        grp_fu_800_p0 = sext_ln23_18_cast_reg_2688;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        grp_fu_800_p0 = sext_ln23_16_cast_reg_2698;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        grp_fu_800_p0 = sext_ln23_14_cast_reg_2708;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        grp_fu_800_p0 = sext_ln23_12_cast_reg_2718;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_800_p0 = sext_ln23_10_cast_reg_2728;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_800_p0 = sext_ln23_8_cast_reg_2738;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_800_p0 = sext_ln23_6_cast_reg_2748;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_800_p0 = sext_ln23_4_cast_reg_2758;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_800_p0 = sext_ln23_2_cast_reg_2768;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_800_p0 = sext_ln23_cast_reg_2778;
    end else begin
        grp_fu_800_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_800_p1 = sext_ln23_77_fu_2472_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_800_p1 = sext_ln23_75_fu_2415_p1;
    end else if (((1'b0 == ap_block_pp0_stage19) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage19))) begin
        grp_fu_800_p1 = sext_ln23_73_fu_2358_p1;
    end else if (((1'b0 == ap_block_pp0_stage18) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage18))) begin
        grp_fu_800_p1 = sext_ln23_71_fu_2281_p1;
    end else if (((1'b0 == ap_block_pp0_stage17) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage17))) begin
        grp_fu_800_p1 = sext_ln23_69_fu_2204_p1;
    end else if (((1'b0 == ap_block_pp0_stage16) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        grp_fu_800_p1 = sext_ln23_67_fu_2127_p1;
    end else if (((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        grp_fu_800_p1 = sext_ln23_65_fu_2050_p1;
    end else if (((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        grp_fu_800_p1 = sext_ln23_63_fu_1973_p1;
    end else if (((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        grp_fu_800_p1 = sext_ln23_61_fu_1896_p1;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        grp_fu_800_p1 = sext_ln23_59_fu_1819_p1;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        grp_fu_800_p1 = sext_ln23_57_fu_1742_p1;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        grp_fu_800_p1 = sext_ln23_55_fu_1665_p1;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        grp_fu_800_p1 = sext_ln23_53_fu_1588_p1;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        grp_fu_800_p1 = sext_ln23_51_fu_1511_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_800_p1 = sext_ln23_49_fu_1434_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_800_p1 = sext_ln23_47_fu_1357_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_800_p1 = sext_ln23_45_fu_1280_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_800_p1 = sext_ln23_43_fu_1203_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_800_p1 = sext_ln23_41_fu_1126_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_800_p1 = sext_ln23_39_fu_1096_p1;
    end else begin
        grp_fu_800_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_804_p0 = sext_ln21_cast_reg_2583;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_804_p0 = sext_ln23_37_cast_reg_2593;
    end else if (((1'b0 == ap_block_pp0_stage19) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage19))) begin
        grp_fu_804_p0 = sext_ln23_35_cast_reg_2603;
    end else if (((1'b0 == ap_block_pp0_stage18) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage18))) begin
        grp_fu_804_p0 = sext_ln23_33_cast_reg_2613;
    end else if (((1'b0 == ap_block_pp0_stage17) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage17))) begin
        grp_fu_804_p0 = sext_ln23_31_cast_reg_2623;
    end else if (((1'b0 == ap_block_pp0_stage16) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        grp_fu_804_p0 = sext_ln23_29_cast_reg_2633;
    end else if (((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        grp_fu_804_p0 = sext_ln23_27_cast_reg_2643;
    end else if (((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        grp_fu_804_p0 = sext_ln23_25_cast_reg_2653;
    end else if (((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        grp_fu_804_p0 = sext_ln23_23_cast_reg_2663;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        grp_fu_804_p0 = sext_ln23_21_cast_reg_2673;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        grp_fu_804_p0 = sext_ln23_19_cast_reg_2683;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        grp_fu_804_p0 = sext_ln23_17_cast_reg_2693;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        grp_fu_804_p0 = sext_ln23_15_cast_reg_2703;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        grp_fu_804_p0 = sext_ln23_13_cast_reg_2713;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_804_p0 = sext_ln23_11_cast_reg_2723;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_804_p0 = sext_ln23_9_cast_reg_2733;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_804_p0 = sext_ln23_7_cast_reg_2743;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_804_p0 = sext_ln23_5_cast_reg_2753;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_804_p0 = sext_ln23_3_cast_reg_2763;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_804_p0 = sext_ln23_1_cast_reg_2773;
    end else begin
        grp_fu_804_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_804_p1 = sext_ln23_78_fu_2477_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_804_p1 = sext_ln23_76_fu_2420_p1;
    end else if (((1'b0 == ap_block_pp0_stage19) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage19))) begin
        grp_fu_804_p1 = sext_ln23_74_fu_2363_p1;
    end else if (((1'b0 == ap_block_pp0_stage18) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage18))) begin
        grp_fu_804_p1 = sext_ln23_72_fu_2286_p1;
    end else if (((1'b0 == ap_block_pp0_stage17) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage17))) begin
        grp_fu_804_p1 = sext_ln23_70_fu_2209_p1;
    end else if (((1'b0 == ap_block_pp0_stage16) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        grp_fu_804_p1 = sext_ln23_68_fu_2132_p1;
    end else if (((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        grp_fu_804_p1 = sext_ln23_66_fu_2055_p1;
    end else if (((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        grp_fu_804_p1 = sext_ln23_64_fu_1978_p1;
    end else if (((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        grp_fu_804_p1 = sext_ln23_62_fu_1901_p1;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        grp_fu_804_p1 = sext_ln23_60_fu_1824_p1;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        grp_fu_804_p1 = sext_ln23_58_fu_1747_p1;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        grp_fu_804_p1 = sext_ln23_56_fu_1670_p1;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        grp_fu_804_p1 = sext_ln23_54_fu_1593_p1;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        grp_fu_804_p1 = sext_ln23_52_fu_1516_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_804_p1 = sext_ln23_50_fu_1439_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_804_p1 = sext_ln23_48_fu_1362_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_804_p1 = sext_ln23_46_fu_1285_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_804_p1 = sext_ln23_44_fu_1208_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_804_p1 = sext_ln23_42_fu_1131_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_804_p1 = sext_ln23_40_fu_1101_p1;
    end else begin
        grp_fu_804_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        x1_address0 = x1_addr_reg_2839_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x1_address0 = i_cast_fu_1004_p1;
    end else begin
        x1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        x1_ce0 = 1'b1;
    end else begin
        x1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        x1_we0 = 1'b1;
    end else begin
        x1_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage4)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        ap_ST_fsm_pp0_stage13 : begin
            if ((1'b0 == ap_block_pp0_stage13_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end
        end
        ap_ST_fsm_pp0_stage14 : begin
            if ((1'b0 == ap_block_pp0_stage14_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end
        end
        ap_ST_fsm_pp0_stage15 : begin
            if ((1'b0 == ap_block_pp0_stage15_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end
        end
        ap_ST_fsm_pp0_stage16 : begin
            if ((1'b0 == ap_block_pp0_stage16_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage16;
            end
        end
        ap_ST_fsm_pp0_stage17 : begin
            if ((1'b0 == ap_block_pp0_stage17_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage17;
            end
        end
        ap_ST_fsm_pp0_stage18 : begin
            if ((1'b0 == ap_block_pp0_stage18_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage18;
            end
        end
        ap_ST_fsm_pp0_stage19 : begin
            if ((1'b0 == ap_block_pp0_stage19_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage19;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln21_fu_998_p2 = (ap_sig_allocacmp_i_2 + 6'd1);

assign add_ln23_10_fu_1548_p2 = (shl_ln23_s_fu_1541_p3 + reg_816);

assign add_ln23_11_fu_1572_p2 = (shl_ln23_10_fu_1564_p3 + reg_820);

assign add_ln23_12_fu_1625_p2 = (shl_ln23_11_fu_1618_p3 + reg_816);

assign add_ln23_13_fu_1649_p2 = (shl_ln23_12_fu_1641_p3 + reg_820);

assign add_ln23_14_fu_1702_p2 = (shl_ln23_13_fu_1695_p3 + reg_816);

assign add_ln23_15_fu_1726_p2 = (shl_ln23_14_fu_1718_p3 + reg_820);

assign add_ln23_16_fu_1779_p2 = (shl_ln23_15_fu_1772_p3 + reg_816);

assign add_ln23_17_fu_1803_p2 = (shl_ln23_16_fu_1795_p3 + reg_820);

assign add_ln23_18_fu_1856_p2 = (shl_ln23_17_fu_1849_p3 + reg_816);

assign add_ln23_19_fu_1880_p2 = (shl_ln23_18_fu_1872_p3 + reg_820);

assign add_ln23_1_fu_1187_p2 = (shl_ln23_1_fu_1179_p3 + reg_820);

assign add_ln23_20_fu_1933_p2 = (shl_ln23_19_fu_1926_p3 + reg_816);

assign add_ln23_21_fu_1957_p2 = (shl_ln23_20_fu_1949_p3 + reg_820);

assign add_ln23_22_fu_2010_p2 = (shl_ln23_21_fu_2003_p3 + reg_816);

assign add_ln23_23_fu_2034_p2 = (shl_ln23_22_fu_2026_p3 + reg_820);

assign add_ln23_24_fu_2087_p2 = (shl_ln23_23_fu_2080_p3 + reg_816);

assign add_ln23_25_fu_2111_p2 = (shl_ln23_24_fu_2103_p3 + reg_820);

assign add_ln23_26_fu_2164_p2 = (shl_ln23_25_fu_2157_p3 + reg_816);

assign add_ln23_27_fu_2188_p2 = (shl_ln23_26_fu_2180_p3 + reg_820);

assign add_ln23_28_fu_2241_p2 = (shl_ln23_27_fu_2234_p3 + reg_816);

assign add_ln23_29_fu_2265_p2 = (shl_ln23_28_fu_2257_p3 + reg_820);

assign add_ln23_2_fu_1240_p2 = (shl_ln23_2_fu_1233_p3 + reg_816);

assign add_ln23_30_fu_2318_p2 = (shl_ln23_29_fu_2311_p3 + reg_816);

assign add_ln23_31_fu_2342_p2 = (shl_ln23_30_fu_2334_p3 + reg_820);

assign add_ln23_32_fu_2375_p2 = (shl_ln23_31_fu_2368_p3 + reg_816);

assign add_ln23_33_fu_2399_p2 = (shl_ln23_32_fu_2391_p3 + reg_820);

assign add_ln23_34_fu_2432_p2 = (shl_ln23_33_fu_2425_p3 + reg_816);

assign add_ln23_35_fu_2456_p2 = (shl_ln23_34_fu_2448_p3 + reg_820);

assign add_ln23_36_fu_2489_p2 = (shl_ln23_35_fu_2482_p3 + reg_816);

assign add_ln23_37_fu_2513_p2 = (shl_ln23_36_fu_2505_p3 + reg_820);

assign add_ln23_38_fu_2536_p2 = (shl_ln23_37_fu_2529_p3 + reg_816);

assign add_ln23_39_fu_2560_p2 = (shl_ln23_38_fu_2552_p3 + reg_820);

assign add_ln23_3_fu_1264_p2 = (shl_ln23_3_fu_1256_p3 + reg_820);

assign add_ln23_40_fu_1029_p2 = (tmp_fu_1009_p3 + zext_ln23_fu_1025_p1);

assign add_ln23_41_fu_1136_p2 = (add_ln23_40_reg_2787 + 11'd8);

assign add_ln23_42_fu_1146_p2 = (add_ln23_40_reg_2787 + 11'd9);

assign add_ln23_43_fu_1213_p2 = (add_ln23_40_reg_2787 + 11'd10);

assign add_ln23_44_fu_1223_p2 = (add_ln23_40_reg_2787 + 11'd11);

assign add_ln23_45_fu_1290_p2 = (add_ln23_40_reg_2787 + 11'd12);

assign add_ln23_46_fu_1300_p2 = (add_ln23_40_reg_2787 + 11'd13);

assign add_ln23_47_fu_1367_p2 = (add_ln23_40_reg_2787 + 11'd14);

assign add_ln23_48_fu_1377_p2 = (add_ln23_40_reg_2787 + 11'd15);

assign add_ln23_49_fu_1444_p2 = (add_ln23_40_reg_2787 + 11'd16);

assign add_ln23_4_fu_1317_p2 = (shl_ln23_4_fu_1310_p3 + reg_816);

assign add_ln23_50_fu_1454_p2 = (add_ln23_40_reg_2787 + 11'd17);

assign add_ln23_51_fu_1521_p2 = (add_ln23_40_reg_2787 + 11'd18);

assign add_ln23_52_fu_1531_p2 = (add_ln23_40_reg_2787 + 11'd19);

assign add_ln23_53_fu_1598_p2 = (add_ln23_40_reg_2787 + 11'd20);

assign add_ln23_54_fu_1608_p2 = (add_ln23_40_reg_2787 + 11'd21);

assign add_ln23_55_fu_1675_p2 = (add_ln23_40_reg_2787 + 11'd22);

assign add_ln23_56_fu_1685_p2 = (add_ln23_40_reg_2787 + 11'd23);

assign add_ln23_57_fu_1752_p2 = (add_ln23_40_reg_2787 + 11'd24);

assign add_ln23_58_fu_1762_p2 = (add_ln23_40_reg_2787 + 11'd25);

assign add_ln23_59_fu_1829_p2 = (add_ln23_40_reg_2787 + 11'd26);

assign add_ln23_5_fu_1341_p2 = (shl_ln23_5_fu_1333_p3 + reg_820);

assign add_ln23_60_fu_1839_p2 = (add_ln23_40_reg_2787 + 11'd27);

assign add_ln23_61_fu_1906_p2 = (add_ln23_40_reg_2787 + 11'd28);

assign add_ln23_62_fu_1916_p2 = (add_ln23_40_reg_2787 + 11'd29);

assign add_ln23_63_fu_1983_p2 = (add_ln23_40_reg_2787 + 11'd30);

assign add_ln23_64_fu_1993_p2 = (add_ln23_40_reg_2787 + 11'd31);

assign add_ln23_65_fu_2060_p2 = (add_ln23_40_reg_2787 + 11'd32);

assign add_ln23_66_fu_2070_p2 = (add_ln23_40_reg_2787 + 11'd33);

assign add_ln23_67_fu_2137_p2 = (add_ln23_40_reg_2787 + 11'd34);

assign add_ln23_68_fu_2147_p2 = (add_ln23_40_reg_2787 + 11'd35);

assign add_ln23_69_fu_2214_p2 = (add_ln23_40_reg_2787 + 11'd36);

assign add_ln23_6_fu_1394_p2 = (shl_ln23_6_fu_1387_p3 + reg_816);

assign add_ln23_70_fu_2224_p2 = (add_ln23_40_reg_2787 + 11'd37);

assign add_ln23_71_fu_2291_p2 = (add_ln23_40_reg_2787 + 11'd38);

assign add_ln23_72_fu_2301_p2 = (add_ln23_40_reg_2787 + 11'd39);

assign add_ln23_7_fu_1418_p2 = (shl_ln23_7_fu_1410_p3 + reg_820);

assign add_ln23_8_fu_1471_p2 = (shl_ln23_8_fu_1464_p3 + reg_816);

assign add_ln23_9_fu_1495_p2 = (shl_ln23_9_fu_1487_p3 + reg_820);

assign add_ln23_fu_1163_p2 = (shl_ln_fu_1156_p3 + reg_816);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage13 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp0_stage14 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp0_stage15 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp0_stage16 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_pp0_stage17 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_pp0_stage18 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_pp0_stage19 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage17 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage17_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage17_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage18 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage18_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage18_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage19 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage19_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage19_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage9_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage10_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage11_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage12_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage13_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage14_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage15_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage16_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage17_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage18_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage19_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage8_iter0 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage4;

assign grp_fu_1748_p_ce = 1'b1;

assign grp_fu_1748_p_din0 = grp_fu_800_p0;

assign grp_fu_1748_p_din1 = grp_fu_800_p1;

assign grp_fu_1752_p_ce = 1'b1;

assign grp_fu_1752_p_din0 = grp_fu_804_p0;

assign grp_fu_1752_p_din1 = grp_fu_804_p1;

assign i_cast_fu_1004_p1 = ap_sig_allocacmp_i_2;

assign icmp_ln21_fu_992_p2 = ((ap_sig_allocacmp_i_2 == 6'd40) ? 1'b1 : 1'b0);

assign or_ln23_1_fu_1056_p2 = (11'd2 | add_ln23_40_reg_2787);

assign or_ln23_2_fu_1066_p2 = (11'd3 | add_ln23_40_reg_2787);

assign or_ln23_3_fu_1076_p2 = (11'd4 | add_ln23_40_reg_2787);

assign or_ln23_4_fu_1086_p2 = (11'd5 | add_ln23_40_reg_2787);

assign or_ln23_5_fu_1106_p2 = (11'd6 | add_ln23_40_reg_2787);

assign or_ln23_6_fu_1116_p2 = (11'd7 | add_ln23_40_reg_2787);

assign or_ln23_fu_1040_p2 = (11'd1 | add_ln23_40_fu_1029_p2);

assign sext_ln21_cast_fu_824_p1 = $signed(sext_ln21);

assign sext_ln23_10_cast_fu_940_p1 = $signed(sext_ln23_10);

assign sext_ln23_11_cast_fu_936_p1 = $signed(sext_ln23_11);

assign sext_ln23_12_cast_fu_932_p1 = $signed(sext_ln23_12);

assign sext_ln23_13_cast_fu_928_p1 = $signed(sext_ln23_13);

assign sext_ln23_14_cast_fu_924_p1 = $signed(sext_ln23_14);

assign sext_ln23_15_cast_fu_920_p1 = $signed(sext_ln23_15);

assign sext_ln23_16_cast_fu_916_p1 = $signed(sext_ln23_16);

assign sext_ln23_17_cast_fu_912_p1 = $signed(sext_ln23_17);

assign sext_ln23_18_cast_fu_908_p1 = $signed(sext_ln23_18);

assign sext_ln23_19_cast_fu_904_p1 = $signed(sext_ln23_19);

assign sext_ln23_1_cast_fu_976_p1 = $signed(sext_ln23_1);

assign sext_ln23_20_cast_fu_900_p1 = $signed(sext_ln23_20);

assign sext_ln23_21_cast_fu_896_p1 = $signed(sext_ln23_21);

assign sext_ln23_22_cast_fu_892_p1 = $signed(sext_ln23_22);

assign sext_ln23_23_cast_fu_888_p1 = $signed(sext_ln23_23);

assign sext_ln23_24_cast_fu_884_p1 = $signed(sext_ln23_24);

assign sext_ln23_25_cast_fu_880_p1 = $signed(sext_ln23_25);

assign sext_ln23_26_cast_fu_876_p1 = $signed(sext_ln23_26);

assign sext_ln23_27_cast_fu_872_p1 = $signed(sext_ln23_27);

assign sext_ln23_28_cast_fu_868_p1 = $signed(sext_ln23_28);

assign sext_ln23_29_cast_fu_864_p1 = $signed(sext_ln23_29);

assign sext_ln23_2_cast_fu_972_p1 = $signed(sext_ln23_2);

assign sext_ln23_30_cast_fu_860_p1 = $signed(sext_ln23_30);

assign sext_ln23_31_cast_fu_856_p1 = $signed(sext_ln23_31);

assign sext_ln23_32_cast_fu_852_p1 = $signed(sext_ln23_32);

assign sext_ln23_33_cast_fu_848_p1 = $signed(sext_ln23_33);

assign sext_ln23_34_cast_fu_844_p1 = $signed(sext_ln23_34);

assign sext_ln23_35_cast_fu_840_p1 = $signed(sext_ln23_35);

assign sext_ln23_36_cast_fu_836_p1 = $signed(sext_ln23_36);

assign sext_ln23_37_cast_fu_832_p1 = $signed(sext_ln23_37);

assign sext_ln23_38_cast_fu_828_p1 = $signed(sext_ln23_38);

assign sext_ln23_39_fu_1096_p1 = $signed(reg_808);

assign sext_ln23_3_cast_fu_968_p1 = $signed(sext_ln23_3);

assign sext_ln23_40_fu_1101_p1 = $signed(reg_812);

assign sext_ln23_41_fu_1126_p1 = $signed(reg_808);

assign sext_ln23_42_fu_1131_p1 = $signed(reg_812);

assign sext_ln23_43_fu_1203_p1 = $signed(reg_808);

assign sext_ln23_44_fu_1208_p1 = $signed(reg_812);

assign sext_ln23_45_fu_1280_p1 = $signed(reg_808);

assign sext_ln23_46_fu_1285_p1 = $signed(reg_812);

assign sext_ln23_47_fu_1357_p1 = $signed(reg_808);

assign sext_ln23_48_fu_1362_p1 = $signed(reg_812);

assign sext_ln23_49_fu_1434_p1 = $signed(reg_808);

assign sext_ln23_4_cast_fu_964_p1 = $signed(sext_ln23_4);

assign sext_ln23_50_fu_1439_p1 = $signed(reg_812);

assign sext_ln23_51_fu_1511_p1 = $signed(reg_808);

assign sext_ln23_52_fu_1516_p1 = $signed(reg_812);

assign sext_ln23_53_fu_1588_p1 = $signed(reg_808);

assign sext_ln23_54_fu_1593_p1 = $signed(reg_812);

assign sext_ln23_55_fu_1665_p1 = $signed(reg_808);

assign sext_ln23_56_fu_1670_p1 = $signed(reg_812);

assign sext_ln23_57_fu_1742_p1 = $signed(reg_808);

assign sext_ln23_58_fu_1747_p1 = $signed(reg_812);

assign sext_ln23_59_fu_1819_p1 = $signed(reg_808);

assign sext_ln23_5_cast_fu_960_p1 = $signed(sext_ln23_5);

assign sext_ln23_60_fu_1824_p1 = $signed(reg_812);

assign sext_ln23_61_fu_1896_p1 = $signed(reg_808);

assign sext_ln23_62_fu_1901_p1 = $signed(reg_812);

assign sext_ln23_63_fu_1973_p1 = $signed(reg_808);

assign sext_ln23_64_fu_1978_p1 = $signed(reg_812);

assign sext_ln23_65_fu_2050_p1 = $signed(reg_808);

assign sext_ln23_66_fu_2055_p1 = $signed(reg_812);

assign sext_ln23_67_fu_2127_p1 = $signed(reg_808);

assign sext_ln23_68_fu_2132_p1 = $signed(reg_812);

assign sext_ln23_69_fu_2204_p1 = $signed(reg_808);

assign sext_ln23_6_cast_fu_956_p1 = $signed(sext_ln23_6);

assign sext_ln23_70_fu_2209_p1 = $signed(reg_812);

assign sext_ln23_71_fu_2281_p1 = $signed(reg_808);

assign sext_ln23_72_fu_2286_p1 = $signed(reg_812);

assign sext_ln23_73_fu_2358_p1 = $signed(reg_808);

assign sext_ln23_74_fu_2363_p1 = $signed(reg_812);

assign sext_ln23_75_fu_2415_p1 = $signed(reg_808);

assign sext_ln23_76_fu_2420_p1 = $signed(reg_812);

assign sext_ln23_77_fu_2472_p1 = $signed(reg_808);

assign sext_ln23_78_fu_2477_p1 = $signed(reg_812);

assign sext_ln23_7_cast_fu_952_p1 = $signed(sext_ln23_7);

assign sext_ln23_8_cast_fu_948_p1 = $signed(sext_ln23_8);

assign sext_ln23_9_cast_fu_944_p1 = $signed(sext_ln23_9);

assign sext_ln23_cast_fu_980_p1 = $signed(sext_ln23);

assign shl_ln23_10_fu_1564_p3 = {{tmp_12_fu_1554_p4}, {16'd0}};

assign shl_ln23_11_fu_1618_p3 = {{tmp_13_reg_3034}, {16'd0}};

assign shl_ln23_12_fu_1641_p3 = {{tmp_14_fu_1631_p4}, {16'd0}};

assign shl_ln23_13_fu_1695_p3 = {{tmp_15_reg_3059}, {16'd0}};

assign shl_ln23_14_fu_1718_p3 = {{tmp_16_fu_1708_p4}, {16'd0}};

assign shl_ln23_15_fu_1772_p3 = {{tmp_17_reg_3084}, {16'd0}};

assign shl_ln23_16_fu_1795_p3 = {{tmp_18_fu_1785_p4}, {16'd0}};

assign shl_ln23_17_fu_1849_p3 = {{tmp_19_reg_3109}, {16'd0}};

assign shl_ln23_18_fu_1872_p3 = {{tmp_20_fu_1862_p4}, {16'd0}};

assign shl_ln23_19_fu_1926_p3 = {{tmp_21_reg_3134}, {16'd0}};

assign shl_ln23_1_fu_1179_p3 = {{tmp_2_fu_1169_p4}, {16'd0}};

assign shl_ln23_20_fu_1949_p3 = {{tmp_22_fu_1939_p4}, {16'd0}};

assign shl_ln23_21_fu_2003_p3 = {{tmp_23_reg_3159}, {16'd0}};

assign shl_ln23_22_fu_2026_p3 = {{tmp_24_fu_2016_p4}, {16'd0}};

assign shl_ln23_23_fu_2080_p3 = {{tmp_25_reg_3184}, {16'd0}};

assign shl_ln23_24_fu_2103_p3 = {{tmp_26_fu_2093_p4}, {16'd0}};

assign shl_ln23_25_fu_2157_p3 = {{tmp_27_reg_3209}, {16'd0}};

assign shl_ln23_26_fu_2180_p3 = {{tmp_28_fu_2170_p4}, {16'd0}};

assign shl_ln23_27_fu_2234_p3 = {{tmp_29_reg_3234}, {16'd0}};

assign shl_ln23_28_fu_2257_p3 = {{tmp_30_fu_2247_p4}, {16'd0}};

assign shl_ln23_29_fu_2311_p3 = {{tmp_31_reg_3259}, {16'd0}};

assign shl_ln23_2_fu_1233_p3 = {{tmp_3_reg_2909}, {16'd0}};

assign shl_ln23_30_fu_2334_p3 = {{tmp_32_fu_2324_p4}, {16'd0}};

assign shl_ln23_31_fu_2368_p3 = {{tmp_33_reg_3284}, {16'd0}};

assign shl_ln23_32_fu_2391_p3 = {{tmp_34_fu_2381_p4}, {16'd0}};

assign shl_ln23_33_fu_2425_p3 = {{tmp_35_reg_3299}, {16'd0}};

assign shl_ln23_34_fu_2448_p3 = {{tmp_36_fu_2438_p4}, {16'd0}};

assign shl_ln23_35_fu_2482_p3 = {{tmp_37_reg_3314}, {16'd0}};

assign shl_ln23_36_fu_2505_p3 = {{tmp_38_fu_2495_p4}, {16'd0}};

assign shl_ln23_37_fu_2529_p3 = {{tmp_39_reg_3329}, {16'd0}};

assign shl_ln23_38_fu_2552_p3 = {{tmp_s_fu_2542_p4}, {16'd0}};

assign shl_ln23_3_fu_1256_p3 = {{tmp_4_fu_1246_p4}, {16'd0}};

assign shl_ln23_4_fu_1310_p3 = {{tmp_5_reg_2934}, {16'd0}};

assign shl_ln23_5_fu_1333_p3 = {{tmp_6_fu_1323_p4}, {16'd0}};

assign shl_ln23_6_fu_1387_p3 = {{tmp_7_reg_2959}, {16'd0}};

assign shl_ln23_7_fu_1410_p3 = {{tmp_8_fu_1400_p4}, {16'd0}};

assign shl_ln23_8_fu_1464_p3 = {{tmp_9_reg_2984}, {16'd0}};

assign shl_ln23_9_fu_1487_p3 = {{tmp_10_fu_1477_p4}, {16'd0}};

assign shl_ln23_s_fu_1541_p3 = {{tmp_11_reg_3009}, {16'd0}};

assign shl_ln_fu_1156_p3 = {{x1_load_reg_2854}, {16'd0}};

assign tmp_10_fu_1477_p4 = {{add_ln23_8_fu_1471_p2[47:16]}};

assign tmp_12_fu_1554_p4 = {{add_ln23_10_fu_1548_p2[47:16]}};

assign tmp_14_fu_1631_p4 = {{add_ln23_12_fu_1625_p2[47:16]}};

assign tmp_16_fu_1708_p4 = {{add_ln23_14_fu_1702_p2[47:16]}};

assign tmp_18_fu_1785_p4 = {{add_ln23_16_fu_1779_p2[47:16]}};

assign tmp_1_fu_1017_p3 = {{ap_sig_allocacmp_i_2}, {3'd0}};

assign tmp_20_fu_1862_p4 = {{add_ln23_18_fu_1856_p2[47:16]}};

assign tmp_22_fu_1939_p4 = {{add_ln23_20_fu_1933_p2[47:16]}};

assign tmp_24_fu_2016_p4 = {{add_ln23_22_fu_2010_p2[47:16]}};

assign tmp_26_fu_2093_p4 = {{add_ln23_24_fu_2087_p2[47:16]}};

assign tmp_28_fu_2170_p4 = {{add_ln23_26_fu_2164_p2[47:16]}};

assign tmp_2_fu_1169_p4 = {{add_ln23_fu_1163_p2[47:16]}};

assign tmp_30_fu_2247_p4 = {{add_ln23_28_fu_2241_p2[47:16]}};

assign tmp_32_fu_2324_p4 = {{add_ln23_30_fu_2318_p2[47:16]}};

assign tmp_34_fu_2381_p4 = {{add_ln23_32_fu_2375_p2[47:16]}};

assign tmp_36_fu_2438_p4 = {{add_ln23_34_fu_2432_p2[47:16]}};

assign tmp_38_fu_2495_p4 = {{add_ln23_36_fu_2489_p2[47:16]}};

assign tmp_4_fu_1246_p4 = {{add_ln23_2_fu_1240_p2[47:16]}};

assign tmp_6_fu_1323_p4 = {{add_ln23_4_fu_1317_p2[47:16]}};

assign tmp_8_fu_1400_p4 = {{add_ln23_6_fu_1394_p2[47:16]}};

assign tmp_fu_1009_p3 = {{ap_sig_allocacmp_i_2}, {5'd0}};

assign tmp_s_fu_2542_p4 = {{add_ln23_38_fu_2536_p2[47:16]}};

assign x1_d0 = trunc_ln23_s_reg_3334;

assign zext_ln23_10_fu_1151_p1 = add_ln23_42_fu_1146_p2;

assign zext_ln23_11_fu_1218_p1 = add_ln23_43_fu_1213_p2;

assign zext_ln23_12_fu_1228_p1 = add_ln23_44_fu_1223_p2;

assign zext_ln23_13_fu_1295_p1 = add_ln23_45_fu_1290_p2;

assign zext_ln23_14_fu_1305_p1 = add_ln23_46_fu_1300_p2;

assign zext_ln23_15_fu_1372_p1 = add_ln23_47_fu_1367_p2;

assign zext_ln23_16_fu_1382_p1 = add_ln23_48_fu_1377_p2;

assign zext_ln23_17_fu_1449_p1 = add_ln23_49_fu_1444_p2;

assign zext_ln23_18_fu_1459_p1 = add_ln23_50_fu_1454_p2;

assign zext_ln23_19_fu_1526_p1 = add_ln23_51_fu_1521_p2;

assign zext_ln23_1_fu_1035_p1 = add_ln23_40_fu_1029_p2;

assign zext_ln23_20_fu_1536_p1 = add_ln23_52_fu_1531_p2;

assign zext_ln23_21_fu_1603_p1 = add_ln23_53_fu_1598_p2;

assign zext_ln23_22_fu_1613_p1 = add_ln23_54_fu_1608_p2;

assign zext_ln23_23_fu_1680_p1 = add_ln23_55_fu_1675_p2;

assign zext_ln23_24_fu_1690_p1 = add_ln23_56_fu_1685_p2;

assign zext_ln23_25_fu_1757_p1 = add_ln23_57_fu_1752_p2;

assign zext_ln23_26_fu_1767_p1 = add_ln23_58_fu_1762_p2;

assign zext_ln23_27_fu_1834_p1 = add_ln23_59_fu_1829_p2;

assign zext_ln23_28_fu_1844_p1 = add_ln23_60_fu_1839_p2;

assign zext_ln23_29_fu_1911_p1 = add_ln23_61_fu_1906_p2;

assign zext_ln23_2_fu_1046_p1 = or_ln23_fu_1040_p2;

assign zext_ln23_30_fu_1921_p1 = add_ln23_62_fu_1916_p2;

assign zext_ln23_31_fu_1988_p1 = add_ln23_63_fu_1983_p2;

assign zext_ln23_32_fu_1998_p1 = add_ln23_64_fu_1993_p2;

assign zext_ln23_33_fu_2065_p1 = add_ln23_65_fu_2060_p2;

assign zext_ln23_34_fu_2075_p1 = add_ln23_66_fu_2070_p2;

assign zext_ln23_35_fu_2142_p1 = add_ln23_67_fu_2137_p2;

assign zext_ln23_36_fu_2152_p1 = add_ln23_68_fu_2147_p2;

assign zext_ln23_37_fu_2219_p1 = add_ln23_69_fu_2214_p2;

assign zext_ln23_38_fu_2229_p1 = add_ln23_70_fu_2224_p2;

assign zext_ln23_39_fu_2296_p1 = add_ln23_71_fu_2291_p2;

assign zext_ln23_3_fu_1061_p1 = or_ln23_1_fu_1056_p2;

assign zext_ln23_40_fu_2306_p1 = add_ln23_72_fu_2301_p2;

assign zext_ln23_4_fu_1071_p1 = or_ln23_2_fu_1066_p2;

assign zext_ln23_5_fu_1081_p1 = or_ln23_3_fu_1076_p2;

assign zext_ln23_6_fu_1091_p1 = or_ln23_4_fu_1086_p2;

assign zext_ln23_7_fu_1111_p1 = or_ln23_5_fu_1106_p2;

assign zext_ln23_8_fu_1121_p1 = or_ln23_6_fu_1116_p2;

assign zext_ln23_9_fu_1141_p1 = add_ln23_41_fu_1136_p2;

assign zext_ln23_fu_1025_p1 = tmp_1_fu_1017_p3;

always @ (posedge ap_clk) begin
    add_ln23_40_reg_2787[2:0] <= 3'b000;
end

endmodule //kernel_mvt_kernel_mvt_Pipeline_VITIS_LOOP_21_1
