// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="kernel_nussinov_kernel_nussinov,hls_ip_2023_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.040000,HLS_SYN_LAT=214201,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=496,HLS_SYN_LUT=1112,HLS_VERSION=2023_1_1}" *)

module kernel_nussinov (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        seq_address0,
        seq_ce0,
        seq_q0,
        table_r_address0,
        table_r_ce0,
        table_r_we0,
        table_r_d0,
        table_r_q0,
        table_r_address1,
        table_r_ce1,
        table_r_q1
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] seq_address0;
output   seq_ce0;
input  [7:0] seq_q0;
output  [11:0] table_r_address0;
output   table_r_ce0;
output   table_r_we0;
output  [31:0] table_r_d0;
input  [31:0] table_r_q0;
output  [11:0] table_r_address1;
output   table_r_ce1;
input  [31:0] table_r_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[5:0] seq_address0;
reg seq_ce0;
reg[11:0] table_r_address0;
reg table_r_ce0;
reg table_r_we0;
reg[11:0] table_r_address1;
reg table_r_ce1;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] trunc_ln17_fu_181_p1;
reg   [5:0] trunc_ln17_reg_475;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_4_fu_185_p3;
wire   [11:0] sub_ln21_fu_216_p2;
reg   [11:0] sub_ln21_reg_489;
wire    ap_CS_fsm_state3;
wire   [6:0] zext_ln17_1_fu_222_p1;
wire   [11:0] sub_ln23_fu_251_p2;
reg   [11:0] sub_ln23_reg_501;
wire  signed [8:0] sext_ln18_fu_257_p1;
reg  signed [8:0] sext_ln18_reg_507;
wire   [11:0] add_ln21_fu_276_p2;
reg   [11:0] add_ln21_reg_515;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln18_fu_261_p2;
wire   [11:0] add_ln23_fu_286_p2;
reg   [11:0] add_ln23_reg_525;
wire   [11:0] add_ln28_2_fu_311_p2;
reg   [11:0] add_ln28_2_reg_535;
wire   [0:0] icmp_ln27_fu_316_p2;
reg   [0:0] icmp_ln27_reg_540;
wire   [6:0] add_ln18_1_fu_321_p2;
reg   [6:0] add_ln18_1_reg_550;
wire    ap_CS_fsm_state5;
wire   [31:0] select_ln21_fu_368_p3;
reg   [31:0] select_ln21_reg_565;
wire   [0:0] icmp_ln28_fu_385_p2;
reg   [0:0] icmp_ln28_reg_571;
wire   [31:0] select_ln23_fu_402_p3;
reg   [31:0] select_ln23_reg_576;
wire    ap_CS_fsm_state6;
reg   [31:0] table_r_load_3_reg_584;
wire   [31:0] add_ln28_1_fu_412_p2;
reg   [31:0] add_ln28_1_reg_590;
reg   [5:0] indvars_iv_load_2_reg_596;
wire    ap_CS_fsm_state7;
wire   [31:0] select_ln27_fu_450_p3;
reg   [31:0] select_ln27_reg_601;
wire    grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_start;
wire    grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_done;
wire    grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_idle;
wire    grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_ready;
wire   [11:0] grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_address0;
wire    grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_ce0;
wire    grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_we0;
wire   [31:0] grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_d0;
wire   [11:0] grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_address1;
wire    grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_ce1;
reg   [6:0] j_reg_142;
wire    ap_CS_fsm_state8;
reg    grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_start_reg;
wire   [63:0] zext_ln17_fu_193_p1;
wire   [63:0] zext_ln21_2_fu_281_p1;
wire   [63:0] zext_ln21_4_fu_306_p1;
wire   [63:0] zext_ln18_fu_267_p1;
wire   [63:0] zext_ln23_1_fu_348_p1;
wire   [63:0] zext_ln28_1_fu_352_p1;
reg   [5:0] indvars_iv_fu_72;
wire   [5:0] add_ln17_1_fu_332_p2;
reg   [6:0] i_fu_76;
wire   [6:0] add_ln17_fu_327_p2;
wire   [8:0] tmp_1_fu_205_p3;
wire   [11:0] tmp_fu_198_p3;
wire   [11:0] zext_ln21_fu_212_p1;
wire   [5:0] add_ln18_fu_226_p2;
wire   [7:0] tmp_3_fu_239_p3;
wire   [11:0] tmp_2_fu_231_p3;
wire   [11:0] zext_ln23_fu_247_p1;
wire   [11:0] zext_ln21_1_fu_272_p1;
wire   [6:0] add_ln20_fu_291_p2;
wire   [11:0] zext_ln21_3_fu_297_p1;
wire   [11:0] add_ln21_1_fu_301_p2;
wire   [0:0] icmp_ln21_fu_356_p2;
wire   [0:0] xor_ln21_fu_362_p2;
wire  signed [8:0] sext_ln28_fu_376_p1;
wire   [8:0] add_ln28_fu_380_p2;
wire   [0:0] icmp_ln23_fu_391_p2;
wire   [0:0] xor_ln23_fu_396_p2;
wire   [31:0] zext_ln28_fu_409_p1;
wire   [0:0] icmp_ln28_1_fu_418_p2;
wire   [0:0] xor_ln28_fu_422_p2;
wire   [0:0] icmp_ln30_fu_434_p2;
wire   [0:0] xor_ln30_fu_438_p2;
wire   [31:0] select_ln28_fu_428_p3;
wire   [31:0] select_ln30_fu_444_p3;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_start_reg = 1'b0;
end

kernel_nussinov_kernel_nussinov_Pipeline_VITIS_LOOP_33_3 grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_start),
    .ap_done(grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_done),
    .ap_idle(grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_idle),
    .ap_ready(grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_ready),
    .select_ln27(select_ln27_reg_601),
    .zext_ln17(indvars_iv_load_2_reg_596),
    .table_r_address0(grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_address0),
    .table_r_ce0(grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_ce0),
    .table_r_we0(grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_we0),
    .table_r_d0(grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_d0),
    .table_r_q0(table_r_q0),
    .table_r_address1(grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_address1),
    .table_r_ce1(grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_ce1),
    .table_r_q1(table_r_q1),
    .add_ln21(add_ln21_reg_515),
    .sub_ln21(sub_ln21_reg_489),
    .zext_ln18(j_reg_142)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_start_reg <= 1'b1;
        end else if ((grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_ready == 1'b1)) begin
            grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_76 <= 7'd59;
    end else if (((icmp_ln18_fu_261_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        i_fu_76 <= add_ln17_fu_327_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvars_iv_fu_72 <= 6'd60;
    end else if (((icmp_ln18_fu_261_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        indvars_iv_fu_72 <= add_ln17_1_fu_332_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_done == 1'b1))) begin
        j_reg_142 <= add_ln18_1_reg_550;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        j_reg_142 <= zext_ln17_1_fu_222_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_261_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        add_ln18_1_reg_550 <= add_ln18_1_fu_321_p2;
        add_ln21_reg_515 <= add_ln21_fu_276_p2;
        add_ln23_reg_525 <= add_ln23_fu_286_p2;
        add_ln28_2_reg_535 <= add_ln28_2_fu_311_p2;
        icmp_ln27_reg_540 <= icmp_ln27_fu_316_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_reg_540 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        add_ln28_1_reg_590 <= add_ln28_1_fu_412_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_reg_540 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        icmp_ln28_reg_571 <= icmp_ln28_fu_385_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        indvars_iv_load_2_reg_596 <= indvars_iv_fu_72;
        select_ln27_reg_601 <= select_ln27_fu_450_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        select_ln21_reg_565 <= select_ln21_fu_368_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        select_ln23_reg_576 <= select_ln23_fu_402_p3;
        table_r_load_3_reg_584 <= table_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sext_ln18_reg_507 <= sext_ln18_fu_257_p1;
        sub_ln21_reg_489[11 : 2] <= sub_ln21_fu_216_p2[11 : 2];
        sub_ln23_reg_501[11 : 2] <= sub_ln23_fu_251_p2[11 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln17_reg_475 <= trunc_ln17_fu_181_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_4_fu_185_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_4_fu_185_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        seq_address0 = zext_ln18_fu_267_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        seq_address0 = zext_ln17_fu_193_p1;
    end else begin
        seq_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        seq_ce0 = 1'b1;
    end else begin
        seq_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        table_r_address0 = zext_ln28_1_fu_352_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        table_r_address0 = zext_ln21_4_fu_306_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        table_r_address0 = grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_address0;
    end else begin
        table_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        table_r_address1 = zext_ln23_1_fu_348_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        table_r_address1 = zext_ln21_2_fu_281_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        table_r_address1 = grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_address1;
    end else begin
        table_r_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state5))) begin
        table_r_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        table_r_ce0 = grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_ce0;
    end else begin
        table_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state5))) begin
        table_r_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        table_r_ce1 = grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_ce1;
    end else begin
        table_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        table_r_we0 = grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_we0;
    end else begin
        table_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_4_fu_185_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln18_fu_261_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln17_1_fu_332_p2 = ($signed(indvars_iv_fu_72) + $signed(6'd63));

assign add_ln17_fu_327_p2 = ($signed(i_fu_76) + $signed(7'd127));

assign add_ln18_1_fu_321_p2 = (j_reg_142 + 7'd1);

assign add_ln18_fu_226_p2 = (trunc_ln17_reg_475 + 6'd1);

assign add_ln20_fu_291_p2 = ($signed(j_reg_142) + $signed(7'd127));

assign add_ln21_1_fu_301_p2 = (sub_ln21_reg_489 + zext_ln21_3_fu_297_p1);

assign add_ln21_fu_276_p2 = (sub_ln21_reg_489 + zext_ln21_1_fu_272_p1);

assign add_ln23_fu_286_p2 = (sub_ln23_reg_501 + zext_ln21_1_fu_272_p1);

assign add_ln28_1_fu_412_p2 = (table_r_q0 + zext_ln28_fu_409_p1);

assign add_ln28_2_fu_311_p2 = (sub_ln23_reg_501 + zext_ln21_3_fu_297_p1);

assign add_ln28_fu_380_p2 = ($signed(sext_ln28_fu_376_p1) + $signed(sext_ln18_reg_507));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_start = grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_ap_start_reg;

assign icmp_ln18_fu_261_p2 = ((j_reg_142 == 7'd60) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_356_p2 = (($signed(table_r_q1) < $signed(table_r_q0)) ? 1'b1 : 1'b0);

assign icmp_ln23_fu_391_p2 = (($signed(select_ln21_reg_565) < $signed(table_r_q1)) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_316_p2 = ((i_fu_76 < add_ln20_fu_291_p2) ? 1'b1 : 1'b0);

assign icmp_ln28_1_fu_418_p2 = (($signed(select_ln23_reg_576) < $signed(add_ln28_1_reg_590)) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_385_p2 = ((add_ln28_fu_380_p2 == 9'd3) ? 1'b1 : 1'b0);

assign icmp_ln30_fu_434_p2 = (($signed(select_ln23_reg_576) < $signed(table_r_load_3_reg_584)) ? 1'b1 : 1'b0);

assign select_ln21_fu_368_p3 = ((xor_ln21_fu_362_p2[0:0] == 1'b1) ? table_r_q1 : table_r_q0);

assign select_ln23_fu_402_p3 = ((xor_ln23_fu_396_p2[0:0] == 1'b1) ? select_ln21_reg_565 : table_r_q1);

assign select_ln27_fu_450_p3 = ((icmp_ln27_reg_540[0:0] == 1'b1) ? select_ln28_fu_428_p3 : select_ln30_fu_444_p3);

assign select_ln28_fu_428_p3 = ((xor_ln28_fu_422_p2[0:0] == 1'b1) ? select_ln23_reg_576 : add_ln28_1_reg_590);

assign select_ln30_fu_444_p3 = ((xor_ln30_fu_438_p2[0:0] == 1'b1) ? select_ln23_reg_576 : table_r_load_3_reg_584);

assign sext_ln18_fu_257_p1 = $signed(seq_q0);

assign sext_ln28_fu_376_p1 = $signed(seq_q0);

assign sub_ln21_fu_216_p2 = (tmp_fu_198_p3 - zext_ln21_fu_212_p1);

assign sub_ln23_fu_251_p2 = (tmp_2_fu_231_p3 - zext_ln23_fu_247_p1);

assign table_r_d0 = grp_kernel_nussinov_Pipeline_VITIS_LOOP_33_3_fu_152_table_r_d0;

assign tmp_1_fu_205_p3 = {{i_fu_76}, {2'd0}};

assign tmp_2_fu_231_p3 = {{add_ln18_fu_226_p2}, {6'd0}};

assign tmp_3_fu_239_p3 = {{add_ln18_fu_226_p2}, {2'd0}};

assign tmp_4_fu_185_p3 = i_fu_76[32'd6];

assign tmp_fu_198_p3 = {{trunc_ln17_reg_475}, {6'd0}};

assign trunc_ln17_fu_181_p1 = i_fu_76[5:0];

assign xor_ln21_fu_362_p2 = (icmp_ln21_fu_356_p2 ^ 1'd1);

assign xor_ln23_fu_396_p2 = (icmp_ln23_fu_391_p2 ^ 1'd1);

assign xor_ln28_fu_422_p2 = (icmp_ln28_1_fu_418_p2 ^ 1'd1);

assign xor_ln30_fu_438_p2 = (icmp_ln30_fu_434_p2 ^ 1'd1);

assign zext_ln17_1_fu_222_p1 = indvars_iv_fu_72;

assign zext_ln17_fu_193_p1 = i_fu_76;

assign zext_ln18_fu_267_p1 = j_reg_142;

assign zext_ln21_1_fu_272_p1 = j_reg_142;

assign zext_ln21_2_fu_281_p1 = add_ln21_fu_276_p2;

assign zext_ln21_3_fu_297_p1 = add_ln20_fu_291_p2;

assign zext_ln21_4_fu_306_p1 = add_ln21_1_fu_301_p2;

assign zext_ln21_fu_212_p1 = tmp_1_fu_205_p3;

assign zext_ln23_1_fu_348_p1 = add_ln23_reg_525;

assign zext_ln23_fu_247_p1 = tmp_3_fu_239_p3;

assign zext_ln28_1_fu_352_p1 = add_ln28_2_reg_535;

assign zext_ln28_fu_409_p1 = icmp_ln28_reg_571;

always @ (posedge ap_clk) begin
    sub_ln21_reg_489[1:0] <= 2'b00;
    sub_ln23_reg_501[1:0] <= 2'b00;
end

endmodule //kernel_nussinov
