// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module kernel_cholesky_sqrt_fixed_32_16_s (
        ap_clk,
        ap_rst,
        x_val,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [31:0] x_val;
output  [23:0] ap_return;

reg   [31:0] x_val_read_reg_3531;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] x_val_read_reg_3531_pp0_iter1_reg;
reg   [31:0] x_val_read_reg_3531_pp0_iter2_reg;
reg   [31:0] x_val_read_reg_3531_pp0_iter3_reg;
reg   [31:0] x_val_read_reg_3531_pp0_iter4_reg;
reg   [31:0] x_val_read_reg_3531_pp0_iter5_reg;
reg   [31:0] x_val_read_reg_3531_pp0_iter6_reg;
reg   [31:0] x_val_read_reg_3531_pp0_iter7_reg;
reg   [31:0] x_val_read_reg_3531_pp0_iter8_reg;
reg   [31:0] x_val_read_reg_3531_pp0_iter9_reg;
reg   [31:0] x_val_read_reg_3531_pp0_iter10_reg;
reg   [31:0] x_val_read_reg_3531_pp0_iter11_reg;
reg   [31:0] x_val_read_reg_3531_pp0_iter12_reg;
reg   [31:0] x_val_read_reg_3531_pp0_iter13_reg;
reg   [31:0] x_val_read_reg_3531_pp0_iter14_reg;
reg   [31:0] x_val_read_reg_3531_pp0_iter15_reg;
reg   [31:0] x_val_read_reg_3531_pp0_iter16_reg;
wire   [15:0] trunc_ln236_fu_306_p1;
reg   [15:0] trunc_ln236_reg_3536;
reg   [15:0] trunc_ln236_reg_3536_pp0_iter1_reg;
reg   [15:0] trunc_ln236_reg_3536_pp0_iter2_reg;
reg   [15:0] trunc_ln236_reg_3536_pp0_iter3_reg;
wire   [18:0] x_l_I_1_fu_348_p3;
reg   [18:0] x_l_I_1_reg_3541;
wire   [7:0] res_I_fu_356_p3;
reg   [7:0] res_I_reg_3547;
wire   [0:0] icmp_ln281_1_fu_396_p2;
reg   [0:0] icmp_ln281_1_reg_3553;
wire   [3:0] sub_ln286_fu_402_p2;
reg   [3:0] sub_ln286_reg_3559;
wire   [0:0] icmp_ln318_2_fu_418_p2;
reg   [0:0] icmp_ln318_2_reg_3564;
reg   [0:0] icmp_ln318_2_reg_3564_pp0_iter1_reg;
reg   [0:0] icmp_ln318_2_reg_3564_pp0_iter2_reg;
reg   [0:0] icmp_ln318_2_reg_3564_pp0_iter3_reg;
wire   [0:0] icmp_ln331_fu_434_p2;
reg   [0:0] icmp_ln331_reg_3569;
reg   [0:0] icmp_ln331_reg_3569_pp0_iter1_reg;
reg   [0:0] icmp_ln331_reg_3569_pp0_iter2_reg;
reg   [0:0] icmp_ln331_reg_3569_pp0_iter3_reg;
wire   [18:0] x_l_I_5_fu_537_p3;
reg   [18:0] x_l_I_5_reg_3574;
wire   [7:0] res_I_4_fu_545_p3;
reg   [7:0] res_I_4_reg_3580;
wire   [0:0] icmp_ln281_3_fu_585_p2;
reg   [0:0] icmp_ln281_3_reg_3586;
wire   [5:0] sub_ln286_2_fu_591_p2;
reg   [5:0] sub_ln286_2_reg_3592;
wire   [18:0] x_l_I_9_fu_694_p3;
reg   [18:0] x_l_I_9_reg_3597;
wire   [7:0] res_I_8_fu_702_p3;
reg   [7:0] res_I_8_reg_3603;
wire   [0:0] icmp_ln281_5_fu_742_p2;
reg   [0:0] icmp_ln281_5_reg_3609;
wire   [7:0] sub_ln286_4_fu_748_p2;
reg   [7:0] sub_ln286_4_reg_3615;
wire   [7:0] res_I_12_fu_859_p3;
reg   [7:0] res_I_12_reg_3620;
wire   [0:0] icmp_ln281_7_fu_883_p2;
reg   [0:0] icmp_ln281_7_reg_3626;
wire   [18:0] x_l_I_15_fu_907_p3;
reg   [18:0] x_l_I_15_reg_3631;
wire   [7:0] res_I_14_fu_931_p3;
reg   [7:0] res_I_14_reg_3640;
reg   [7:0] res_I_14_reg_3640_pp0_iter5_reg;
reg   [7:0] res_I_14_reg_3640_pp0_iter6_reg;
reg   [7:0] res_I_14_reg_3640_pp0_iter7_reg;
reg   [7:0] res_I_14_reg_3640_pp0_iter8_reg;
reg   [7:0] res_I_14_reg_3640_pp0_iter9_reg;
reg   [7:0] res_I_14_reg_3640_pp0_iter10_reg;
reg   [7:0] res_I_14_reg_3640_pp0_iter11_reg;
reg   [7:0] res_I_14_reg_3640_pp0_iter12_reg;
reg   [7:0] res_I_14_reg_3640_pp0_iter13_reg;
reg   [7:0] res_I_14_reg_3640_pp0_iter14_reg;
reg   [7:0] res_I_14_reg_3640_pp0_iter15_reg;
reg   [7:0] res_I_14_reg_3640_pp0_iter16_reg;
wire   [18:0] x_l_I_19_fu_993_p3;
reg   [18:0] x_l_I_19_reg_3655;
wire   [16:0] x_l_FH_34_fu_1000_p3;
reg   [16:0] x_l_FH_34_reg_3661;
wire   [16:0] res_FH_fu_1008_p3;
reg   [16:0] res_FH_reg_3667;
wire   [16:0] mul_FH_fu_1030_p4;
reg   [16:0] mul_FH_reg_3673;
wire   [18:0] zext_ln318_1_fu_1058_p1;
reg   [18:0] zext_ln318_1_reg_3678;
wire   [0:0] icmp_ln318_3_fu_1062_p2;
reg   [0:0] icmp_ln318_3_reg_3683;
wire   [0:0] icmp_ln318_4_fu_1068_p2;
reg   [0:0] icmp_ln318_4_reg_3688;
wire   [0:0] icmp_ln318_5_fu_1074_p2;
reg   [0:0] icmp_ln318_5_reg_3693;
wire   [0:0] icmp_ln331_1_fu_1080_p2;
reg   [0:0] icmp_ln331_1_reg_3698;
wire   [18:0] x_l_I_20_fu_1086_p2;
reg   [18:0] x_l_I_20_reg_3703;
wire   [1:0] trunc_ln306_1_fu_1092_p1;
reg   [1:0] trunc_ln306_1_reg_3708;
reg   [5:0] tmp_25_reg_3713;
wire   [2:0] trunc_ln306_2_fu_1106_p1;
reg   [2:0] trunc_ln306_2_reg_3718;
reg   [2:0] trunc_ln306_2_reg_3718_pp0_iter5_reg;
reg   [4:0] tmp_27_reg_3723;
reg   [4:0] tmp_27_reg_3723_pp0_iter5_reg;
wire   [3:0] trunc_ln306_3_fu_1120_p1;
reg   [3:0] trunc_ln306_3_reg_3728;
reg   [3:0] trunc_ln306_3_reg_3728_pp0_iter5_reg;
reg   [3:0] trunc_ln306_3_reg_3728_pp0_iter6_reg;
reg   [3:0] tmp_30_reg_3733;
reg   [3:0] tmp_30_reg_3733_pp0_iter5_reg;
reg   [3:0] tmp_30_reg_3733_pp0_iter6_reg;
wire   [4:0] trunc_ln306_4_fu_1134_p1;
reg   [4:0] trunc_ln306_4_reg_3738;
reg   [4:0] trunc_ln306_4_reg_3738_pp0_iter5_reg;
reg   [4:0] trunc_ln306_4_reg_3738_pp0_iter6_reg;
reg   [2:0] tmp_33_reg_3743;
reg   [2:0] tmp_33_reg_3743_pp0_iter5_reg;
reg   [2:0] tmp_33_reg_3743_pp0_iter6_reg;
wire   [5:0] trunc_ln306_5_fu_1148_p1;
reg   [5:0] trunc_ln306_5_reg_3748;
reg   [5:0] trunc_ln306_5_reg_3748_pp0_iter5_reg;
reg   [5:0] trunc_ln306_5_reg_3748_pp0_iter6_reg;
reg   [5:0] trunc_ln306_5_reg_3748_pp0_iter7_reg;
reg   [1:0] tmp_35_reg_3753;
reg   [1:0] tmp_35_reg_3753_pp0_iter5_reg;
reg   [1:0] tmp_35_reg_3753_pp0_iter6_reg;
reg   [1:0] tmp_35_reg_3753_pp0_iter7_reg;
wire   [6:0] trunc_ln306_6_fu_1162_p1;
reg   [6:0] trunc_ln306_6_reg_3758;
reg   [6:0] trunc_ln306_6_reg_3758_pp0_iter5_reg;
reg   [6:0] trunc_ln306_6_reg_3758_pp0_iter6_reg;
reg   [6:0] trunc_ln306_6_reg_3758_pp0_iter7_reg;
reg   [6:0] trunc_ln306_6_reg_3758_pp0_iter8_reg;
reg   [0:0] tmp_42_reg_3763;
reg   [0:0] tmp_42_reg_3763_pp0_iter5_reg;
reg   [0:0] tmp_42_reg_3763_pp0_iter6_reg;
reg   [0:0] tmp_42_reg_3763_pp0_iter7_reg;
reg   [0:0] tmp_42_reg_3763_pp0_iter8_reg;
wire   [18:0] x_l_I_23_fu_1212_p3;
reg   [18:0] x_l_I_23_reg_3768;
wire   [16:0] res_FH_2_fu_1226_p3;
reg   [16:0] res_FH_2_reg_3773;
wire   [18:0] x_l_I_26_fu_1313_p2;
reg   [18:0] x_l_I_26_reg_3779;
wire   [0:0] or_ln318_3_fu_1325_p2;
reg   [0:0] or_ln318_3_reg_3784;
wire   [16:0] x_l_FH_36_fu_1331_p3;
reg   [16:0] x_l_FH_36_reg_3790;
wire   [18:0] x_l_I_31_fu_1464_p3;
reg   [18:0] x_l_I_31_reg_3798;
wire   [16:0] x_l_FH_37_fu_1472_p3;
reg   [16:0] x_l_FH_37_reg_3807;
wire   [16:0] res_FH_6_fu_1479_p3;
reg   [16:0] res_FH_6_reg_3815;
reg   [4:0] tmp_28_reg_3821;
wire   [18:0] x_l_I_35_fu_1586_p3;
reg   [18:0] x_l_I_35_reg_3826;
wire   [16:0] x_l_FH_38_fu_1593_p3;
reg   [16:0] x_l_FH_38_reg_3832;
wire   [16:0] res_FH_8_fu_1600_p3;
reg   [16:0] res_FH_8_reg_3838;
wire   [16:0] mul_FH_4_fu_1617_p4;
reg   [16:0] mul_FH_4_reg_3844;
wire   [18:0] zext_ln318_5_fu_1633_p1;
reg   [18:0] zext_ln318_5_reg_3849;
wire   [0:0] icmp_ln318_15_fu_1637_p2;
reg   [0:0] icmp_ln318_15_reg_3854;
wire   [0:0] icmp_ln318_16_fu_1643_p2;
reg   [0:0] icmp_ln318_16_reg_3859;
wire   [0:0] icmp_ln318_17_fu_1649_p2;
reg   [0:0] icmp_ln318_17_reg_3864;
wire   [0:0] icmp_ln331_5_fu_1655_p2;
reg   [0:0] icmp_ln331_5_reg_3869;
wire   [18:0] x_l_I_36_fu_1661_p2;
reg   [18:0] x_l_I_36_reg_3874;
wire   [18:0] x_l_I_39_fu_1705_p3;
reg   [18:0] x_l_I_39_reg_3879;
wire   [16:0] res_FH_10_fu_1719_p3;
reg   [16:0] res_FH_10_reg_3884;
wire   [18:0] x_l_I_42_fu_1806_p2;
reg   [18:0] x_l_I_42_reg_3890;
wire   [0:0] or_ln318_7_fu_1818_p2;
reg   [0:0] or_ln318_7_reg_3895;
wire   [16:0] x_l_FH_40_fu_1824_p3;
reg   [16:0] x_l_FH_40_reg_3901;
wire   [16:0] res_FH_12_fu_1846_p3;
reg   [16:0] res_FH_12_reg_3909;
wire   [0:0] or_ln318_8_fu_1941_p2;
reg   [0:0] or_ln318_8_reg_3915;
wire   [18:0] x_l_I_47_fu_1947_p3;
reg   [18:0] x_l_I_47_reg_3920;
wire   [16:0] x_l_FH_41_fu_1955_p3;
reg   [16:0] x_l_FH_41_reg_3927;
wire   [18:0] x_l_I_50_fu_2043_p3;
reg   [18:0] x_l_I_50_reg_3934;
wire   [16:0] x_l_FH_42_fu_2051_p3;
reg   [16:0] x_l_FH_42_reg_3941;
wire   [16:0] x_l_FL_15_fu_2058_p3;
reg   [16:0] x_l_FL_15_reg_3950;
wire   [16:0] res_FH_16_fu_2066_p3;
reg   [16:0] res_FH_16_reg_3957;
reg   [7:0] tmp_43_reg_3963;
wire   [16:0] mul_FL_fu_2094_p3;
reg   [16:0] mul_FL_reg_3968;
wire   [0:0] delta_fu_2102_p2;
reg   [0:0] delta_reg_3974;
wire   [18:0] x_l_I_53_fu_2218_p3;
reg   [18:0] x_l_I_53_reg_3980;
wire   [16:0] x_l_FH_43_fu_2226_p3;
reg   [16:0] x_l_FH_43_reg_3987;
wire   [16:0] x_l_FL_16_fu_2233_p3;
reg   [16:0] x_l_FL_16_reg_3996;
wire   [16:0] res_FH_18_fu_2240_p3;
reg   [16:0] res_FH_18_reg_4003;
reg   [6:0] tmp_44_reg_4009;
wire   [16:0] mul_FL_1_fu_2267_p3;
reg   [16:0] mul_FL_1_reg_4014;
wire   [0:0] delta_1_fu_2275_p2;
reg   [0:0] delta_1_reg_4020;
wire   [16:0] p_neg153_fu_2281_p3;
reg   [16:0] p_neg153_reg_4025;
wire   [18:0] x_l_I_56_fu_2395_p3;
reg   [18:0] x_l_I_56_reg_4030;
wire   [16:0] x_l_FH_44_fu_2403_p3;
reg   [16:0] x_l_FH_44_reg_4036;
wire   [16:0] x_l_FL_17_fu_2410_p3;
reg   [16:0] x_l_FL_17_reg_4042;
wire   [16:0] res_FH_20_fu_2417_p3;
reg   [16:0] res_FH_20_reg_4048;
wire   [14:0] mul_FH_s_fu_2444_p4;
reg   [14:0] mul_FH_s_reg_4054;
wire   [16:0] mul_FL_2_fu_2457_p3;
reg   [16:0] mul_FL_2_reg_4059;
wire   [0:0] icmp_ln318_34_fu_2465_p2;
reg   [0:0] icmp_ln318_34_reg_4064;
wire   [0:0] icmp_ln318_35_fu_2471_p2;
reg   [0:0] icmp_ln318_35_reg_4069;
wire   [0:0] icmp_ln318_36_fu_2477_p2;
reg   [0:0] icmp_ln318_36_reg_4074;
wire   [0:0] icmp_ln318_37_fu_2483_p2;
reg   [0:0] icmp_ln318_37_reg_4080;
wire   [0:0] delta_2_fu_2489_p2;
reg   [0:0] delta_2_reg_4085;
wire   [0:0] icmp_ln331_10_fu_2495_p2;
reg   [0:0] icmp_ln331_10_reg_4091;
wire   [18:0] x_l_I_59_fu_2580_p3;
reg   [18:0] x_l_I_59_reg_4096;
wire   [16:0] x_l_FH_45_fu_2588_p3;
reg   [16:0] x_l_FH_45_reg_4102;
wire   [16:0] x_l_FL_18_fu_2595_p3;
reg   [16:0] x_l_FL_18_reg_4108;
wire   [16:0] res_FH_22_fu_2602_p3;
reg   [16:0] res_FH_22_reg_4114;
wire   [16:0] mul_FL_3_fu_2646_p3;
reg   [16:0] mul_FL_3_reg_4120;
wire   [0:0] icmp_ln318_38_fu_2654_p2;
reg   [0:0] icmp_ln318_38_reg_4125;
wire   [0:0] icmp_ln318_39_fu_2660_p2;
reg   [0:0] icmp_ln318_39_reg_4130;
wire   [0:0] icmp_ln318_40_fu_2666_p2;
reg   [0:0] icmp_ln318_40_reg_4135;
wire   [0:0] icmp_ln318_41_fu_2672_p2;
reg   [0:0] icmp_ln318_41_reg_4141;
wire   [0:0] delta_3_fu_2678_p2;
reg   [0:0] delta_3_reg_4146;
wire   [0:0] icmp_ln331_11_fu_2684_p2;
reg   [0:0] icmp_ln331_11_reg_4151;
wire   [14:0] sub_ln335_3_fu_2698_p2;
reg   [14:0] sub_ln335_3_reg_4156;
wire   [16:0] x_l_FH_46_fu_2774_p3;
reg   [16:0] x_l_FH_46_reg_4161;
wire   [13:0] sub_ln335_4_fu_2922_p2;
reg   [13:0] sub_ln335_4_reg_4167;
wire   [0:0] or_ln318_18_fu_2950_p2;
reg   [0:0] or_ln318_18_reg_4172;
wire   [18:0] x_l_I_65_fu_2956_p3;
reg   [18:0] x_l_I_65_reg_4177;
wire   [16:0] x_l_FL_20_fu_2964_p3;
reg   [16:0] x_l_FL_20_reg_4184;
wire   [16:0] res_FH_26_fu_2972_p3;
reg   [16:0] res_FH_26_reg_4192;
reg   [11:0] tmp_40_reg_4198;
reg   [2:0] tmp_48_reg_4203;
wire   [18:0] x_l_I_68_fu_3156_p3;
reg   [18:0] x_l_I_68_reg_4208;
wire   [16:0] x_l_FH_48_fu_3164_p3;
reg   [16:0] x_l_FH_48_reg_4215;
wire   [16:0] x_l_FL_21_fu_3172_p3;
reg   [16:0] x_l_FL_21_reg_4224;
wire   [16:0] res_FH_28_fu_3179_p3;
reg   [16:0] res_FH_28_reg_4232;
reg   [13:0] tmp_41_reg_4238;
reg   [1:0] tmp_49_reg_4243;
wire   [0:0] or_ln318_22_fu_3338_p2;
reg   [0:0] or_ln318_22_reg_4248;
wire   [16:0] x_l_FH_32_fu_3344_p3;
reg   [16:0] x_l_FH_32_reg_4253;
wire   [16:0] res_FH_30_fu_3358_p3;
reg   [16:0] res_FH_30_reg_4259;
reg   [0:0] tmp_60_reg_4265;
wire   [0:0] icmp_ln318_54_fu_3385_p2;
reg   [0:0] icmp_ln318_54_reg_4270;
wire   [0:0] icmp_ln318_57_fu_3391_p2;
reg   [0:0] icmp_ln318_57_reg_4275;
wire    ap_block_pp0_stage0;
wire   [15:0] trunc_ln_fu_292_p4;
wire   [1:0] tmp_1_fu_310_p4;
wire   [2:0] zext_ln281_fu_320_p1;
wire   [18:0] zext_ln235_fu_302_p1;
wire   [2:0] add_ln286_fu_330_p2;
wire   [0:0] icmp_ln281_fu_324_p2;
wire   [18:0] x_l_I_fu_336_p5;
wire   [1:0] tmp_s_fu_364_p4;
wire   [2:0] tmp_fu_374_p3;
wire   [3:0] tmp_3_fu_382_p4;
wire   [3:0] zext_ln281_1_fu_392_p1;
wire   [1:0] tmp_22_fu_408_p4;
wire   [1:0] tmp_23_fu_424_p4;
wire   [18:0] x_l_I_2_fu_440_p5;
wire   [7:0] res_I_1_fu_450_p4;
wire   [7:0] res_I_2_fu_465_p3;
wire   [2:0] tmp_4_fu_471_p4;
wire   [18:0] x_l_I_3_fu_459_p3;
wire   [3:0] tmp_6_fu_481_p3;
wire   [4:0] tmp_5_fu_489_p4;
wire   [4:0] zext_ln281_2_fu_499_p1;
wire   [4:0] sub_ln286_1_fu_509_p2;
wire   [0:0] icmp_ln281_2_fu_503_p2;
wire   [18:0] x_l_I_4_fu_515_p5;
wire   [7:0] res_I_3_fu_527_p4;
wire   [3:0] tmp_8_fu_553_p4;
wire   [4:0] tmp_7_fu_563_p3;
wire   [5:0] tmp_9_fu_571_p4;
wire   [5:0] zext_ln281_3_fu_581_p1;
wire   [18:0] x_l_I_6_fu_597_p5;
wire   [7:0] res_I_5_fu_607_p4;
wire   [7:0] res_I_6_fu_622_p3;
wire   [4:0] tmp_10_fu_628_p4;
wire   [18:0] x_l_I_7_fu_616_p3;
wire   [5:0] tmp_11_fu_638_p3;
wire   [6:0] tmp_12_fu_646_p4;
wire   [6:0] zext_ln281_4_fu_656_p1;
wire   [6:0] sub_ln286_3_fu_666_p2;
wire   [0:0] icmp_ln281_4_fu_660_p2;
wire   [18:0] x_l_I_8_fu_672_p5;
wire   [7:0] res_I_7_fu_684_p4;
wire   [5:0] tmp_13_fu_710_p4;
wire   [6:0] tmp_14_fu_720_p3;
wire   [7:0] tmp_15_fu_728_p4;
wire   [7:0] zext_ln281_5_fu_738_p1;
wire   [18:0] x_l_I_10_fu_754_p5;
wire   [7:0] res_I_9_fu_764_p4;
wire   [7:0] res_I_10_fu_779_p3;
wire   [6:0] tmp_16_fu_785_p4;
wire   [18:0] x_l_I_11_fu_773_p3;
wire   [7:0] tmp_17_fu_795_p3;
wire   [8:0] tmp_19_fu_803_p4;
wire   [8:0] zext_ln281_6_fu_813_p1;
wire   [8:0] sub_ln286_5_fu_823_p2;
wire   [0:0] icmp_ln281_6_fu_817_p2;
wire   [18:0] x_l_I_12_fu_829_p5;
wire   [7:0] res_I_11_fu_841_p4;
wire   [18:0] x_l_I_13_fu_851_p3;
wire   [8:0] tmp_18_fu_867_p3;
wire   [9:0] trunc_ln281_fu_875_p1;
wire   [9:0] zext_ln281_7_fu_879_p1;
wire   [9:0] sub_ln286_6_fu_889_p2;
wire   [18:0] x_l_I_14_fu_895_p5;
wire   [7:0] res_I_13_fu_922_p4;
wire   [8:0] trunc_ln2_fu_937_p3;
wire   [18:0] zext_ln318_fu_945_p1;
wire   [0:0] icmp_ln318_1_fu_954_p2;
wire   [18:0] x_l_I_16_fu_964_p2;
wire   [18:0] x_l_I_17_fu_969_p3;
wire   [16:0] x_l_FH_33_fu_915_p3;
wire   [0:0] icmp_ln318_fu_949_p2;
wire   [0:0] and_ln318_fu_959_p2;
wire   [0:0] or_ln318_1_fu_987_p2;
wire   [18:0] x_l_I_18_fu_975_p2;
wire   [16:0] x_l_FH_fu_981_p2;
wire   [0:0] trunc_ln306_fu_1026_p1;
wire   [1:0] tmp_20_fu_1016_p4;
wire   [6:0] tmp_21_fu_1040_p4;
wire   [7:0] trunc_ln318_1_fu_1050_p3;
wire   [0:0] xor_ln318_fu_1174_p2;
wire   [18:0] x_l_I_21_fu_1184_p3;
wire   [0:0] and_ln318_1_fu_1179_p2;
wire   [0:0] or_ln318_2_fu_1207_p2;
wire   [18:0] x_l_I_22_fu_1189_p2;
wire   [16:0] x_l_FH_3_fu_1194_p2;
wire   [16:0] res_FH_1_fu_1198_p4;
wire   [2:0] tmp_24_fu_1233_p4;
wire   [6:0] trunc_ln318_2_fu_1252_p3;
wire   [18:0] zext_ln318_2_fu_1259_p1;
wire   [16:0] x_l_FH_35_fu_1219_p3;
wire   [16:0] mul_FH_1_fu_1243_p4;
wire   [0:0] icmp_ln318_8_fu_1275_p2;
wire   [0:0] icmp_ln318_7_fu_1269_p2;
wire   [0:0] xor_ln318_1_fu_1281_p2;
wire   [0:0] icmp_ln331_2_fu_1293_p2;
wire   [18:0] x_l_I_24_fu_1299_p2;
wire   [18:0] x_l_I_25_fu_1305_p3;
wire   [0:0] icmp_ln318_6_fu_1263_p2;
wire   [0:0] and_ln318_2_fu_1287_p2;
wire   [16:0] x_l_FH_5_fu_1319_p2;
wire   [16:0] res_FH_3_fu_1339_p4;
wire   [16:0] res_FH_4_fu_1353_p3;
wire   [3:0] tmp_26_fu_1359_p4;
wire   [5:0] trunc_ln318_3_fu_1378_p3;
wire   [18:0] x_l_I_27_fu_1348_p3;
wire   [18:0] zext_ln318_3_fu_1385_p1;
wire   [16:0] mul_FH_2_fu_1369_p4;
wire   [0:0] icmp_ln318_11_fu_1401_p2;
wire   [0:0] icmp_ln318_10_fu_1395_p2;
wire   [0:0] xor_ln318_2_fu_1406_p2;
wire   [0:0] icmp_ln331_3_fu_1418_p2;
wire   [18:0] x_l_I_28_fu_1423_p2;
wire   [18:0] x_l_I_29_fu_1429_p3;
wire   [0:0] icmp_ln318_9_fu_1389_p2;
wire   [0:0] and_ln318_3_fu_1412_p2;
wire   [0:0] or_ln318_4_fu_1458_p2;
wire   [18:0] x_l_I_30_fu_1437_p2;
wire   [16:0] x_l_FH_7_fu_1443_p2;
wire   [16:0] res_FH_5_fu_1448_p4;
wire   [4:0] trunc_ln318_4_fu_1505_p3;
wire   [18:0] zext_ln318_4_fu_1512_p1;
wire   [16:0] mul_FH_3_fu_1497_p4;
wire   [0:0] icmp_ln318_14_fu_1526_p2;
wire   [0:0] icmp_ln318_13_fu_1521_p2;
wire   [0:0] xor_ln318_3_fu_1531_p2;
wire   [0:0] icmp_ln331_4_fu_1543_p2;
wire   [18:0] x_l_I_32_fu_1548_p2;
wire   [18:0] x_l_I_33_fu_1553_p3;
wire   [0:0] icmp_ln318_12_fu_1516_p2;
wire   [0:0] and_ln318_4_fu_1537_p2;
wire   [0:0] or_ln318_5_fu_1580_p2;
wire   [18:0] x_l_I_34_fu_1560_p2;
wire   [16:0] x_l_FH_9_fu_1566_p2;
wire   [16:0] res_FH_7_fu_1571_p4;
wire   [5:0] tmp_32_fu_1607_p4;
wire   [3:0] trunc_ln318_5_fu_1626_p3;
wire   [0:0] xor_ln318_4_fu_1667_p2;
wire   [18:0] x_l_I_37_fu_1677_p3;
wire   [0:0] and_ln318_5_fu_1672_p2;
wire   [0:0] or_ln318_6_fu_1700_p2;
wire   [18:0] x_l_I_38_fu_1682_p2;
wire   [16:0] x_l_FH_11_fu_1687_p2;
wire   [16:0] res_FH_9_fu_1691_p4;
wire   [6:0] tmp_34_fu_1726_p4;
wire   [2:0] trunc_ln318_6_fu_1745_p3;
wire   [18:0] zext_ln318_6_fu_1752_p1;
wire   [16:0] x_l_FH_39_fu_1712_p3;
wire   [16:0] mul_FH_5_fu_1736_p4;
wire   [0:0] icmp_ln318_20_fu_1768_p2;
wire   [0:0] icmp_ln318_19_fu_1762_p2;
wire   [0:0] xor_ln318_5_fu_1774_p2;
wire   [0:0] icmp_ln331_6_fu_1786_p2;
wire   [18:0] x_l_I_40_fu_1792_p2;
wire   [18:0] x_l_I_41_fu_1798_p3;
wire   [0:0] icmp_ln318_18_fu_1756_p2;
wire   [0:0] and_ln318_6_fu_1780_p2;
wire   [16:0] x_l_FH_13_fu_1812_p2;
wire   [16:0] res_FH_11_fu_1832_p4;
wire   [7:0] tmp_36_fu_1852_p4;
wire   [1:0] trunc_ln318_7_fu_1871_p3;
wire   [18:0] x_l_I_43_fu_1841_p3;
wire   [18:0] zext_ln318_7_fu_1878_p1;
wire   [16:0] mul_FH_6_fu_1862_p4;
wire   [0:0] icmp_ln318_23_fu_1894_p2;
wire   [0:0] icmp_ln318_22_fu_1888_p2;
wire   [0:0] xor_ln318_6_fu_1899_p2;
wire   [0:0] icmp_ln331_7_fu_1911_p2;
wire   [18:0] x_l_I_44_fu_1916_p2;
wire   [18:0] x_l_I_45_fu_1922_p3;
wire   [0:0] icmp_ln318_21_fu_1882_p2;
wire   [0:0] and_ln318_7_fu_1905_p2;
wire   [18:0] x_l_I_46_fu_1930_p2;
wire   [16:0] x_l_FH_15_fu_1936_p2;
wire   [16:0] res_FH_13_fu_1962_p4;
wire   [16:0] res_FH_14_fu_1971_p3;
wire   [8:0] tmp_50_fu_1977_p4;
wire   [16:0] mul_FH_7_fu_1987_p3;
wire   [0:0] icmp_ln318_24_fu_1994_p2;
wire   [0:0] icmp_ln318_25_fu_1999_p2;
wire   [18:0] x_l_I_48_fu_2010_p2;
wire   [16:0] xor_ln335_fu_2022_p2;
wire   [0:0] or_ln318_fu_2004_p2;
wire   [18:0] x_l_I_49_fu_2015_p3;
wire   [16:0] x_l_FH_17_fu_2028_p2;
wire   [16:0] res_FH_15_fu_2033_p4;
wire   [1:0] tmp_29_fu_2074_p4;
wire   [16:0] mul_FH_8_fu_2108_p4;
wire   [0:0] icmp_ln318_29_fu_2131_p2;
wire   [0:0] icmp_ln318_28_fu_2126_p2;
wire   [0:0] xor_ln318_7_fu_2135_p2;
wire   [0:0] icmp_ln331_8_fu_2147_p2;
wire   [0:0] and_ln331_fu_2152_p2;
wire   [0:0] or_ln331_fu_2157_p2;
wire   [18:0] x_l_I_51_fu_2163_p2;
wire   [16:0] p_neg152_fu_2175_p3;
wire   [16:0] sub_ln335_fu_2182_p2;
wire   [0:0] icmp_ln318_27_fu_2121_p2;
wire   [0:0] and_ln318_8_fu_2141_p2;
wire   [0:0] or_ln318_9_fu_2206_p2;
wire   [0:0] icmp_ln318_26_fu_2116_p2;
wire   [0:0] or_ln318_10_fu_2212_p2;
wire   [18:0] x_l_I_52_fu_2168_p3;
wire   [16:0] x_l_FH_19_fu_2188_p2;
wire   [16:0] x_l_FL_fu_2193_p2;
wire   [16:0] res_FH_17_fu_2197_p4;
wire   [3:0] tmp_31_fu_2247_p4;
wire   [15:0] mul_FH_9_fu_2289_p4;
wire   [16:0] zext_ln308_fu_2297_p1;
wire   [0:0] icmp_ln318_33_fu_2316_p2;
wire   [0:0] icmp_ln318_32_fu_2311_p2;
wire   [0:0] xor_ln318_8_fu_2320_p2;
wire   [0:0] icmp_ln331_9_fu_2332_p2;
wire   [0:0] and_ln331_1_fu_2337_p2;
wire   [0:0] or_ln331_1_fu_2342_p2;
wire   [18:0] x_l_I_54_fu_2348_p2;
wire   [16:0] sub_ln335_1_fu_2360_p2;
wire   [0:0] icmp_ln318_31_fu_2306_p2;
wire   [0:0] and_ln318_9_fu_2326_p2;
wire   [0:0] or_ln318_11_fu_2383_p2;
wire   [0:0] icmp_ln318_30_fu_2301_p2;
wire   [0:0] or_ln318_12_fu_2389_p2;
wire   [18:0] x_l_I_55_fu_2353_p3;
wire   [16:0] x_l_FH_21_fu_2365_p2;
wire   [16:0] x_l_FL_3_fu_2370_p2;
wire   [16:0] res_FH_19_fu_2374_p4;
wire   [5:0] tmp_45_fu_2434_p4;
wire   [5:0] tmp_37_fu_2424_p4;
wire   [16:0] zext_ln308_1_fu_2453_p1;
wire   [0:0] xor_ln318_9_fu_2504_p2;
wire   [0:0] and_ln331_2_fu_2514_p2;
wire   [0:0] or_ln331_2_fu_2518_p2;
wire   [18:0] x_l_I_57_fu_2523_p2;
wire   [15:0] select_ln235_fu_2535_p3;
wire   [15:0] zext_ln308_2_fu_2501_p1;
wire   [15:0] sub_ln335_2_fu_2542_p2;
wire  signed [16:0] sext_ln342_fu_2548_p1;
wire   [0:0] and_ln318_10_fu_2509_p2;
wire   [0:0] or_ln318_13_fu_2570_p2;
wire   [0:0] or_ln318_14_fu_2575_p2;
wire   [18:0] x_l_I_58_fu_2528_p3;
wire   [16:0] x_l_FH_23_fu_2552_p2;
wire   [16:0] x_l_FL_5_fu_2557_p2;
wire   [16:0] res_FH_21_fu_2561_p4;
wire   [4:0] tmp_46_fu_2619_p4;
wire   [13:0] mul_FH_10_fu_2629_p4;
wire   [7:0] tmp_38_fu_2609_p4;
wire   [16:0] zext_ln308_3_fu_2638_p1;
wire   [14:0] select_ln235_1_fu_2690_p3;
wire   [14:0] zext_ln308_4_fu_2642_p1;
wire   [0:0] xor_ln318_10_fu_2704_p2;
wire   [0:0] and_ln331_3_fu_2714_p2;
wire   [0:0] or_ln331_3_fu_2718_p2;
wire   [18:0] x_l_I_60_fu_2723_p2;
wire  signed [16:0] sext_ln342_1_fu_2735_p1;
wire   [0:0] and_ln318_11_fu_2709_p2;
wire   [0:0] or_ln318_15_fu_2756_p2;
wire   [0:0] or_ln318_16_fu_2761_p2;
wire   [18:0] x_l_I_61_fu_2728_p3;
wire   [16:0] x_l_FH_25_fu_2738_p2;
wire   [16:0] x_l_FL_7_fu_2743_p2;
wire   [16:0] res_FH_23_fu_2747_p4;
wire   [16:0] res_FH_24_fu_2788_p3;
wire   [3:0] tmp_47_fu_2805_p4;
wire   [12:0] mul_FH_11_fu_2815_p4;
wire   [9:0] tmp_39_fu_2795_p4;
wire   [18:0] x_l_I_62_fu_2766_p3;
wire   [16:0] zext_ln308_5_fu_2824_p1;
wire   [16:0] x_l_FL_19_fu_2781_p3;
wire   [16:0] mul_FL_4_fu_2832_p3;
wire   [0:0] icmp_ln318_45_fu_2858_p2;
wire   [0:0] icmp_ln318_44_fu_2852_p2;
wire   [0:0] xor_ln318_11_fu_2864_p2;
wire   [0:0] delta_4_fu_2876_p2;
wire   [0:0] icmp_ln331_12_fu_2882_p2;
wire   [0:0] and_ln331_4_fu_2888_p2;
wire   [0:0] or_ln331_4_fu_2894_p2;
wire   [18:0] x_l_I_63_fu_2900_p2;
wire   [13:0] select_ln235_2_fu_2914_p3;
wire   [13:0] zext_ln308_6_fu_2828_p1;
wire   [0:0] icmp_ln318_43_fu_2846_p2;
wire   [0:0] and_ln318_12_fu_2870_p2;
wire   [0:0] or_ln318_17_fu_2944_p2;
wire   [0:0] icmp_ln318_42_fu_2840_p2;
wire   [18:0] x_l_I_64_fu_2906_p3;
wire   [16:0] x_l_FL_9_fu_2928_p2;
wire   [16:0] res_FH_25_fu_2934_p4;
wire  signed [16:0] sext_ln342_2_fu_3000_p1;
wire   [16:0] x_l_FH_27_fu_3003_p2;
wire   [11:0] mul_FH_12_fu_3014_p4;
wire   [16:0] x_l_FH_47_fu_3008_p3;
wire   [16:0] zext_ln308_7_fu_3022_p1;
wire   [16:0] mul_FL_5_fu_3030_p3;
wire   [0:0] icmp_ln318_49_fu_3054_p2;
wire   [0:0] icmp_ln318_48_fu_3048_p2;
wire   [0:0] xor_ln318_12_fu_3059_p2;
wire   [0:0] delta_5_fu_3071_p2;
wire   [0:0] icmp_ln331_13_fu_3076_p2;
wire   [0:0] and_ln331_5_fu_3082_p2;
wire   [0:0] or_ln331_5_fu_3088_p2;
wire   [18:0] x_l_I_66_fu_3094_p2;
wire   [12:0] select_ln235_3_fu_3106_p3;
wire   [12:0] zext_ln308_8_fu_3026_p1;
wire   [12:0] sub_ln335_5_fu_3114_p2;
wire  signed [16:0] sext_ln342_3_fu_3120_p1;
wire   [0:0] icmp_ln318_47_fu_3042_p2;
wire   [0:0] and_ln318_13_fu_3065_p2;
wire   [0:0] or_ln318_19_fu_3144_p2;
wire   [0:0] icmp_ln318_46_fu_3037_p2;
wire   [0:0] or_ln318_20_fu_3150_p2;
wire   [18:0] x_l_I_67_fu_3099_p3;
wire   [16:0] x_l_FH_29_fu_3124_p2;
wire   [16:0] x_l_FL_11_fu_3130_p2;
wire   [16:0] res_FH_27_fu_3135_p4;
wire   [10:0] mul_FH_13_fu_3206_p4;
wire   [16:0] zext_ln308_9_fu_3214_p1;
wire   [16:0] mul_FL_6_fu_3222_p3;
wire   [0:0] icmp_ln318_53_fu_3244_p2;
wire   [0:0] icmp_ln318_52_fu_3239_p2;
wire   [0:0] xor_ln318_13_fu_3249_p2;
wire   [0:0] delta_6_fu_3261_p2;
wire   [0:0] icmp_ln331_14_fu_3266_p2;
wire   [0:0] and_ln331_6_fu_3271_p2;
wire   [0:0] or_ln331_6_fu_3277_p2;
wire   [18:0] x_l_I_69_fu_3283_p2;
wire   [11:0] select_ln235_4_fu_3295_p3;
wire   [11:0] zext_ln308_10_fu_3218_p1;
wire   [11:0] sub_ln335_6_fu_3303_p2;
wire  signed [16:0] sext_ln342_4_fu_3309_p1;
wire   [0:0] icmp_ln318_51_fu_3234_p2;
wire   [0:0] and_ln318_14_fu_3255_p2;
wire   [0:0] or_ln318_21_fu_3332_p2;
wire   [0:0] icmp_ln318_50_fu_3229_p2;
wire   [16:0] x_l_FH_31_fu_3313_p2;
wire   [16:0] x_l_FL_13_fu_3318_p2;
wire   [16:0] res_FH_29_fu_3323_p4;
wire   [15:0] trunc_ln306_7_fu_3365_p1;
wire   [18:0] x_l_I_70_fu_3288_p3;
wire   [16:0] x_l_FL_14_fu_3351_p3;
wire   [16:0] mul_FL_7_fu_3369_p3;
wire   [9:0] mul_FH_14_fu_3404_p4;
wire   [16:0] zext_ln308_11_fu_3412_p1;
wire   [0:0] icmp_ln318_56_fu_3425_p2;
wire   [0:0] xor_ln318_14_fu_3430_p2;
wire   [0:0] icmp_ln318_55_fu_3420_p2;
wire   [0:0] and_ln318_15_fu_3435_p2;
wire   [0:0] or_ln318_23_fu_3450_p2;
wire   [0:0] and_ln318_16_fu_3416_p2;
wire   [0:0] or_ln318_24_fu_3456_p2;
wire   [16:0] res_FH_31_fu_3441_p4;
wire   [16:0] res_FH_32_fu_3462_p3;
wire   [17:0] zext_ln361_fu_3469_p1;
wire   [17:0] res_FH_l_fu_3473_p2;
wire   [0:0] tmp_62_fu_3485_p3;
wire   [7:0] res_I_15_fu_3493_p2;
wire   [16:0] res_FH_33_fu_3479_p2;
wire   [7:0] res_I_16_fu_3498_p3;
wire   [15:0] tmp_51_fu_3505_p4;
wire   [0:0] tmp_2_fu_3397_p3;
wire   [23:0] trunc_ln4_fu_3515_p3;
reg   [31:0] x_val_int_reg;
wire    ap_ce_reg;

always @ (posedge ap_clk) begin
    x_val_int_reg <= x_val;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        delta_1_reg_4020 <= delta_1_fu_2275_p2;
        delta_2_reg_4085 <= delta_2_fu_2489_p2;
        delta_3_reg_4146 <= delta_3_fu_2678_p2;
        delta_reg_3974 <= delta_fu_2102_p2;
        icmp_ln281_1_reg_3553 <= icmp_ln281_1_fu_396_p2;
        icmp_ln281_3_reg_3586 <= icmp_ln281_3_fu_585_p2;
        icmp_ln281_5_reg_3609 <= icmp_ln281_5_fu_742_p2;
        icmp_ln281_7_reg_3626 <= icmp_ln281_7_fu_883_p2;
        icmp_ln318_15_reg_3854 <= icmp_ln318_15_fu_1637_p2;
        icmp_ln318_16_reg_3859 <= icmp_ln318_16_fu_1643_p2;
        icmp_ln318_17_reg_3864 <= icmp_ln318_17_fu_1649_p2;
        icmp_ln318_2_reg_3564 <= icmp_ln318_2_fu_418_p2;
        icmp_ln318_2_reg_3564_pp0_iter1_reg <= icmp_ln318_2_reg_3564;
        icmp_ln318_2_reg_3564_pp0_iter2_reg <= icmp_ln318_2_reg_3564_pp0_iter1_reg;
        icmp_ln318_2_reg_3564_pp0_iter3_reg <= icmp_ln318_2_reg_3564_pp0_iter2_reg;
        icmp_ln318_34_reg_4064 <= icmp_ln318_34_fu_2465_p2;
        icmp_ln318_35_reg_4069 <= icmp_ln318_35_fu_2471_p2;
        icmp_ln318_36_reg_4074 <= icmp_ln318_36_fu_2477_p2;
        icmp_ln318_37_reg_4080 <= icmp_ln318_37_fu_2483_p2;
        icmp_ln318_38_reg_4125 <= icmp_ln318_38_fu_2654_p2;
        icmp_ln318_39_reg_4130 <= icmp_ln318_39_fu_2660_p2;
        icmp_ln318_3_reg_3683 <= icmp_ln318_3_fu_1062_p2;
        icmp_ln318_40_reg_4135 <= icmp_ln318_40_fu_2666_p2;
        icmp_ln318_41_reg_4141 <= icmp_ln318_41_fu_2672_p2;
        icmp_ln318_4_reg_3688 <= icmp_ln318_4_fu_1068_p2;
        icmp_ln318_54_reg_4270 <= icmp_ln318_54_fu_3385_p2;
        icmp_ln318_57_reg_4275 <= icmp_ln318_57_fu_3391_p2;
        icmp_ln318_5_reg_3693 <= icmp_ln318_5_fu_1074_p2;
        icmp_ln331_10_reg_4091 <= icmp_ln331_10_fu_2495_p2;
        icmp_ln331_11_reg_4151 <= icmp_ln331_11_fu_2684_p2;
        icmp_ln331_1_reg_3698 <= icmp_ln331_1_fu_1080_p2;
        icmp_ln331_5_reg_3869 <= icmp_ln331_5_fu_1655_p2;
        icmp_ln331_reg_3569 <= icmp_ln331_fu_434_p2;
        icmp_ln331_reg_3569_pp0_iter1_reg <= icmp_ln331_reg_3569;
        icmp_ln331_reg_3569_pp0_iter2_reg <= icmp_ln331_reg_3569_pp0_iter1_reg;
        icmp_ln331_reg_3569_pp0_iter3_reg <= icmp_ln331_reg_3569_pp0_iter2_reg;
        mul_FH_4_reg_3844[16 : 6] <= mul_FH_4_fu_1617_p4[16 : 6];
        mul_FH_reg_3673[16 : 15] <= mul_FH_fu_1030_p4[16 : 15];
        mul_FH_s_reg_4054[13 : 0] <= mul_FH_s_fu_2444_p4[13 : 0];
        mul_FL_1_reg_4014[16 : 13] <= mul_FL_1_fu_2267_p3[16 : 13];
        mul_FL_2_reg_4059[16 : 11] <= mul_FL_2_fu_2457_p3[16 : 11];
        mul_FL_3_reg_4120[16 : 9] <= mul_FL_3_fu_2646_p3[16 : 9];
        mul_FL_reg_3968[16 : 15] <= mul_FL_fu_2094_p3[16 : 15];
        or_ln318_18_reg_4172 <= or_ln318_18_fu_2950_p2;
        or_ln318_22_reg_4248 <= or_ln318_22_fu_3338_p2;
        or_ln318_3_reg_3784 <= or_ln318_3_fu_1325_p2;
        or_ln318_7_reg_3895 <= or_ln318_7_fu_1818_p2;
        or_ln318_8_reg_3915 <= or_ln318_8_fu_1941_p2;
        p_neg153_reg_4025 <= p_neg153_fu_2281_p3;
        res_FH_10_reg_3884 <= res_FH_10_fu_1719_p3;
        res_FH_12_reg_3909 <= res_FH_12_fu_1846_p3;
        res_FH_16_reg_3957 <= res_FH_16_fu_2066_p3;
        res_FH_18_reg_4003 <= res_FH_18_fu_2240_p3;
        res_FH_20_reg_4048 <= res_FH_20_fu_2417_p3;
        res_FH_22_reg_4114 <= res_FH_22_fu_2602_p3;
        res_FH_26_reg_4192 <= res_FH_26_fu_2972_p3;
        res_FH_28_reg_4232 <= res_FH_28_fu_3179_p3;
        res_FH_2_reg_3773 <= res_FH_2_fu_1226_p3;
        res_FH_30_reg_4259 <= res_FH_30_fu_3358_p3;
        res_FH_6_reg_3815 <= res_FH_6_fu_1479_p3;
        res_FH_8_reg_3838 <= res_FH_8_fu_1600_p3;
        res_FH_reg_3667[16] <= res_FH_fu_1008_p3[16];
        res_I_12_reg_3620 <= res_I_12_fu_859_p3;
        res_I_14_reg_3640 <= res_I_14_fu_931_p3;
        res_I_14_reg_3640_pp0_iter10_reg <= res_I_14_reg_3640_pp0_iter9_reg;
        res_I_14_reg_3640_pp0_iter11_reg <= res_I_14_reg_3640_pp0_iter10_reg;
        res_I_14_reg_3640_pp0_iter12_reg <= res_I_14_reg_3640_pp0_iter11_reg;
        res_I_14_reg_3640_pp0_iter13_reg <= res_I_14_reg_3640_pp0_iter12_reg;
        res_I_14_reg_3640_pp0_iter14_reg <= res_I_14_reg_3640_pp0_iter13_reg;
        res_I_14_reg_3640_pp0_iter15_reg <= res_I_14_reg_3640_pp0_iter14_reg;
        res_I_14_reg_3640_pp0_iter16_reg <= res_I_14_reg_3640_pp0_iter15_reg;
        res_I_14_reg_3640_pp0_iter5_reg <= res_I_14_reg_3640;
        res_I_14_reg_3640_pp0_iter6_reg <= res_I_14_reg_3640_pp0_iter5_reg;
        res_I_14_reg_3640_pp0_iter7_reg <= res_I_14_reg_3640_pp0_iter6_reg;
        res_I_14_reg_3640_pp0_iter8_reg <= res_I_14_reg_3640_pp0_iter7_reg;
        res_I_14_reg_3640_pp0_iter9_reg <= res_I_14_reg_3640_pp0_iter8_reg;
        res_I_4_reg_3580 <= res_I_4_fu_545_p3;
        res_I_8_reg_3603 <= res_I_8_fu_702_p3;
        res_I_reg_3547[7] <= res_I_fu_356_p3[7];
        sub_ln286_2_reg_3592 <= sub_ln286_2_fu_591_p2;
        sub_ln286_4_reg_3615 <= sub_ln286_4_fu_748_p2;
        sub_ln286_reg_3559 <= sub_ln286_fu_402_p2;
        sub_ln335_3_reg_4156 <= sub_ln335_3_fu_2698_p2;
        sub_ln335_4_reg_4167 <= sub_ln335_4_fu_2922_p2;
        tmp_25_reg_3713 <= {{res_I_14_fu_931_p3[7:2]}};
        tmp_27_reg_3723 <= {{res_I_14_fu_931_p3[7:3]}};
        tmp_27_reg_3723_pp0_iter5_reg <= tmp_27_reg_3723;
        tmp_28_reg_3821 <= {{res_FH_6_fu_1479_p3[16:12]}};
        tmp_30_reg_3733 <= {{res_I_14_fu_931_p3[7:4]}};
        tmp_30_reg_3733_pp0_iter5_reg <= tmp_30_reg_3733;
        tmp_30_reg_3733_pp0_iter6_reg <= tmp_30_reg_3733_pp0_iter5_reg;
        tmp_33_reg_3743 <= {{res_I_14_fu_931_p3[7:5]}};
        tmp_33_reg_3743_pp0_iter5_reg <= tmp_33_reg_3743;
        tmp_33_reg_3743_pp0_iter6_reg <= tmp_33_reg_3743_pp0_iter5_reg;
        tmp_35_reg_3753 <= {{res_I_14_fu_931_p3[7:6]}};
        tmp_35_reg_3753_pp0_iter5_reg <= tmp_35_reg_3753;
        tmp_35_reg_3753_pp0_iter6_reg <= tmp_35_reg_3753_pp0_iter5_reg;
        tmp_35_reg_3753_pp0_iter7_reg <= tmp_35_reg_3753_pp0_iter6_reg;
        tmp_40_reg_4198 <= {{res_FH_26_fu_2972_p3[13:2]}};
        tmp_41_reg_4238 <= {{res_FH_28_fu_3179_p3[14:1]}};
        tmp_42_reg_3763 <= res_I_14_fu_931_p3[32'd7];
        tmp_42_reg_3763_pp0_iter5_reg <= tmp_42_reg_3763;
        tmp_42_reg_3763_pp0_iter6_reg <= tmp_42_reg_3763_pp0_iter5_reg;
        tmp_42_reg_3763_pp0_iter7_reg <= tmp_42_reg_3763_pp0_iter6_reg;
        tmp_42_reg_3763_pp0_iter8_reg <= tmp_42_reg_3763_pp0_iter7_reg;
        tmp_43_reg_3963 <= {{res_FH_16_fu_2066_p3[16:9]}};
        tmp_44_reg_4009 <= {{res_FH_18_fu_2240_p3[16:10]}};
        tmp_48_reg_4203 <= {{res_FH_26_fu_2972_p3[16:14]}};
        tmp_49_reg_4243 <= {{res_FH_28_fu_3179_p3[16:15]}};
        tmp_60_reg_4265 <= res_FH_30_fu_3358_p3[32'd16];
        trunc_ln236_reg_3536 <= trunc_ln236_fu_306_p1;
        trunc_ln236_reg_3536_pp0_iter1_reg <= trunc_ln236_reg_3536;
        trunc_ln236_reg_3536_pp0_iter2_reg <= trunc_ln236_reg_3536_pp0_iter1_reg;
        trunc_ln236_reg_3536_pp0_iter3_reg <= trunc_ln236_reg_3536_pp0_iter2_reg;
        trunc_ln306_1_reg_3708 <= trunc_ln306_1_fu_1092_p1;
        trunc_ln306_2_reg_3718 <= trunc_ln306_2_fu_1106_p1;
        trunc_ln306_2_reg_3718_pp0_iter5_reg <= trunc_ln306_2_reg_3718;
        trunc_ln306_3_reg_3728 <= trunc_ln306_3_fu_1120_p1;
        trunc_ln306_3_reg_3728_pp0_iter5_reg <= trunc_ln306_3_reg_3728;
        trunc_ln306_3_reg_3728_pp0_iter6_reg <= trunc_ln306_3_reg_3728_pp0_iter5_reg;
        trunc_ln306_4_reg_3738 <= trunc_ln306_4_fu_1134_p1;
        trunc_ln306_4_reg_3738_pp0_iter5_reg <= trunc_ln306_4_reg_3738;
        trunc_ln306_4_reg_3738_pp0_iter6_reg <= trunc_ln306_4_reg_3738_pp0_iter5_reg;
        trunc_ln306_5_reg_3748 <= trunc_ln306_5_fu_1148_p1;
        trunc_ln306_5_reg_3748_pp0_iter5_reg <= trunc_ln306_5_reg_3748;
        trunc_ln306_5_reg_3748_pp0_iter6_reg <= trunc_ln306_5_reg_3748_pp0_iter5_reg;
        trunc_ln306_5_reg_3748_pp0_iter7_reg <= trunc_ln306_5_reg_3748_pp0_iter6_reg;
        trunc_ln306_6_reg_3758 <= trunc_ln306_6_fu_1162_p1;
        trunc_ln306_6_reg_3758_pp0_iter5_reg <= trunc_ln306_6_reg_3758;
        trunc_ln306_6_reg_3758_pp0_iter6_reg <= trunc_ln306_6_reg_3758_pp0_iter5_reg;
        trunc_ln306_6_reg_3758_pp0_iter7_reg <= trunc_ln306_6_reg_3758_pp0_iter6_reg;
        trunc_ln306_6_reg_3758_pp0_iter8_reg <= trunc_ln306_6_reg_3758_pp0_iter7_reg;
        x_l_FH_32_reg_4253 <= x_l_FH_32_fu_3344_p3;
        x_l_FH_34_reg_3661[16 : 1] <= x_l_FH_34_fu_1000_p3[16 : 1];
        x_l_FH_36_reg_3790[16 : 1] <= x_l_FH_36_fu_1331_p3[16 : 1];
        x_l_FH_37_reg_3807[16 : 1] <= x_l_FH_37_fu_1472_p3[16 : 1];
        x_l_FH_38_reg_3832[16 : 1] <= x_l_FH_38_fu_1593_p3[16 : 1];
        x_l_FH_40_reg_3901[16 : 1] <= x_l_FH_40_fu_1824_p3[16 : 1];
        x_l_FH_41_reg_3927[16 : 1] <= x_l_FH_41_fu_1955_p3[16 : 1];
        x_l_FH_42_reg_3941 <= x_l_FH_42_fu_2051_p3;
        x_l_FH_43_reg_3987 <= x_l_FH_43_fu_2226_p3;
        x_l_FH_44_reg_4036 <= x_l_FH_44_fu_2403_p3;
        x_l_FH_45_reg_4102 <= x_l_FH_45_fu_2588_p3;
        x_l_FH_46_reg_4161 <= x_l_FH_46_fu_2774_p3;
        x_l_FH_48_reg_4215 <= x_l_FH_48_fu_3164_p3;
        x_l_FL_15_reg_3950[16] <= x_l_FL_15_fu_2058_p3[16];
        x_l_FL_16_reg_3996[16 : 14] <= x_l_FL_16_fu_2233_p3[16 : 14];
        x_l_FL_17_reg_4042[16 : 12] <= x_l_FL_17_fu_2410_p3[16 : 12];
        x_l_FL_18_reg_4108[16 : 10] <= x_l_FL_18_fu_2595_p3[16 : 10];
        x_l_FL_20_reg_4184[16 : 6] <= x_l_FL_20_fu_2964_p3[16 : 6];
        x_l_FL_21_reg_4224[16 : 4] <= x_l_FL_21_fu_3172_p3[16 : 4];
        x_l_I_15_reg_3631 <= x_l_I_15_fu_907_p3;
        x_l_I_19_reg_3655 <= x_l_I_19_fu_993_p3;
        x_l_I_1_reg_3541 <= x_l_I_1_fu_348_p3;
        x_l_I_20_reg_3703 <= x_l_I_20_fu_1086_p2;
        x_l_I_23_reg_3768 <= x_l_I_23_fu_1212_p3;
        x_l_I_26_reg_3779 <= x_l_I_26_fu_1313_p2;
        x_l_I_31_reg_3798 <= x_l_I_31_fu_1464_p3;
        x_l_I_35_reg_3826 <= x_l_I_35_fu_1586_p3;
        x_l_I_36_reg_3874 <= x_l_I_36_fu_1661_p2;
        x_l_I_39_reg_3879 <= x_l_I_39_fu_1705_p3;
        x_l_I_42_reg_3890 <= x_l_I_42_fu_1806_p2;
        x_l_I_47_reg_3920 <= x_l_I_47_fu_1947_p3;
        x_l_I_50_reg_3934 <= x_l_I_50_fu_2043_p3;
        x_l_I_53_reg_3980 <= x_l_I_53_fu_2218_p3;
        x_l_I_56_reg_4030 <= x_l_I_56_fu_2395_p3;
        x_l_I_59_reg_4096 <= x_l_I_59_fu_2580_p3;
        x_l_I_5_reg_3574 <= x_l_I_5_fu_537_p3;
        x_l_I_65_reg_4177 <= x_l_I_65_fu_2956_p3;
        x_l_I_68_reg_4208 <= x_l_I_68_fu_3156_p3;
        x_l_I_9_reg_3597 <= x_l_I_9_fu_694_p3;
        x_val_read_reg_3531 <= x_val_int_reg;
        x_val_read_reg_3531_pp0_iter10_reg <= x_val_read_reg_3531_pp0_iter9_reg;
        x_val_read_reg_3531_pp0_iter11_reg <= x_val_read_reg_3531_pp0_iter10_reg;
        x_val_read_reg_3531_pp0_iter12_reg <= x_val_read_reg_3531_pp0_iter11_reg;
        x_val_read_reg_3531_pp0_iter13_reg <= x_val_read_reg_3531_pp0_iter12_reg;
        x_val_read_reg_3531_pp0_iter14_reg <= x_val_read_reg_3531_pp0_iter13_reg;
        x_val_read_reg_3531_pp0_iter15_reg <= x_val_read_reg_3531_pp0_iter14_reg;
        x_val_read_reg_3531_pp0_iter16_reg <= x_val_read_reg_3531_pp0_iter15_reg;
        x_val_read_reg_3531_pp0_iter1_reg <= x_val_read_reg_3531;
        x_val_read_reg_3531_pp0_iter2_reg <= x_val_read_reg_3531_pp0_iter1_reg;
        x_val_read_reg_3531_pp0_iter3_reg <= x_val_read_reg_3531_pp0_iter2_reg;
        x_val_read_reg_3531_pp0_iter4_reg <= x_val_read_reg_3531_pp0_iter3_reg;
        x_val_read_reg_3531_pp0_iter5_reg <= x_val_read_reg_3531_pp0_iter4_reg;
        x_val_read_reg_3531_pp0_iter6_reg <= x_val_read_reg_3531_pp0_iter5_reg;
        x_val_read_reg_3531_pp0_iter7_reg <= x_val_read_reg_3531_pp0_iter6_reg;
        x_val_read_reg_3531_pp0_iter8_reg <= x_val_read_reg_3531_pp0_iter7_reg;
        x_val_read_reg_3531_pp0_iter9_reg <= x_val_read_reg_3531_pp0_iter8_reg;
        zext_ln318_1_reg_3678[6 : 0] <= zext_ln318_1_fu_1058_p1[6 : 0];
        zext_ln318_5_reg_3849[2 : 0] <= zext_ln318_5_fu_1633_p1[2 : 0];
    end
end

assign add_ln286_fu_330_p2 = ($signed(zext_ln281_fu_320_p1) + $signed(3'd7));

assign and_ln318_10_fu_2509_p2 = (xor_ln318_9_fu_2504_p2 & icmp_ln318_36_reg_4074);

assign and_ln318_11_fu_2709_p2 = (xor_ln318_10_fu_2704_p2 & icmp_ln318_40_reg_4135);

assign and_ln318_12_fu_2870_p2 = (xor_ln318_11_fu_2864_p2 & icmp_ln318_44_fu_2852_p2);

assign and_ln318_13_fu_3065_p2 = (xor_ln318_12_fu_3059_p2 & icmp_ln318_48_fu_3048_p2);

assign and_ln318_14_fu_3255_p2 = (xor_ln318_13_fu_3249_p2 & icmp_ln318_52_fu_3239_p2);

assign and_ln318_15_fu_3435_p2 = (xor_ln318_14_fu_3430_p2 & icmp_ln318_56_fu_3425_p2);

assign and_ln318_16_fu_3416_p2 = (or_ln318_22_reg_4248 & icmp_ln318_54_reg_4270);

assign and_ln318_1_fu_1179_p2 = (xor_ln318_fu_1174_p2 & icmp_ln318_4_reg_3688);

assign and_ln318_2_fu_1287_p2 = (xor_ln318_1_fu_1281_p2 & icmp_ln318_7_fu_1269_p2);

assign and_ln318_3_fu_1412_p2 = (xor_ln318_2_fu_1406_p2 & icmp_ln318_10_fu_1395_p2);

assign and_ln318_4_fu_1537_p2 = (xor_ln318_3_fu_1531_p2 & icmp_ln318_13_fu_1521_p2);

assign and_ln318_5_fu_1672_p2 = (xor_ln318_4_fu_1667_p2 & icmp_ln318_16_reg_3859);

assign and_ln318_6_fu_1780_p2 = (xor_ln318_5_fu_1774_p2 & icmp_ln318_19_fu_1762_p2);

assign and_ln318_7_fu_1905_p2 = (xor_ln318_6_fu_1899_p2 & icmp_ln318_22_fu_1888_p2);

assign and_ln318_8_fu_2141_p2 = (xor_ln318_7_fu_2135_p2 & icmp_ln318_28_fu_2126_p2);

assign and_ln318_9_fu_2326_p2 = (xor_ln318_8_fu_2320_p2 & icmp_ln318_32_fu_2311_p2);

assign and_ln318_fu_959_p2 = (icmp_ln318_2_reg_3564_pp0_iter3_reg & icmp_ln318_1_fu_954_p2);

assign and_ln331_1_fu_2337_p2 = (icmp_ln318_32_fu_2311_p2 & delta_1_reg_4020);

assign and_ln331_2_fu_2514_p2 = (icmp_ln318_36_reg_4074 & delta_2_reg_4085);

assign and_ln331_3_fu_2714_p2 = (icmp_ln318_40_reg_4135 & delta_3_reg_4146);

assign and_ln331_4_fu_2888_p2 = (icmp_ln318_44_fu_2852_p2 & delta_4_fu_2876_p2);

assign and_ln331_5_fu_3082_p2 = (icmp_ln318_48_fu_3048_p2 & delta_5_fu_3071_p2);

assign and_ln331_6_fu_3271_p2 = (icmp_ln318_52_fu_3239_p2 & delta_6_fu_3261_p2);

assign and_ln331_fu_2152_p2 = (icmp_ln318_28_fu_2126_p2 & delta_reg_3974);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_return = ((tmp_2_fu_3397_p3[0:0] == 1'b1) ? 24'd0 : trunc_ln4_fu_3515_p3);

assign delta_1_fu_2275_p2 = ((x_l_FL_16_fu_2233_p3 < mul_FL_1_fu_2267_p3) ? 1'b1 : 1'b0);

assign delta_2_fu_2489_p2 = ((x_l_FL_17_fu_2410_p3 < mul_FL_2_fu_2457_p3) ? 1'b1 : 1'b0);

assign delta_3_fu_2678_p2 = ((x_l_FL_18_fu_2595_p3 < mul_FL_3_fu_2646_p3) ? 1'b1 : 1'b0);

assign delta_4_fu_2876_p2 = ((x_l_FL_19_fu_2781_p3 < mul_FL_4_fu_2832_p3) ? 1'b1 : 1'b0);

assign delta_5_fu_3071_p2 = ((x_l_FL_20_reg_4184 < mul_FL_5_fu_3030_p3) ? 1'b1 : 1'b0);

assign delta_6_fu_3261_p2 = ((x_l_FL_21_reg_4224 < mul_FL_6_fu_3222_p3) ? 1'b1 : 1'b0);

assign delta_fu_2102_p2 = ((x_l_FL_15_fu_2058_p3 < mul_FL_fu_2094_p3) ? 1'b1 : 1'b0);

assign icmp_ln281_1_fu_396_p2 = ((tmp_3_fu_382_p4 < zext_ln281_1_fu_392_p1) ? 1'b1 : 1'b0);

assign icmp_ln281_2_fu_503_p2 = ((tmp_5_fu_489_p4 < zext_ln281_2_fu_499_p1) ? 1'b1 : 1'b0);

assign icmp_ln281_3_fu_585_p2 = ((tmp_9_fu_571_p4 < zext_ln281_3_fu_581_p1) ? 1'b1 : 1'b0);

assign icmp_ln281_4_fu_660_p2 = ((tmp_12_fu_646_p4 < zext_ln281_4_fu_656_p1) ? 1'b1 : 1'b0);

assign icmp_ln281_5_fu_742_p2 = ((tmp_15_fu_728_p4 < zext_ln281_5_fu_738_p1) ? 1'b1 : 1'b0);

assign icmp_ln281_6_fu_817_p2 = ((tmp_19_fu_803_p4 < zext_ln281_6_fu_813_p1) ? 1'b1 : 1'b0);

assign icmp_ln281_7_fu_883_p2 = ((trunc_ln281_fu_875_p1 < zext_ln281_7_fu_879_p1) ? 1'b1 : 1'b0);

assign icmp_ln281_fu_324_p2 = ((tmp_1_fu_310_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_10_fu_1395_p2 = ((x_l_I_27_fu_1348_p3 == zext_ln318_3_fu_1385_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_11_fu_1401_p2 = ((x_l_FH_36_reg_3790 < mul_FH_2_fu_1369_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_12_fu_1516_p2 = ((x_l_I_31_reg_3798 > zext_ln318_4_fu_1512_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_13_fu_1521_p2 = ((x_l_I_31_reg_3798 == zext_ln318_4_fu_1512_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_14_fu_1526_p2 = ((x_l_FH_37_reg_3807 < mul_FH_3_fu_1497_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_15_fu_1637_p2 = ((x_l_I_35_fu_1586_p3 > zext_ln318_5_fu_1633_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_16_fu_1643_p2 = ((x_l_I_35_fu_1586_p3 == zext_ln318_5_fu_1633_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_17_fu_1649_p2 = ((x_l_FH_38_fu_1593_p3 < mul_FH_4_fu_1617_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_18_fu_1756_p2 = ((x_l_I_39_fu_1705_p3 > zext_ln318_6_fu_1752_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_19_fu_1762_p2 = ((x_l_I_39_fu_1705_p3 == zext_ln318_6_fu_1752_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_1_fu_954_p2 = ((x_l_I_15_reg_3631 == zext_ln318_fu_945_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_20_fu_1768_p2 = ((x_l_FH_39_fu_1712_p3 < mul_FH_5_fu_1736_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_21_fu_1882_p2 = ((x_l_I_43_fu_1841_p3 > zext_ln318_7_fu_1878_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_22_fu_1888_p2 = ((x_l_I_43_fu_1841_p3 == zext_ln318_7_fu_1878_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_23_fu_1894_p2 = ((x_l_FH_40_reg_3901 < mul_FH_6_fu_1862_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_24_fu_1994_p2 = ((x_l_I_47_reg_3920 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_25_fu_1999_p2 = ((x_l_FH_41_reg_3927 > mul_FH_7_fu_1987_p3) ? 1'b1 : 1'b0);

assign icmp_ln318_26_fu_2116_p2 = ((x_l_I_50_reg_3934 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_27_fu_2121_p2 = ((x_l_FH_42_reg_3941 > mul_FH_8_fu_2108_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_28_fu_2126_p2 = ((x_l_FH_42_reg_3941 == mul_FH_8_fu_2108_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_29_fu_2131_p2 = ((x_l_FL_15_reg_3950 < mul_FL_reg_3968) ? 1'b1 : 1'b0);

assign icmp_ln318_2_fu_418_p2 = ((tmp_22_fu_408_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_30_fu_2301_p2 = ((x_l_I_53_reg_3980 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_31_fu_2306_p2 = ((x_l_FH_43_reg_3987 > zext_ln308_fu_2297_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_32_fu_2311_p2 = ((x_l_FH_43_reg_3987 == zext_ln308_fu_2297_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_33_fu_2316_p2 = ((x_l_FL_16_reg_3996 < mul_FL_1_reg_4014) ? 1'b1 : 1'b0);

assign icmp_ln318_34_fu_2465_p2 = ((x_l_I_56_fu_2395_p3 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_35_fu_2471_p2 = ((x_l_FH_44_fu_2403_p3 > zext_ln308_1_fu_2453_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_36_fu_2477_p2 = ((x_l_FH_44_fu_2403_p3 == zext_ln308_1_fu_2453_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_37_fu_2483_p2 = ((x_l_FL_17_fu_2410_p3 < mul_FL_2_fu_2457_p3) ? 1'b1 : 1'b0);

assign icmp_ln318_38_fu_2654_p2 = ((x_l_I_59_fu_2580_p3 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_39_fu_2660_p2 = ((x_l_FH_45_fu_2588_p3 > zext_ln308_3_fu_2638_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_3_fu_1062_p2 = ((x_l_I_19_fu_993_p3 > zext_ln318_1_fu_1058_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_40_fu_2666_p2 = ((x_l_FH_45_fu_2588_p3 == zext_ln308_3_fu_2638_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_41_fu_2672_p2 = ((x_l_FL_18_fu_2595_p3 < mul_FL_3_fu_2646_p3) ? 1'b1 : 1'b0);

assign icmp_ln318_42_fu_2840_p2 = ((x_l_I_62_fu_2766_p3 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_43_fu_2846_p2 = ((x_l_FH_46_fu_2774_p3 > zext_ln308_5_fu_2824_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_44_fu_2852_p2 = ((x_l_FH_46_fu_2774_p3 == zext_ln308_5_fu_2824_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_45_fu_2858_p2 = ((x_l_FL_19_fu_2781_p3 < mul_FL_4_fu_2832_p3) ? 1'b1 : 1'b0);

assign icmp_ln318_46_fu_3037_p2 = ((x_l_I_65_reg_4177 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_47_fu_3042_p2 = ((x_l_FH_47_fu_3008_p3 > zext_ln308_7_fu_3022_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_48_fu_3048_p2 = ((x_l_FH_47_fu_3008_p3 == zext_ln308_7_fu_3022_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_49_fu_3054_p2 = ((x_l_FL_20_reg_4184 < mul_FL_5_fu_3030_p3) ? 1'b1 : 1'b0);

assign icmp_ln318_4_fu_1068_p2 = ((x_l_I_19_fu_993_p3 == zext_ln318_1_fu_1058_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_50_fu_3229_p2 = ((x_l_I_68_reg_4208 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_51_fu_3234_p2 = ((x_l_FH_48_reg_4215 > zext_ln308_9_fu_3214_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_52_fu_3239_p2 = ((x_l_FH_48_reg_4215 == zext_ln308_9_fu_3214_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_53_fu_3244_p2 = ((x_l_FL_21_reg_4224 < mul_FL_6_fu_3222_p3) ? 1'b1 : 1'b0);

assign icmp_ln318_54_fu_3385_p2 = ((x_l_I_70_fu_3288_p3 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_55_fu_3420_p2 = ((x_l_FH_32_reg_4253 > zext_ln308_11_fu_3412_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_56_fu_3425_p2 = ((x_l_FH_32_reg_4253 == zext_ln308_11_fu_3412_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_57_fu_3391_p2 = ((x_l_FL_14_fu_3351_p3 < mul_FL_7_fu_3369_p3) ? 1'b1 : 1'b0);

assign icmp_ln318_5_fu_1074_p2 = ((x_l_FH_34_fu_1000_p3 < mul_FH_fu_1030_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_6_fu_1263_p2 = ((x_l_I_23_fu_1212_p3 > zext_ln318_2_fu_1259_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_7_fu_1269_p2 = ((x_l_I_23_fu_1212_p3 == zext_ln318_2_fu_1259_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_8_fu_1275_p2 = ((x_l_FH_35_fu_1219_p3 < mul_FH_1_fu_1243_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_9_fu_1389_p2 = ((x_l_I_27_fu_1348_p3 > zext_ln318_3_fu_1385_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_fu_949_p2 = ((x_l_I_15_reg_3631 > zext_ln318_fu_945_p1) ? 1'b1 : 1'b0);

assign icmp_ln331_10_fu_2495_p2 = ((x_l_FH_44_fu_2403_p3 < zext_ln308_1_fu_2453_p1) ? 1'b1 : 1'b0);

assign icmp_ln331_11_fu_2684_p2 = ((x_l_FH_45_fu_2588_p3 < zext_ln308_3_fu_2638_p1) ? 1'b1 : 1'b0);

assign icmp_ln331_12_fu_2882_p2 = ((x_l_FH_46_fu_2774_p3 < zext_ln308_5_fu_2824_p1) ? 1'b1 : 1'b0);

assign icmp_ln331_13_fu_3076_p2 = ((x_l_FH_47_fu_3008_p3 < zext_ln308_7_fu_3022_p1) ? 1'b1 : 1'b0);

assign icmp_ln331_14_fu_3266_p2 = ((x_l_FH_48_reg_4215 < zext_ln308_9_fu_3214_p1) ? 1'b1 : 1'b0);

assign icmp_ln331_1_fu_1080_p2 = ((x_l_FH_34_fu_1000_p3 < mul_FH_fu_1030_p4) ? 1'b1 : 1'b0);

assign icmp_ln331_2_fu_1293_p2 = ((x_l_FH_35_fu_1219_p3 < mul_FH_1_fu_1243_p4) ? 1'b1 : 1'b0);

assign icmp_ln331_3_fu_1418_p2 = ((x_l_FH_36_reg_3790 < mul_FH_2_fu_1369_p4) ? 1'b1 : 1'b0);

assign icmp_ln331_4_fu_1543_p2 = ((x_l_FH_37_reg_3807 < mul_FH_3_fu_1497_p4) ? 1'b1 : 1'b0);

assign icmp_ln331_5_fu_1655_p2 = ((x_l_FH_38_fu_1593_p3 < mul_FH_4_fu_1617_p4) ? 1'b1 : 1'b0);

assign icmp_ln331_6_fu_1786_p2 = ((x_l_FH_39_fu_1712_p3 < mul_FH_5_fu_1736_p4) ? 1'b1 : 1'b0);

assign icmp_ln331_7_fu_1911_p2 = ((x_l_FH_40_reg_3901 < mul_FH_6_fu_1862_p4) ? 1'b1 : 1'b0);

assign icmp_ln331_8_fu_2147_p2 = ((x_l_FH_42_reg_3941 < mul_FH_8_fu_2108_p4) ? 1'b1 : 1'b0);

assign icmp_ln331_9_fu_2332_p2 = ((x_l_FH_43_reg_3987 < zext_ln308_fu_2297_p1) ? 1'b1 : 1'b0);

assign icmp_ln331_fu_434_p2 = ((tmp_23_fu_424_p4 == 2'd0) ? 1'b1 : 1'b0);

assign mul_FH_10_fu_2629_p4 = {{{{1'd0}, {res_I_14_reg_3640_pp0_iter12_reg}}}, {tmp_46_fu_2619_p4}};

assign mul_FH_11_fu_2815_p4 = {{{{1'd0}, {res_I_14_reg_3640_pp0_iter13_reg}}}, {tmp_47_fu_2805_p4}};

assign mul_FH_12_fu_3014_p4 = {{{{1'd0}, {res_I_14_reg_3640_pp0_iter14_reg}}}, {tmp_48_reg_4203}};

assign mul_FH_13_fu_3206_p4 = {{{{1'd0}, {res_I_14_reg_3640_pp0_iter15_reg}}}, {tmp_49_reg_4243}};

assign mul_FH_14_fu_3404_p4 = {{{{1'd0}, {res_I_14_reg_3640_pp0_iter16_reg}}}, {tmp_60_reg_4265}};

assign mul_FH_1_fu_1243_p4 = {{{trunc_ln306_1_reg_3708}, {tmp_24_fu_1233_p4}}, {12'd2048}};

assign mul_FH_2_fu_1369_p4 = {{{trunc_ln306_2_reg_3718_pp0_iter5_reg}, {tmp_26_fu_1359_p4}}, {10'd512}};

assign mul_FH_3_fu_1497_p4 = {{{trunc_ln306_3_reg_3728_pp0_iter6_reg}, {tmp_28_reg_3821}}, {8'd128}};

assign mul_FH_4_fu_1617_p4 = {{{trunc_ln306_4_reg_3738_pp0_iter6_reg}, {tmp_32_fu_1607_p4}}, {6'd32}};

assign mul_FH_5_fu_1736_p4 = {{{trunc_ln306_5_reg_3748_pp0_iter7_reg}, {tmp_34_fu_1726_p4}}, {4'd8}};

assign mul_FH_6_fu_1862_p4 = {{{trunc_ln306_6_reg_3758_pp0_iter8_reg}, {tmp_36_fu_1852_p4}}, {2'd2}};

assign mul_FH_7_fu_1987_p3 = {{res_I_14_reg_3640_pp0_iter9_reg}, {tmp_50_fu_1977_p4}};

assign mul_FH_8_fu_2108_p4 = {{{{1'd0}, {res_I_14_reg_3640_pp0_iter10_reg}}}, {tmp_43_reg_3963}};

assign mul_FH_9_fu_2289_p4 = {{{{1'd0}, {res_I_14_reg_3640_pp0_iter11_reg}}}, {tmp_44_reg_4009}};

assign mul_FH_fu_1030_p4 = {{{trunc_ln306_fu_1026_p1}, {tmp_20_fu_1016_p4}}, {14'd8192}};

assign mul_FH_s_fu_2444_p4 = {{{{1'd0}, {res_I_14_reg_3640_pp0_iter11_reg}}}, {tmp_45_fu_2434_p4}};

assign mul_FL_1_fu_2267_p3 = {{tmp_31_fu_2247_p4}, {13'd4096}};

assign mul_FL_2_fu_2457_p3 = {{tmp_37_fu_2424_p4}, {11'd1024}};

assign mul_FL_3_fu_2646_p3 = {{tmp_38_fu_2609_p4}, {9'd256}};

assign mul_FL_4_fu_2832_p3 = {{tmp_39_fu_2795_p4}, {7'd64}};

assign mul_FL_5_fu_3030_p3 = {{tmp_40_reg_4198}, {5'd16}};

assign mul_FL_6_fu_3222_p3 = {{tmp_41_reg_4238}, {3'd4}};

assign mul_FL_7_fu_3369_p3 = {{trunc_ln306_7_fu_3365_p1}, {1'd1}};

assign mul_FL_fu_2094_p3 = {{tmp_29_fu_2074_p4}, {15'd16384}};

assign or_ln318_10_fu_2212_p2 = (or_ln318_9_fu_2206_p2 | icmp_ln318_26_fu_2116_p2);

assign or_ln318_11_fu_2383_p2 = (icmp_ln318_31_fu_2306_p2 | and_ln318_9_fu_2326_p2);

assign or_ln318_12_fu_2389_p2 = (or_ln318_11_fu_2383_p2 | icmp_ln318_30_fu_2301_p2);

assign or_ln318_13_fu_2570_p2 = (icmp_ln318_35_reg_4069 | and_ln318_10_fu_2509_p2);

assign or_ln318_14_fu_2575_p2 = (or_ln318_13_fu_2570_p2 | icmp_ln318_34_reg_4064);

assign or_ln318_15_fu_2756_p2 = (icmp_ln318_39_reg_4130 | and_ln318_11_fu_2709_p2);

assign or_ln318_16_fu_2761_p2 = (or_ln318_15_fu_2756_p2 | icmp_ln318_38_reg_4125);

assign or_ln318_17_fu_2944_p2 = (icmp_ln318_43_fu_2846_p2 | and_ln318_12_fu_2870_p2);

assign or_ln318_18_fu_2950_p2 = (or_ln318_17_fu_2944_p2 | icmp_ln318_42_fu_2840_p2);

assign or_ln318_19_fu_3144_p2 = (icmp_ln318_47_fu_3042_p2 | and_ln318_13_fu_3065_p2);

assign or_ln318_1_fu_987_p2 = (icmp_ln318_fu_949_p2 | and_ln318_fu_959_p2);

assign or_ln318_20_fu_3150_p2 = (or_ln318_19_fu_3144_p2 | icmp_ln318_46_fu_3037_p2);

assign or_ln318_21_fu_3332_p2 = (icmp_ln318_51_fu_3234_p2 | and_ln318_14_fu_3255_p2);

assign or_ln318_22_fu_3338_p2 = (or_ln318_21_fu_3332_p2 | icmp_ln318_50_fu_3229_p2);

assign or_ln318_23_fu_3450_p2 = (icmp_ln318_55_fu_3420_p2 | and_ln318_15_fu_3435_p2);

assign or_ln318_24_fu_3456_p2 = (or_ln318_23_fu_3450_p2 | and_ln318_16_fu_3416_p2);

assign or_ln318_2_fu_1207_p2 = (icmp_ln318_3_reg_3683 | and_ln318_1_fu_1179_p2);

assign or_ln318_3_fu_1325_p2 = (icmp_ln318_6_fu_1263_p2 | and_ln318_2_fu_1287_p2);

assign or_ln318_4_fu_1458_p2 = (icmp_ln318_9_fu_1389_p2 | and_ln318_3_fu_1412_p2);

assign or_ln318_5_fu_1580_p2 = (icmp_ln318_12_fu_1516_p2 | and_ln318_4_fu_1537_p2);

assign or_ln318_6_fu_1700_p2 = (icmp_ln318_15_reg_3854 | and_ln318_5_fu_1672_p2);

assign or_ln318_7_fu_1818_p2 = (icmp_ln318_18_fu_1756_p2 | and_ln318_6_fu_1780_p2);

assign or_ln318_8_fu_1941_p2 = (icmp_ln318_21_fu_1882_p2 | and_ln318_7_fu_1905_p2);

assign or_ln318_9_fu_2206_p2 = (icmp_ln318_27_fu_2121_p2 | and_ln318_8_fu_2141_p2);

assign or_ln318_fu_2004_p2 = (icmp_ln318_25_fu_1999_p2 | icmp_ln318_24_fu_1994_p2);

assign or_ln331_1_fu_2342_p2 = (icmp_ln331_9_fu_2332_p2 | and_ln331_1_fu_2337_p2);

assign or_ln331_2_fu_2518_p2 = (icmp_ln331_10_reg_4091 | and_ln331_2_fu_2514_p2);

assign or_ln331_3_fu_2718_p2 = (icmp_ln331_11_reg_4151 | and_ln331_3_fu_2714_p2);

assign or_ln331_4_fu_2894_p2 = (icmp_ln331_12_fu_2882_p2 | and_ln331_4_fu_2888_p2);

assign or_ln331_5_fu_3088_p2 = (icmp_ln331_13_fu_3076_p2 | and_ln331_5_fu_3082_p2);

assign or_ln331_6_fu_3277_p2 = (icmp_ln331_14_fu_3266_p2 | and_ln331_6_fu_3271_p2);

assign or_ln331_fu_2157_p2 = (icmp_ln331_8_fu_2147_p2 | and_ln331_fu_2152_p2);

assign p_neg152_fu_2175_p3 = ((delta_reg_3974[0:0] == 1'b1) ? 17'd131071 : 17'd0);

assign p_neg153_fu_2281_p3 = ((delta_1_fu_2275_p2[0:0] == 1'b1) ? 17'd131071 : 17'd0);

assign res_FH_10_fu_1719_p3 = ((or_ln318_6_fu_1700_p2[0:0] == 1'b1) ? res_FH_9_fu_1691_p4 : res_FH_8_reg_3838);

assign res_FH_11_fu_1832_p4 = {res_FH_10_reg_3884[17 - 1:11], |(1'd1), res_FH_10_reg_3884[9:0]};

assign res_FH_12_fu_1846_p3 = ((or_ln318_7_reg_3895[0:0] == 1'b1) ? res_FH_11_fu_1832_p4 : res_FH_10_reg_3884);

assign res_FH_13_fu_1962_p4 = {res_FH_12_reg_3909[17 - 1:10], |(1'd1), res_FH_12_reg_3909[8:0]};

assign res_FH_14_fu_1971_p3 = ((or_ln318_8_reg_3915[0:0] == 1'b1) ? res_FH_13_fu_1962_p4 : res_FH_12_reg_3909);

assign res_FH_15_fu_2033_p4 = {res_FH_14_fu_1971_p3[17 - 1:9], |(1'd1), res_FH_14_fu_1971_p3[7:0]};

assign res_FH_16_fu_2066_p3 = ((or_ln318_fu_2004_p2[0:0] == 1'b1) ? res_FH_15_fu_2033_p4 : res_FH_14_fu_1971_p3);

assign res_FH_17_fu_2197_p4 = {res_FH_16_reg_3957[17 - 1:8], |(1'd1), res_FH_16_reg_3957[6:0]};

assign res_FH_18_fu_2240_p3 = ((or_ln318_10_fu_2212_p2[0:0] == 1'b1) ? res_FH_17_fu_2197_p4 : res_FH_16_reg_3957);

assign res_FH_19_fu_2374_p4 = {res_FH_18_reg_4003[17 - 1:7], |(1'd1), res_FH_18_reg_4003[5:0]};

assign res_FH_1_fu_1198_p4 = {res_FH_reg_3667[17 - 1:16], |(1'd1), res_FH_reg_3667[14:0]};

assign res_FH_20_fu_2417_p3 = ((or_ln318_12_fu_2389_p2[0:0] == 1'b1) ? res_FH_19_fu_2374_p4 : res_FH_18_reg_4003);

assign res_FH_21_fu_2561_p4 = {res_FH_20_reg_4048[17 - 1:6], |(1'd1), res_FH_20_reg_4048[4:0]};

assign res_FH_22_fu_2602_p3 = ((or_ln318_14_fu_2575_p2[0:0] == 1'b1) ? res_FH_21_fu_2561_p4 : res_FH_20_reg_4048);

assign res_FH_23_fu_2747_p4 = {res_FH_22_reg_4114[17 - 1:5], |(1'd1), res_FH_22_reg_4114[3:0]};

assign res_FH_24_fu_2788_p3 = ((or_ln318_16_fu_2761_p2[0:0] == 1'b1) ? res_FH_23_fu_2747_p4 : res_FH_22_reg_4114);

assign res_FH_25_fu_2934_p4 = {res_FH_24_fu_2788_p3[17 - 1:4], |(1'd1), res_FH_24_fu_2788_p3[2:0]};

assign res_FH_26_fu_2972_p3 = ((or_ln318_18_fu_2950_p2[0:0] == 1'b1) ? res_FH_25_fu_2934_p4 : res_FH_24_fu_2788_p3);

assign res_FH_27_fu_3135_p4 = {res_FH_26_reg_4192[17 - 1:3], |(1'd1), res_FH_26_reg_4192[1:0]};

assign res_FH_28_fu_3179_p3 = ((or_ln318_20_fu_3150_p2[0:0] == 1'b1) ? res_FH_27_fu_3135_p4 : res_FH_26_reg_4192);

assign res_FH_29_fu_3323_p4 = {res_FH_28_reg_4232[17 - 1:2], |(1'd1), res_FH_28_reg_4232[0:0]};

assign res_FH_2_fu_1226_p3 = ((or_ln318_2_fu_1207_p2[0:0] == 1'b1) ? res_FH_1_fu_1198_p4 : res_FH_reg_3667);

assign res_FH_30_fu_3358_p3 = ((or_ln318_22_fu_3338_p2[0:0] == 1'b1) ? res_FH_29_fu_3323_p4 : res_FH_28_reg_4232);

assign res_FH_31_fu_3441_p4 = {res_FH_30_reg_4259[17-1:1], |(1'd1)};

assign res_FH_32_fu_3462_p3 = ((or_ln318_24_fu_3456_p2[0:0] == 1'b1) ? res_FH_31_fu_3441_p4 : res_FH_30_reg_4259);

assign res_FH_33_fu_3479_p2 = (res_FH_32_fu_3462_p3 + 17'd1);

assign res_FH_3_fu_1339_p4 = {res_FH_2_reg_3773[17 - 1:15], |(1'd1), res_FH_2_reg_3773[13:0]};

assign res_FH_4_fu_1353_p3 = ((or_ln318_3_reg_3784[0:0] == 1'b1) ? res_FH_3_fu_1339_p4 : res_FH_2_reg_3773);

assign res_FH_5_fu_1448_p4 = {res_FH_4_fu_1353_p3[17 - 1:14], |(1'd1), res_FH_4_fu_1353_p3[12:0]};

assign res_FH_6_fu_1479_p3 = ((or_ln318_4_fu_1458_p2[0:0] == 1'b1) ? res_FH_5_fu_1448_p4 : res_FH_4_fu_1353_p3);

assign res_FH_7_fu_1571_p4 = {res_FH_6_reg_3815[17 - 1:13], |(1'd1), res_FH_6_reg_3815[11:0]};

assign res_FH_8_fu_1600_p3 = ((or_ln318_5_fu_1580_p2[0:0] == 1'b1) ? res_FH_7_fu_1571_p4 : res_FH_6_reg_3815);

assign res_FH_9_fu_1691_p4 = {res_FH_8_reg_3838[17 - 1:12], |(1'd1), res_FH_8_reg_3838[10:0]};

assign res_FH_fu_1008_p3 = ((or_ln318_1_fu_987_p2[0:0] == 1'b1) ? 17'd65536 : 17'd0);

assign res_FH_l_fu_3473_p2 = (zext_ln361_fu_3469_p1 + 18'd1);

assign res_I_10_fu_779_p3 = ((icmp_ln281_5_reg_3609[0:0] == 1'b1) ? res_I_8_reg_3603 : res_I_9_fu_764_p4);

assign res_I_11_fu_841_p4 = {res_I_10_fu_779_p3[8 - 1:2], |(1'd1), res_I_10_fu_779_p3[0:0]};

assign res_I_12_fu_859_p3 = ((icmp_ln281_6_fu_817_p2[0:0] == 1'b1) ? res_I_10_fu_779_p3 : res_I_11_fu_841_p4);

assign res_I_13_fu_922_p4 = {res_I_12_reg_3620[8-1:1], |(1'd1)};

assign res_I_14_fu_931_p3 = ((icmp_ln281_7_reg_3626[0:0] == 1'b1) ? res_I_12_reg_3620 : res_I_13_fu_922_p4);

assign res_I_15_fu_3493_p2 = (res_I_14_reg_3640_pp0_iter16_reg + 8'd1);

assign res_I_16_fu_3498_p3 = ((tmp_62_fu_3485_p3[0:0] == 1'b1) ? res_I_15_fu_3493_p2 : res_I_14_reg_3640_pp0_iter16_reg);

assign res_I_1_fu_450_p4 = {res_I_reg_3547[8 - 1:7], |(1'd1), res_I_reg_3547[5:0]};

assign res_I_2_fu_465_p3 = ((icmp_ln281_1_reg_3553[0:0] == 1'b1) ? res_I_reg_3547 : res_I_1_fu_450_p4);

assign res_I_3_fu_527_p4 = {res_I_2_fu_465_p3[8 - 1:6], |(1'd1), res_I_2_fu_465_p3[4:0]};

assign res_I_4_fu_545_p3 = ((icmp_ln281_2_fu_503_p2[0:0] == 1'b1) ? res_I_2_fu_465_p3 : res_I_3_fu_527_p4);

assign res_I_5_fu_607_p4 = {res_I_4_reg_3580[8 - 1:5], |(1'd1), res_I_4_reg_3580[3:0]};

assign res_I_6_fu_622_p3 = ((icmp_ln281_3_reg_3586[0:0] == 1'b1) ? res_I_4_reg_3580 : res_I_5_fu_607_p4);

assign res_I_7_fu_684_p4 = {res_I_6_fu_622_p3[8 - 1:4], |(1'd1), res_I_6_fu_622_p3[2:0]};

assign res_I_8_fu_702_p3 = ((icmp_ln281_4_fu_660_p2[0:0] == 1'b1) ? res_I_6_fu_622_p3 : res_I_7_fu_684_p4);

assign res_I_9_fu_764_p4 = {res_I_8_reg_3603[8 - 1:3], |(1'd1), res_I_8_reg_3603[1:0]};

assign res_I_fu_356_p3 = ((icmp_ln281_fu_324_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign select_ln235_1_fu_2690_p3 = ((delta_3_fu_2678_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln235_2_fu_2914_p3 = ((delta_4_fu_2876_p2[0:0] == 1'b1) ? 14'd16383 : 14'd0);

assign select_ln235_3_fu_3106_p3 = ((delta_5_fu_3071_p2[0:0] == 1'b1) ? 13'd8191 : 13'd0);

assign select_ln235_4_fu_3295_p3 = ((delta_6_fu_3261_p2[0:0] == 1'b1) ? 12'd4095 : 12'd0);

assign select_ln235_fu_2535_p3 = ((delta_2_reg_4085[0:0] == 1'b1) ? 16'd65535 : 16'd0);

assign sext_ln342_1_fu_2735_p1 = $signed(sub_ln335_3_reg_4156);

assign sext_ln342_2_fu_3000_p1 = $signed(sub_ln335_4_reg_4167);

assign sext_ln342_3_fu_3120_p1 = $signed(sub_ln335_5_fu_3114_p2);

assign sext_ln342_4_fu_3309_p1 = $signed(sub_ln335_6_fu_3303_p2);

assign sext_ln342_fu_2548_p1 = $signed(sub_ln335_2_fu_2542_p2);

assign sub_ln286_1_fu_509_p2 = (tmp_5_fu_489_p4 - zext_ln281_2_fu_499_p1);

assign sub_ln286_2_fu_591_p2 = (tmp_9_fu_571_p4 - zext_ln281_3_fu_581_p1);

assign sub_ln286_3_fu_666_p2 = (tmp_12_fu_646_p4 - zext_ln281_4_fu_656_p1);

assign sub_ln286_4_fu_748_p2 = (tmp_15_fu_728_p4 - zext_ln281_5_fu_738_p1);

assign sub_ln286_5_fu_823_p2 = (tmp_19_fu_803_p4 - zext_ln281_6_fu_813_p1);

assign sub_ln286_6_fu_889_p2 = (trunc_ln281_fu_875_p1 - zext_ln281_7_fu_879_p1);

assign sub_ln286_fu_402_p2 = (tmp_3_fu_382_p4 - zext_ln281_1_fu_392_p1);

assign sub_ln335_1_fu_2360_p2 = (p_neg153_reg_4025 - zext_ln308_fu_2297_p1);

assign sub_ln335_2_fu_2542_p2 = (select_ln235_fu_2535_p3 - zext_ln308_2_fu_2501_p1);

assign sub_ln335_3_fu_2698_p2 = (select_ln235_1_fu_2690_p3 - zext_ln308_4_fu_2642_p1);

assign sub_ln335_4_fu_2922_p2 = (select_ln235_2_fu_2914_p3 - zext_ln308_6_fu_2828_p1);

assign sub_ln335_5_fu_3114_p2 = (select_ln235_3_fu_3106_p3 - zext_ln308_8_fu_3026_p1);

assign sub_ln335_6_fu_3303_p2 = (select_ln235_4_fu_3295_p3 - zext_ln308_10_fu_3218_p1);

assign sub_ln335_fu_2182_p2 = (p_neg152_fu_2175_p3 - mul_FH_8_fu_2108_p4);

assign tmp_10_fu_628_p4 = {{res_I_6_fu_622_p3[7:3]}};

assign tmp_11_fu_638_p3 = {{tmp_10_fu_628_p4}, {1'd1}};

assign tmp_12_fu_646_p4 = {{x_l_I_7_fu_616_p3[12:6]}};

assign tmp_13_fu_710_p4 = {{res_I_8_fu_702_p3[7:2]}};

assign tmp_14_fu_720_p3 = {{tmp_13_fu_710_p4}, {1'd1}};

assign tmp_15_fu_728_p4 = {{x_l_I_9_fu_694_p3[11:4]}};

assign tmp_16_fu_785_p4 = {{res_I_10_fu_779_p3[7:1]}};

assign tmp_17_fu_795_p3 = {{tmp_16_fu_785_p4}, {1'd1}};

assign tmp_18_fu_867_p3 = {{res_I_12_fu_859_p3}, {1'd1}};

assign tmp_19_fu_803_p4 = {{x_l_I_11_fu_773_p3[10:2]}};

assign tmp_1_fu_310_p4 = {{x_val_int_reg[31:30]}};

assign tmp_20_fu_1016_p4 = {{res_FH_fu_1008_p3[16:15]}};

assign tmp_21_fu_1040_p4 = {{res_I_14_fu_931_p3[7:1]}};

assign tmp_22_fu_408_p4 = {{x_val_int_reg[15:14]}};

assign tmp_23_fu_424_p4 = {{x_val_int_reg[15:14]}};

assign tmp_24_fu_1233_p4 = {{res_FH_2_fu_1226_p3[16:14]}};

assign tmp_26_fu_1359_p4 = {{res_FH_4_fu_1353_p3[16:13]}};

assign tmp_29_fu_2074_p4 = {{res_FH_16_fu_2066_p3[8:7]}};

assign tmp_2_fu_3397_p3 = x_val_read_reg_3531_pp0_iter16_reg[32'd31];

assign tmp_31_fu_2247_p4 = {{res_FH_18_fu_2240_p3[9:6]}};

assign tmp_32_fu_1607_p4 = {{res_FH_8_fu_1600_p3[16:11]}};

assign tmp_34_fu_1726_p4 = {{res_FH_10_fu_1719_p3[16:10]}};

assign tmp_36_fu_1852_p4 = {{res_FH_12_fu_1846_p3[16:9]}};

assign tmp_37_fu_2424_p4 = {{res_FH_20_fu_2417_p3[10:5]}};

assign tmp_38_fu_2609_p4 = {{res_FH_22_fu_2602_p3[11:4]}};

assign tmp_39_fu_2795_p4 = {{res_FH_24_fu_2788_p3[12:3]}};

assign tmp_3_fu_382_p4 = {{x_l_I_1_fu_348_p3[15:12]}};

assign tmp_45_fu_2434_p4 = {{res_FH_20_fu_2417_p3[16:11]}};

assign tmp_46_fu_2619_p4 = {{res_FH_22_fu_2602_p3[16:12]}};

assign tmp_47_fu_2805_p4 = {{res_FH_24_fu_2788_p3[16:13]}};

assign tmp_4_fu_471_p4 = {{res_I_2_fu_465_p3[7:5]}};

assign tmp_50_fu_1977_p4 = {{res_FH_14_fu_1971_p3[16:8]}};

assign tmp_51_fu_3505_p4 = {{res_FH_33_fu_3479_p2[16:1]}};

assign tmp_5_fu_489_p4 = {{x_l_I_3_fu_459_p3[14:10]}};

assign tmp_62_fu_3485_p3 = res_FH_l_fu_3473_p2[32'd17];

assign tmp_6_fu_481_p3 = {{tmp_4_fu_471_p4}, {1'd1}};

assign tmp_7_fu_563_p3 = {{tmp_8_fu_553_p4}, {1'd1}};

assign tmp_8_fu_553_p4 = {{res_I_4_fu_545_p3[7:4]}};

assign tmp_9_fu_571_p4 = {{x_l_I_5_fu_537_p3[13:8]}};

assign tmp_fu_374_p3 = {{tmp_s_fu_364_p4}, {1'd1}};

assign tmp_s_fu_364_p4 = {{res_I_fu_356_p3[7:6]}};

assign trunc_ln236_fu_306_p1 = x_val_int_reg[15:0];

assign trunc_ln281_fu_875_p1 = x_l_I_13_fu_851_p3[9:0];

assign trunc_ln2_fu_937_p3 = {{1'd0}, {res_I_14_fu_931_p3}};

assign trunc_ln306_1_fu_1092_p1 = res_I_14_fu_931_p3[1:0];

assign trunc_ln306_2_fu_1106_p1 = res_I_14_fu_931_p3[2:0];

assign trunc_ln306_3_fu_1120_p1 = res_I_14_fu_931_p3[3:0];

assign trunc_ln306_4_fu_1134_p1 = res_I_14_fu_931_p3[4:0];

assign trunc_ln306_5_fu_1148_p1 = res_I_14_fu_931_p3[5:0];

assign trunc_ln306_6_fu_1162_p1 = res_I_14_fu_931_p3[6:0];

assign trunc_ln306_7_fu_3365_p1 = res_FH_30_fu_3358_p3[15:0];

assign trunc_ln306_fu_1026_p1 = res_I_14_fu_931_p3[0:0];

assign trunc_ln318_1_fu_1050_p3 = {{1'd0}, {tmp_21_fu_1040_p4}};

assign trunc_ln318_2_fu_1252_p3 = {{1'd0}, {tmp_25_reg_3713}};

assign trunc_ln318_3_fu_1378_p3 = {{1'd0}, {tmp_27_reg_3723_pp0_iter5_reg}};

assign trunc_ln318_4_fu_1505_p3 = {{1'd0}, {tmp_30_reg_3733_pp0_iter6_reg}};

assign trunc_ln318_5_fu_1626_p3 = {{1'd0}, {tmp_33_reg_3743_pp0_iter6_reg}};

assign trunc_ln318_6_fu_1745_p3 = {{1'd0}, {tmp_35_reg_3753_pp0_iter7_reg}};

assign trunc_ln318_7_fu_1871_p3 = {{1'd0}, {tmp_42_reg_3763_pp0_iter8_reg}};

assign trunc_ln4_fu_3515_p3 = {{res_I_16_fu_3498_p3}, {tmp_51_fu_3505_p4}};

assign trunc_ln_fu_292_p4 = {{x_val_int_reg[31:16]}};

assign x_l_FH_11_fu_1687_p2 = (x_l_FH_38_reg_3832 - mul_FH_4_reg_3844);

assign x_l_FH_13_fu_1812_p2 = (x_l_FH_39_fu_1712_p3 - mul_FH_5_fu_1736_p4);

assign x_l_FH_15_fu_1936_p2 = (x_l_FH_40_reg_3901 - mul_FH_6_fu_1862_p4);

assign x_l_FH_17_fu_2028_p2 = (x_l_FH_41_reg_3927 + xor_ln335_fu_2022_p2);

assign x_l_FH_19_fu_2188_p2 = (sub_ln335_fu_2182_p2 + x_l_FH_42_reg_3941);

assign x_l_FH_21_fu_2365_p2 = (sub_ln335_1_fu_2360_p2 + x_l_FH_43_reg_3987);

assign x_l_FH_23_fu_2552_p2 = ($signed(sext_ln342_fu_2548_p1) + $signed(x_l_FH_44_reg_4036));

assign x_l_FH_25_fu_2738_p2 = ($signed(sext_ln342_1_fu_2735_p1) + $signed(x_l_FH_45_reg_4102));

assign x_l_FH_27_fu_3003_p2 = ($signed(sext_ln342_2_fu_3000_p1) + $signed(x_l_FH_46_reg_4161));

assign x_l_FH_29_fu_3124_p2 = ($signed(sext_ln342_3_fu_3120_p1) + $signed(x_l_FH_47_fu_3008_p3));

assign x_l_FH_31_fu_3313_p2 = ($signed(sext_ln342_4_fu_3309_p1) + $signed(x_l_FH_48_reg_4215));

assign x_l_FH_32_fu_3344_p3 = ((or_ln318_22_fu_3338_p2[0:0] == 1'b1) ? x_l_FH_31_fu_3313_p2 : x_l_FH_48_reg_4215);

assign x_l_FH_33_fu_915_p3 = {{trunc_ln236_reg_3536_pp0_iter3_reg}, {1'd0}};

assign x_l_FH_34_fu_1000_p3 = ((or_ln318_1_fu_987_p2[0:0] == 1'b1) ? x_l_FH_fu_981_p2 : x_l_FH_33_fu_915_p3);

assign x_l_FH_35_fu_1219_p3 = ((or_ln318_2_fu_1207_p2[0:0] == 1'b1) ? x_l_FH_3_fu_1194_p2 : x_l_FH_34_reg_3661);

assign x_l_FH_36_fu_1331_p3 = ((or_ln318_3_fu_1325_p2[0:0] == 1'b1) ? x_l_FH_5_fu_1319_p2 : x_l_FH_35_fu_1219_p3);

assign x_l_FH_37_fu_1472_p3 = ((or_ln318_4_fu_1458_p2[0:0] == 1'b1) ? x_l_FH_7_fu_1443_p2 : x_l_FH_36_reg_3790);

assign x_l_FH_38_fu_1593_p3 = ((or_ln318_5_fu_1580_p2[0:0] == 1'b1) ? x_l_FH_9_fu_1566_p2 : x_l_FH_37_reg_3807);

assign x_l_FH_39_fu_1712_p3 = ((or_ln318_6_fu_1700_p2[0:0] == 1'b1) ? x_l_FH_11_fu_1687_p2 : x_l_FH_38_reg_3832);

assign x_l_FH_3_fu_1194_p2 = (x_l_FH_34_reg_3661 - mul_FH_reg_3673);

assign x_l_FH_40_fu_1824_p3 = ((or_ln318_7_fu_1818_p2[0:0] == 1'b1) ? x_l_FH_13_fu_1812_p2 : x_l_FH_39_fu_1712_p3);

assign x_l_FH_41_fu_1955_p3 = ((or_ln318_8_fu_1941_p2[0:0] == 1'b1) ? x_l_FH_15_fu_1936_p2 : x_l_FH_40_reg_3901);

assign x_l_FH_42_fu_2051_p3 = ((or_ln318_fu_2004_p2[0:0] == 1'b1) ? x_l_FH_17_fu_2028_p2 : x_l_FH_41_reg_3927);

assign x_l_FH_43_fu_2226_p3 = ((or_ln318_10_fu_2212_p2[0:0] == 1'b1) ? x_l_FH_19_fu_2188_p2 : x_l_FH_42_reg_3941);

assign x_l_FH_44_fu_2403_p3 = ((or_ln318_12_fu_2389_p2[0:0] == 1'b1) ? x_l_FH_21_fu_2365_p2 : x_l_FH_43_reg_3987);

assign x_l_FH_45_fu_2588_p3 = ((or_ln318_14_fu_2575_p2[0:0] == 1'b1) ? x_l_FH_23_fu_2552_p2 : x_l_FH_44_reg_4036);

assign x_l_FH_46_fu_2774_p3 = ((or_ln318_16_fu_2761_p2[0:0] == 1'b1) ? x_l_FH_25_fu_2738_p2 : x_l_FH_45_reg_4102);

assign x_l_FH_47_fu_3008_p3 = ((or_ln318_18_reg_4172[0:0] == 1'b1) ? x_l_FH_27_fu_3003_p2 : x_l_FH_46_reg_4161);

assign x_l_FH_48_fu_3164_p3 = ((or_ln318_20_fu_3150_p2[0:0] == 1'b1) ? x_l_FH_29_fu_3124_p2 : x_l_FH_47_fu_3008_p3);

assign x_l_FH_5_fu_1319_p2 = (x_l_FH_35_fu_1219_p3 - mul_FH_1_fu_1243_p4);

assign x_l_FH_7_fu_1443_p2 = (x_l_FH_36_reg_3790 - mul_FH_2_fu_1369_p4);

assign x_l_FH_9_fu_1566_p2 = (x_l_FH_37_reg_3807 - mul_FH_3_fu_1497_p4);

assign x_l_FH_fu_981_p2 = ($signed(x_l_FH_33_fu_915_p3) + $signed(17'd98304));

assign x_l_FL_11_fu_3130_p2 = (x_l_FL_20_reg_4184 - mul_FL_5_fu_3030_p3);

assign x_l_FL_13_fu_3318_p2 = (x_l_FL_21_reg_4224 - mul_FL_6_fu_3222_p3);

assign x_l_FL_14_fu_3351_p3 = ((or_ln318_22_fu_3338_p2[0:0] == 1'b1) ? x_l_FL_13_fu_3318_p2 : x_l_FL_21_reg_4224);

assign x_l_FL_15_fu_2058_p3 = ((or_ln318_fu_2004_p2[0:0] == 1'b1) ? 17'd65536 : 17'd0);

assign x_l_FL_16_fu_2233_p3 = ((or_ln318_10_fu_2212_p2[0:0] == 1'b1) ? x_l_FL_fu_2193_p2 : x_l_FL_15_reg_3950);

assign x_l_FL_17_fu_2410_p3 = ((or_ln318_12_fu_2389_p2[0:0] == 1'b1) ? x_l_FL_3_fu_2370_p2 : x_l_FL_16_reg_3996);

assign x_l_FL_18_fu_2595_p3 = ((or_ln318_14_fu_2575_p2[0:0] == 1'b1) ? x_l_FL_5_fu_2557_p2 : x_l_FL_17_reg_4042);

assign x_l_FL_19_fu_2781_p3 = ((or_ln318_16_fu_2761_p2[0:0] == 1'b1) ? x_l_FL_7_fu_2743_p2 : x_l_FL_18_reg_4108);

assign x_l_FL_20_fu_2964_p3 = ((or_ln318_18_fu_2950_p2[0:0] == 1'b1) ? x_l_FL_9_fu_2928_p2 : x_l_FL_19_fu_2781_p3);

assign x_l_FL_21_fu_3172_p3 = ((or_ln318_20_fu_3150_p2[0:0] == 1'b1) ? x_l_FL_11_fu_3130_p2 : x_l_FL_20_reg_4184);

assign x_l_FL_3_fu_2370_p2 = (x_l_FL_16_reg_3996 - mul_FL_1_reg_4014);

assign x_l_FL_5_fu_2557_p2 = (x_l_FL_17_reg_4042 - mul_FL_2_reg_4059);

assign x_l_FL_7_fu_2743_p2 = (x_l_FL_18_reg_4108 - mul_FL_3_reg_4120);

assign x_l_FL_9_fu_2928_p2 = (x_l_FL_19_fu_2781_p3 - mul_FL_4_fu_2832_p3);

assign x_l_FL_fu_2193_p2 = (x_l_FL_15_reg_3950 - mul_FL_reg_3968);

assign x_l_I_10_fu_754_p5 = {{x_l_I_9_reg_3597[18:12]}, {sub_ln286_4_reg_3615}, {x_l_I_9_reg_3597[3:0]}};

assign x_l_I_11_fu_773_p3 = ((icmp_ln281_5_reg_3609[0:0] == 1'b1) ? x_l_I_9_reg_3597 : x_l_I_10_fu_754_p5);

assign x_l_I_12_fu_829_p5 = {{x_l_I_11_fu_773_p3[18:11]}, {sub_ln286_5_fu_823_p2}, {x_l_I_11_fu_773_p3[1:0]}};

assign x_l_I_13_fu_851_p3 = ((icmp_ln281_6_fu_817_p2[0:0] == 1'b1) ? x_l_I_11_fu_773_p3 : x_l_I_12_fu_829_p5);

assign x_l_I_14_fu_895_p5 = {{x_l_I_13_fu_851_p3[18:10]}, {sub_ln286_6_fu_889_p2}};

assign x_l_I_15_fu_907_p3 = ((icmp_ln281_7_fu_883_p2[0:0] == 1'b1) ? x_l_I_13_fu_851_p3 : x_l_I_14_fu_895_p5);

assign x_l_I_16_fu_964_p2 = ($signed(x_l_I_15_reg_3631) + $signed(19'd524287));

assign x_l_I_17_fu_969_p3 = ((icmp_ln331_reg_3569_pp0_iter3_reg[0:0] == 1'b1) ? x_l_I_16_fu_964_p2 : x_l_I_15_reg_3631);

assign x_l_I_18_fu_975_p2 = (x_l_I_17_fu_969_p3 - zext_ln318_fu_945_p1);

assign x_l_I_19_fu_993_p3 = ((or_ln318_1_fu_987_p2[0:0] == 1'b1) ? x_l_I_18_fu_975_p2 : x_l_I_15_reg_3631);

assign x_l_I_1_fu_348_p3 = ((icmp_ln281_fu_324_p2[0:0] == 1'b1) ? zext_ln235_fu_302_p1 : x_l_I_fu_336_p5);

assign x_l_I_20_fu_1086_p2 = ($signed(x_l_I_19_fu_993_p3) + $signed(19'd524287));

assign x_l_I_21_fu_1184_p3 = ((icmp_ln331_1_reg_3698[0:0] == 1'b1) ? x_l_I_20_reg_3703 : x_l_I_19_reg_3655);

assign x_l_I_22_fu_1189_p2 = (x_l_I_21_fu_1184_p3 - zext_ln318_1_reg_3678);

assign x_l_I_23_fu_1212_p3 = ((or_ln318_2_fu_1207_p2[0:0] == 1'b1) ? x_l_I_22_fu_1189_p2 : x_l_I_19_reg_3655);

assign x_l_I_24_fu_1299_p2 = ($signed(x_l_I_23_fu_1212_p3) + $signed(19'd524287));

assign x_l_I_25_fu_1305_p3 = ((icmp_ln331_2_fu_1293_p2[0:0] == 1'b1) ? x_l_I_24_fu_1299_p2 : x_l_I_23_fu_1212_p3);

assign x_l_I_26_fu_1313_p2 = (x_l_I_25_fu_1305_p3 - zext_ln318_2_fu_1259_p1);

assign x_l_I_27_fu_1348_p3 = ((or_ln318_3_reg_3784[0:0] == 1'b1) ? x_l_I_26_reg_3779 : x_l_I_23_reg_3768);

assign x_l_I_28_fu_1423_p2 = ($signed(x_l_I_27_fu_1348_p3) + $signed(19'd524287));

assign x_l_I_29_fu_1429_p3 = ((icmp_ln331_3_fu_1418_p2[0:0] == 1'b1) ? x_l_I_28_fu_1423_p2 : x_l_I_27_fu_1348_p3);

assign x_l_I_2_fu_440_p5 = {{x_l_I_1_reg_3541[18:16]}, {sub_ln286_reg_3559}, {x_l_I_1_reg_3541[11:0]}};

assign x_l_I_30_fu_1437_p2 = (x_l_I_29_fu_1429_p3 - zext_ln318_3_fu_1385_p1);

assign x_l_I_31_fu_1464_p3 = ((or_ln318_4_fu_1458_p2[0:0] == 1'b1) ? x_l_I_30_fu_1437_p2 : x_l_I_27_fu_1348_p3);

assign x_l_I_32_fu_1548_p2 = ($signed(x_l_I_31_reg_3798) + $signed(19'd524287));

assign x_l_I_33_fu_1553_p3 = ((icmp_ln331_4_fu_1543_p2[0:0] == 1'b1) ? x_l_I_32_fu_1548_p2 : x_l_I_31_reg_3798);

assign x_l_I_34_fu_1560_p2 = (x_l_I_33_fu_1553_p3 - zext_ln318_4_fu_1512_p1);

assign x_l_I_35_fu_1586_p3 = ((or_ln318_5_fu_1580_p2[0:0] == 1'b1) ? x_l_I_34_fu_1560_p2 : x_l_I_31_reg_3798);

assign x_l_I_36_fu_1661_p2 = ($signed(x_l_I_35_fu_1586_p3) + $signed(19'd524287));

assign x_l_I_37_fu_1677_p3 = ((icmp_ln331_5_reg_3869[0:0] == 1'b1) ? x_l_I_36_reg_3874 : x_l_I_35_reg_3826);

assign x_l_I_38_fu_1682_p2 = (x_l_I_37_fu_1677_p3 - zext_ln318_5_reg_3849);

assign x_l_I_39_fu_1705_p3 = ((or_ln318_6_fu_1700_p2[0:0] == 1'b1) ? x_l_I_38_fu_1682_p2 : x_l_I_35_reg_3826);

assign x_l_I_3_fu_459_p3 = ((icmp_ln281_1_reg_3553[0:0] == 1'b1) ? x_l_I_1_reg_3541 : x_l_I_2_fu_440_p5);

assign x_l_I_40_fu_1792_p2 = ($signed(x_l_I_39_fu_1705_p3) + $signed(19'd524287));

assign x_l_I_41_fu_1798_p3 = ((icmp_ln331_6_fu_1786_p2[0:0] == 1'b1) ? x_l_I_40_fu_1792_p2 : x_l_I_39_fu_1705_p3);

assign x_l_I_42_fu_1806_p2 = (x_l_I_41_fu_1798_p3 - zext_ln318_6_fu_1752_p1);

assign x_l_I_43_fu_1841_p3 = ((or_ln318_7_reg_3895[0:0] == 1'b1) ? x_l_I_42_reg_3890 : x_l_I_39_reg_3879);

assign x_l_I_44_fu_1916_p2 = ($signed(x_l_I_43_fu_1841_p3) + $signed(19'd524287));

assign x_l_I_45_fu_1922_p3 = ((icmp_ln331_7_fu_1911_p2[0:0] == 1'b1) ? x_l_I_44_fu_1916_p2 : x_l_I_43_fu_1841_p3);

assign x_l_I_46_fu_1930_p2 = (x_l_I_45_fu_1922_p3 - zext_ln318_7_fu_1878_p1);

assign x_l_I_47_fu_1947_p3 = ((or_ln318_8_fu_1941_p2[0:0] == 1'b1) ? x_l_I_46_fu_1930_p2 : x_l_I_43_fu_1841_p3);

assign x_l_I_48_fu_2010_p2 = ($signed(x_l_I_47_reg_3920) + $signed(19'd524287));

assign x_l_I_49_fu_2015_p3 = ((icmp_ln318_25_fu_1999_p2[0:0] == 1'b1) ? x_l_I_47_reg_3920 : x_l_I_48_fu_2010_p2);

assign x_l_I_4_fu_515_p5 = {{x_l_I_3_fu_459_p3[18:15]}, {sub_ln286_1_fu_509_p2}, {x_l_I_3_fu_459_p3[9:0]}};

assign x_l_I_50_fu_2043_p3 = ((or_ln318_fu_2004_p2[0:0] == 1'b1) ? x_l_I_49_fu_2015_p3 : 19'd0);

assign x_l_I_51_fu_2163_p2 = ($signed(x_l_I_50_reg_3934) + $signed(19'd524287));

assign x_l_I_52_fu_2168_p3 = ((or_ln331_fu_2157_p2[0:0] == 1'b1) ? x_l_I_51_fu_2163_p2 : x_l_I_50_reg_3934);

assign x_l_I_53_fu_2218_p3 = ((or_ln318_10_fu_2212_p2[0:0] == 1'b1) ? x_l_I_52_fu_2168_p3 : 19'd0);

assign x_l_I_54_fu_2348_p2 = ($signed(x_l_I_53_reg_3980) + $signed(19'd524287));

assign x_l_I_55_fu_2353_p3 = ((or_ln331_1_fu_2342_p2[0:0] == 1'b1) ? x_l_I_54_fu_2348_p2 : x_l_I_53_reg_3980);

assign x_l_I_56_fu_2395_p3 = ((or_ln318_12_fu_2389_p2[0:0] == 1'b1) ? x_l_I_55_fu_2353_p3 : 19'd0);

assign x_l_I_57_fu_2523_p2 = ($signed(x_l_I_56_reg_4030) + $signed(19'd524287));

assign x_l_I_58_fu_2528_p3 = ((or_ln331_2_fu_2518_p2[0:0] == 1'b1) ? x_l_I_57_fu_2523_p2 : x_l_I_56_reg_4030);

assign x_l_I_59_fu_2580_p3 = ((or_ln318_14_fu_2575_p2[0:0] == 1'b1) ? x_l_I_58_fu_2528_p3 : 19'd0);

assign x_l_I_5_fu_537_p3 = ((icmp_ln281_2_fu_503_p2[0:0] == 1'b1) ? x_l_I_3_fu_459_p3 : x_l_I_4_fu_515_p5);

assign x_l_I_60_fu_2723_p2 = ($signed(x_l_I_59_reg_4096) + $signed(19'd524287));

assign x_l_I_61_fu_2728_p3 = ((or_ln331_3_fu_2718_p2[0:0] == 1'b1) ? x_l_I_60_fu_2723_p2 : x_l_I_59_reg_4096);

assign x_l_I_62_fu_2766_p3 = ((or_ln318_16_fu_2761_p2[0:0] == 1'b1) ? x_l_I_61_fu_2728_p3 : 19'd0);

assign x_l_I_63_fu_2900_p2 = ($signed(x_l_I_62_fu_2766_p3) + $signed(19'd524287));

assign x_l_I_64_fu_2906_p3 = ((or_ln331_4_fu_2894_p2[0:0] == 1'b1) ? x_l_I_63_fu_2900_p2 : x_l_I_62_fu_2766_p3);

assign x_l_I_65_fu_2956_p3 = ((or_ln318_18_fu_2950_p2[0:0] == 1'b1) ? x_l_I_64_fu_2906_p3 : 19'd0);

assign x_l_I_66_fu_3094_p2 = ($signed(x_l_I_65_reg_4177) + $signed(19'd524287));

assign x_l_I_67_fu_3099_p3 = ((or_ln331_5_fu_3088_p2[0:0] == 1'b1) ? x_l_I_66_fu_3094_p2 : x_l_I_65_reg_4177);

assign x_l_I_68_fu_3156_p3 = ((or_ln318_20_fu_3150_p2[0:0] == 1'b1) ? x_l_I_67_fu_3099_p3 : 19'd0);

assign x_l_I_69_fu_3283_p2 = ($signed(x_l_I_68_reg_4208) + $signed(19'd524287));

assign x_l_I_6_fu_597_p5 = {{x_l_I_5_reg_3574[18:14]}, {sub_ln286_2_reg_3592}, {x_l_I_5_reg_3574[7:0]}};

assign x_l_I_70_fu_3288_p3 = ((or_ln331_6_fu_3277_p2[0:0] == 1'b1) ? x_l_I_69_fu_3283_p2 : x_l_I_68_reg_4208);

assign x_l_I_7_fu_616_p3 = ((icmp_ln281_3_reg_3586[0:0] == 1'b1) ? x_l_I_5_reg_3574 : x_l_I_6_fu_597_p5);

assign x_l_I_8_fu_672_p5 = {{x_l_I_7_fu_616_p3[18:13]}, {sub_ln286_3_fu_666_p2}, {x_l_I_7_fu_616_p3[5:0]}};

assign x_l_I_9_fu_694_p3 = ((icmp_ln281_4_fu_660_p2[0:0] == 1'b1) ? x_l_I_7_fu_616_p3 : x_l_I_8_fu_672_p5);

assign x_l_I_fu_336_p5 = {{zext_ln235_fu_302_p1[18:17]}, {add_ln286_fu_330_p2}, {zext_ln235_fu_302_p1[13:0]}};

assign xor_ln318_10_fu_2704_p2 = (icmp_ln318_41_reg_4141 ^ 1'd1);

assign xor_ln318_11_fu_2864_p2 = (icmp_ln318_45_fu_2858_p2 ^ 1'd1);

assign xor_ln318_12_fu_3059_p2 = (icmp_ln318_49_fu_3054_p2 ^ 1'd1);

assign xor_ln318_13_fu_3249_p2 = (icmp_ln318_53_fu_3244_p2 ^ 1'd1);

assign xor_ln318_14_fu_3430_p2 = (icmp_ln318_57_reg_4275 ^ 1'd1);

assign xor_ln318_1_fu_1281_p2 = (icmp_ln318_8_fu_1275_p2 ^ 1'd1);

assign xor_ln318_2_fu_1406_p2 = (icmp_ln318_11_fu_1401_p2 ^ 1'd1);

assign xor_ln318_3_fu_1531_p2 = (icmp_ln318_14_fu_1526_p2 ^ 1'd1);

assign xor_ln318_4_fu_1667_p2 = (icmp_ln318_17_reg_3864 ^ 1'd1);

assign xor_ln318_5_fu_1774_p2 = (icmp_ln318_20_fu_1768_p2 ^ 1'd1);

assign xor_ln318_6_fu_1899_p2 = (icmp_ln318_23_fu_1894_p2 ^ 1'd1);

assign xor_ln318_7_fu_2135_p2 = (icmp_ln318_29_fu_2131_p2 ^ 1'd1);

assign xor_ln318_8_fu_2320_p2 = (icmp_ln318_33_fu_2316_p2 ^ 1'd1);

assign xor_ln318_9_fu_2504_p2 = (icmp_ln318_37_reg_4080 ^ 1'd1);

assign xor_ln318_fu_1174_p2 = (icmp_ln318_5_reg_3693 ^ 1'd1);

assign xor_ln335_fu_2022_p2 = (mul_FH_7_fu_1987_p3 ^ 17'd131071);

assign zext_ln235_fu_302_p1 = trunc_ln_fu_292_p4;

assign zext_ln281_1_fu_392_p1 = tmp_fu_374_p3;

assign zext_ln281_2_fu_499_p1 = tmp_6_fu_481_p3;

assign zext_ln281_3_fu_581_p1 = tmp_7_fu_563_p3;

assign zext_ln281_4_fu_656_p1 = tmp_11_fu_638_p3;

assign zext_ln281_5_fu_738_p1 = tmp_14_fu_720_p3;

assign zext_ln281_6_fu_813_p1 = tmp_17_fu_795_p3;

assign zext_ln281_7_fu_879_p1 = tmp_18_fu_867_p3;

assign zext_ln281_fu_320_p1 = tmp_1_fu_310_p4;

assign zext_ln308_10_fu_3218_p1 = mul_FH_13_fu_3206_p4;

assign zext_ln308_11_fu_3412_p1 = mul_FH_14_fu_3404_p4;

assign zext_ln308_1_fu_2453_p1 = mul_FH_s_fu_2444_p4;

assign zext_ln308_2_fu_2501_p1 = mul_FH_s_reg_4054;

assign zext_ln308_3_fu_2638_p1 = mul_FH_10_fu_2629_p4;

assign zext_ln308_4_fu_2642_p1 = mul_FH_10_fu_2629_p4;

assign zext_ln308_5_fu_2824_p1 = mul_FH_11_fu_2815_p4;

assign zext_ln308_6_fu_2828_p1 = mul_FH_11_fu_2815_p4;

assign zext_ln308_7_fu_3022_p1 = mul_FH_12_fu_3014_p4;

assign zext_ln308_8_fu_3026_p1 = mul_FH_12_fu_3014_p4;

assign zext_ln308_9_fu_3214_p1 = mul_FH_13_fu_3206_p4;

assign zext_ln308_fu_2297_p1 = mul_FH_9_fu_2289_p4;

assign zext_ln318_1_fu_1058_p1 = trunc_ln318_1_fu_1050_p3;

assign zext_ln318_2_fu_1259_p1 = trunc_ln318_2_fu_1252_p3;

assign zext_ln318_3_fu_1385_p1 = trunc_ln318_3_fu_1378_p3;

assign zext_ln318_4_fu_1512_p1 = trunc_ln318_4_fu_1505_p3;

assign zext_ln318_5_fu_1633_p1 = trunc_ln318_5_fu_1626_p3;

assign zext_ln318_6_fu_1752_p1 = trunc_ln318_6_fu_1745_p3;

assign zext_ln318_7_fu_1878_p1 = trunc_ln318_7_fu_1871_p3;

assign zext_ln318_fu_945_p1 = trunc_ln2_fu_937_p3;

assign zext_ln361_fu_3469_p1 = res_FH_32_fu_3462_p3;

always @ (posedge ap_clk) begin
    res_I_reg_3547[6:0] <= 7'b0000000;
    x_l_FH_34_reg_3661[0] <= 1'b0;
    res_FH_reg_3667[15:0] <= 16'b0000000000000000;
    mul_FH_reg_3673[14:0] <= 15'b010000000000000;
    zext_ln318_1_reg_3678[18:7] <= 12'b000000000000;
    x_l_FH_36_reg_3790[0] <= 1'b0;
    x_l_FH_37_reg_3807[0] <= 1'b0;
    x_l_FH_38_reg_3832[0] <= 1'b0;
    mul_FH_4_reg_3844[5:0] <= 6'b100000;
    zext_ln318_5_reg_3849[18:3] <= 16'b0000000000000000;
    x_l_FH_40_reg_3901[0] <= 1'b0;
    x_l_FH_41_reg_3927[0] <= 1'b0;
    x_l_FL_15_reg_3950[15:0] <= 16'b0000000000000000;
    mul_FL_reg_3968[14:0] <= 15'b100000000000000;
    x_l_FL_16_reg_3996[13:0] <= 14'b00000000000000;
    mul_FL_1_reg_4014[12:0] <= 13'b1000000000000;
    x_l_FL_17_reg_4042[11:0] <= 12'b000000000000;
    mul_FH_s_reg_4054[14] <= 1'b0;
    mul_FL_2_reg_4059[10:0] <= 11'b10000000000;
    x_l_FL_18_reg_4108[9:0] <= 10'b0000000000;
    mul_FL_3_reg_4120[8:0] <= 9'b100000000;
    x_l_FL_20_reg_4184[5:0] <= 6'b000000;
    x_l_FL_21_reg_4224[3:0] <= 4'b0000;
end

endmodule //kernel_cholesky_sqrt_fixed_32_16_s
