// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="kernel_symm_kernel_symm,hls_ip_2023_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.034000,HLS_SYN_LAT=18001,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2488,HLS_SYN_LUT=1536,HLS_VERSION=2023_1_1}" *)

module kernel_symm (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        alpha,
        beta,
        C_address0,
        C_ce0,
        C_we0,
        C_d0,
        C_q0,
        C_address1,
        C_ce1,
        C_q1,
        A_address0,
        A_ce0,
        A_q0,
        B_address0,
        B_ce0,
        B_q0
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] alpha;
input  [31:0] beta;
output  [9:0] C_address0;
output   C_ce0;
output   C_we0;
output  [31:0] C_d0;
input  [31:0] C_q0;
output  [9:0] C_address1;
output   C_ce1;
input  [31:0] C_q1;
output  [8:0] A_address0;
output   A_ce0;
input  [31:0] A_q0;
output  [9:0] B_address0;
output   B_ce0;
input  [31:0] B_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] C_address0;
reg C_ce0;
reg C_we0;
reg[31:0] C_d0;
reg C_ce1;
reg[8:0] A_address0;
reg A_ce0;
reg[9:0] B_address0;
reg B_ce0;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire  signed [63:0] conv_i389_fu_183_p1;
reg  signed [63:0] conv_i389_reg_440;
wire  signed [47:0] alpha_cast_fu_187_p1;
reg  signed [47:0] alpha_cast_reg_445;
wire  signed [47:0] sext_ln22_fu_191_p1;
reg  signed [47:0] sext_ln22_reg_450;
wire   [4:0] select_ln22_fu_243_p3;
reg   [4:0] select_ln22_reg_458;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln22_fu_213_p2;
wire   [4:0] select_ln22_1_fu_251_p3;
reg   [4:0] select_ln22_1_reg_464;
reg   [9:0] C_addr_reg_474;
wire    ap_CS_fsm_state3;
reg  signed [31:0] B_load_reg_484;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg  signed [31:0] A_load_reg_499;
wire    ap_CS_fsm_state6;
wire  signed [63:0] grp_fu_175_p2;
reg   [63:0] mul_ln30_reg_504;
wire   [8:0] add_ln27_1_fu_355_p2;
reg   [8:0] add_ln27_1_reg_510;
wire    ap_CS_fsm_state7;
reg  signed [31:0] C_load_reg_520;
wire    ap_CS_fsm_state10;
wire  signed [47:0] sext_ln30_1_fu_369_p1;
wire    ap_CS_fsm_state11;
wire   [63:0] grp_fu_179_p2;
reg   [63:0] mul_ln30_2_reg_530;
wire   [47:0] grp_fu_167_p2;
reg   [47:0] mul_ln30_1_reg_540;
wire    ap_CS_fsm_state12;
wire   [47:0] grp_fu_171_p2;
reg   [47:0] mul_ln30_3_reg_545;
reg   [31:0] trunc_ln_reg_550;
wire    ap_CS_fsm_state13;
wire    grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_start;
wire    grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_done;
wire    grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_idle;
wire    grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_ready;
wire   [9:0] grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_address0;
wire    grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_ce0;
wire    grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_we0;
wire   [31:0] grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_d0;
wire   [9:0] grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_address1;
wire    grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_ce1;
wire   [8:0] grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_A_address0;
wire    grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_A_ce0;
wire   [9:0] grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_B_address0;
wire    grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_B_ce0;
wire  signed [31:0] grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_temp2_out;
wire    grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_temp2_out_ap_vld;
wire  signed [31:0] grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_grp_fu_167_p_din0;
wire  signed [31:0] grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_grp_fu_167_p_din1;
wire    grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_grp_fu_167_p_ce;
reg    grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_start_reg;
wire    ap_CS_fsm_state8;
wire   [63:0] zext_ln30_2_fu_313_p1;
wire   [63:0] mul_ln22_cast_fu_328_p1;
reg   [4:0] j_fu_86;
wire   [4:0] add_ln23_fu_259_p2;
reg   [4:0] i_fu_90;
reg   [9:0] indvar_flatten_fu_94;
wire   [9:0] add_ln22_1_fu_219_p2;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state14;
reg  signed [31:0] grp_fu_167_p0;
reg  signed [31:0] grp_fu_167_p1;
wire  signed [31:0] grp_fu_171_p1;
wire  signed [31:0] grp_fu_175_p1;
wire  signed [31:0] conv_i389_fu_183_p0;
wire  signed [31:0] alpha_cast_fu_187_p0;
wire   [0:0] icmp_ln23_fu_237_p2;
wire   [4:0] add_ln22_fu_231_p2;
wire   [5:0] tmp_1_fu_287_p3;
wire   [9:0] tmp_fu_280_p3;
wire   [9:0] zext_ln30_fu_294_p1;
wire   [9:0] sub_ln30_fu_298_p2;
wire   [9:0] zext_ln30_1_fu_304_p1;
wire   [9:0] add_ln30_2_fu_307_p2;
wire   [4:0] mul_ln22_fu_322_p0;
wire   [5:0] mul_ln22_fu_322_p1;
wire   [9:0] mul_ln22_fu_322_p2;
wire   [6:0] tmp_3_fu_344_p3;
wire   [8:0] tmp_2_fu_337_p3;
wire   [8:0] zext_ln27_fu_351_p1;
wire   [63:0] shl_ln_fu_378_p3;
wire   [63:0] shl_ln30_1_fu_390_p3;
wire   [63:0] add_ln30_fu_385_p2;
wire   [63:0] add_ln30_1_fu_397_p2;
reg    grp_fu_167_ce;
reg    grp_fu_179_ce;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire   [9:0] mul_ln22_fu_322_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_start_reg = 1'b0;
end

kernel_symm_kernel_symm_Pipeline_VITIS_LOOP_26_3 grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_start),
    .ap_done(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_done),
    .ap_idle(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_idle),
    .ap_ready(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_ready),
    .select_ln22_1(select_ln22_1_reg_464),
    .zext_ln23(select_ln22_reg_458),
    .C_address0(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_address0),
    .C_ce0(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_ce0),
    .C_we0(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_we0),
    .C_d0(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_d0),
    .C_address1(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_address1),
    .C_ce1(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_ce1),
    .C_q1(C_q1),
    .add_ln27_1(add_ln27_1_reg_510),
    .A_address0(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_A_address0),
    .A_ce0(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_A_ce0),
    .A_q0(A_q0),
    .B_address0(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_B_address0),
    .B_ce0(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_B_ce0),
    .B_q0(B_q0),
    .mul_ln30(mul_ln30_reg_504),
    .temp2_out(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_temp2_out),
    .temp2_out_ap_vld(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_temp2_out_ap_vld),
    .grp_fu_167_p_din0(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_grp_fu_167_p_din0),
    .grp_fu_167_p_din1(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_grp_fu_167_p_din1),
    .grp_fu_167_p_dout0(grp_fu_167_p2),
    .grp_fu_167_p_ce(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_grp_fu_167_p_ce)
);

kernel_symm_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_167_p0),
    .din1(grp_fu_167_p1),
    .ce(grp_fu_167_ce),
    .dout(grp_fu_167_p2)
);

kernel_symm_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_temp2_out),
    .din1(grp_fu_171_p1),
    .ce(1'b1),
    .dout(grp_fu_171_p2)
);

kernel_symm_mul_32s_32s_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32s_32s_64_2_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(B_load_reg_484),
    .din1(grp_fu_175_p1),
    .ce(1'b1),
    .dout(grp_fu_175_p2)
);

kernel_symm_mul_64s_32s_64_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_64s_32s_64_5_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_ln30_reg_504),
    .din1(A_load_reg_499),
    .ce(grp_fu_179_ce),
    .dout(grp_fu_179_p2)
);

kernel_symm_mul_5ns_6ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 10 ))
mul_5ns_6ns_10_1_1_U16(
    .din0(mul_ln22_fu_322_p0),
    .din1(mul_ln22_fu_322_p1),
    .dout(mul_ln22_fu_322_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_start_reg <= 1'b1;
        end else if ((grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_ready == 1'b1)) begin
            grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_90 <= 5'd0;
    end else if (((icmp_ln22_fu_213_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_90 <= select_ln22_1_fu_251_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_fu_94 <= 10'd0;
    end else if (((icmp_ln22_fu_213_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_fu_94 <= add_ln22_1_fu_219_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j_fu_86 <= 5'd0;
    end else if (((icmp_ln22_fu_213_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_fu_86 <= add_ln23_fu_259_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_load_reg_499 <= A_q0;
        mul_ln30_reg_504 <= grp_fu_175_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        B_load_reg_484 <= B_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        C_addr_reg_474 <= zext_ln30_2_fu_313_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        C_load_reg_520 <= C_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln27_1_reg_510[8 : 2] <= add_ln27_1_fu_355_p2[8 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        alpha_cast_reg_445 <= alpha_cast_fu_187_p1;
        conv_i389_reg_440 <= conv_i389_fu_183_p1;
        sext_ln22_reg_450 <= sext_ln22_fu_191_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        mul_ln30_1_reg_540 <= grp_fu_167_p2;
        mul_ln30_3_reg_545 <= grp_fu_171_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        mul_ln30_2_reg_530 <= grp_fu_179_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln22_fu_213_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        select_ln22_1_reg_464 <= select_ln22_1_fu_251_p3;
        select_ln22_reg_458 <= select_ln22_fu_243_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        trunc_ln_reg_550 <= {{add_ln30_1_fu_397_p2[63:32]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        A_address0 = mul_ln22_cast_fu_328_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        A_address0 = grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_A_address0;
    end else begin
        A_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        A_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        A_ce0 = grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_A_ce0;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        B_address0 = zext_ln30_2_fu_313_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        B_address0 = grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_B_address0;
    end else begin
        B_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        B_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        B_ce0 = grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_B_ce0;
    end else begin
        B_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state9))) begin
        C_address0 = C_addr_reg_474;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        C_address0 = grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_address0;
    end else begin
        C_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state9))) begin
        C_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        C_ce0 = grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_ce0;
    end else begin
        C_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        C_ce1 = grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_ce1;
    end else begin
        C_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        C_d0 = trunc_ln_reg_550;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        C_d0 = grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_d0;
    end else begin
        C_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        C_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        C_we0 = grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_we0;
    end else begin
        C_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln22_fu_213_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln22_fu_213_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_167_ce = grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_grp_fu_167_p_ce;
    end else begin
        grp_fu_167_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_167_p0 = grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_grp_fu_167_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_167_p0 = sext_ln30_1_fu_369_p1;
    end else begin
        grp_fu_167_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_167_p1 = grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_grp_fu_167_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_167_p1 = sext_ln22_reg_450;
    end else begin
        grp_fu_167_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state8) & (grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_done == 1'b1)))) begin
        grp_fu_179_ce = 1'b1;
    end else begin
        grp_fu_179_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln22_fu_213_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_address1 = grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_C_address1;

assign add_ln22_1_fu_219_p2 = (indvar_flatten_fu_94 + 10'd1);

assign add_ln22_fu_231_p2 = (i_fu_90 + 5'd1);

assign add_ln23_fu_259_p2 = (select_ln22_fu_243_p3 + 5'd1);

assign add_ln27_1_fu_355_p2 = (tmp_2_fu_337_p3 + zext_ln27_fu_351_p1);

assign add_ln30_1_fu_397_p2 = (shl_ln30_1_fu_390_p3 + add_ln30_fu_385_p2);

assign add_ln30_2_fu_307_p2 = (sub_ln30_fu_298_p2 + zext_ln30_1_fu_304_p1);

assign add_ln30_fu_385_p2 = (shl_ln_fu_378_p3 + mul_ln30_2_reg_530);

assign alpha_cast_fu_187_p0 = alpha;

assign alpha_cast_fu_187_p1 = alpha_cast_fu_187_p0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign conv_i389_fu_183_p0 = alpha;

assign conv_i389_fu_183_p1 = conv_i389_fu_183_p0;

assign grp_fu_171_p1 = alpha_cast_reg_445;

assign grp_fu_175_p1 = conv_i389_reg_440;

assign grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_start = grp_kernel_symm_Pipeline_VITIS_LOOP_26_3_fu_152_ap_start_reg;

assign icmp_ln22_fu_213_p2 = ((indvar_flatten_fu_94 == 10'd600) ? 1'b1 : 1'b0);

assign icmp_ln23_fu_237_p2 = ((j_fu_86 == 5'd30) ? 1'b1 : 1'b0);

assign mul_ln22_cast_fu_328_p1 = mul_ln22_fu_322_p2;

assign mul_ln22_fu_322_p0 = mul_ln22_fu_322_p00;

assign mul_ln22_fu_322_p00 = select_ln22_1_reg_464;

assign mul_ln22_fu_322_p1 = 10'd21;

assign select_ln22_1_fu_251_p3 = ((icmp_ln23_fu_237_p2[0:0] == 1'b1) ? add_ln22_fu_231_p2 : i_fu_90);

assign select_ln22_fu_243_p3 = ((icmp_ln23_fu_237_p2[0:0] == 1'b1) ? 5'd0 : j_fu_86);

assign sext_ln22_fu_191_p1 = $signed(beta);

assign sext_ln30_1_fu_369_p1 = C_load_reg_520;

assign shl_ln30_1_fu_390_p3 = {{mul_ln30_3_reg_545}, {16'd0}};

assign shl_ln_fu_378_p3 = {{mul_ln30_1_reg_540}, {16'd0}};

assign sub_ln30_fu_298_p2 = (tmp_fu_280_p3 - zext_ln30_fu_294_p1);

assign tmp_1_fu_287_p3 = {{select_ln22_1_reg_464}, {1'd0}};

assign tmp_2_fu_337_p3 = {{select_ln22_1_reg_464}, {4'd0}};

assign tmp_3_fu_344_p3 = {{select_ln22_1_reg_464}, {2'd0}};

assign tmp_fu_280_p3 = {{select_ln22_1_reg_464}, {5'd0}};

assign zext_ln27_fu_351_p1 = tmp_3_fu_344_p3;

assign zext_ln30_1_fu_304_p1 = select_ln22_reg_458;

assign zext_ln30_2_fu_313_p1 = add_ln30_2_fu_307_p2;

assign zext_ln30_fu_294_p1 = tmp_1_fu_287_p3;

always @ (posedge ap_clk) begin
    add_ln27_1_reg_510[1:0] <= 2'b00;
end

endmodule //kernel_symm
